### PR TITLE
impstats: Updated python based statslog analyzer sample scripts.

### PR DESCRIPTION
**Pull request by alorbach**
Updated python sample scripts, should fix LGTM issues.

### CODE REVIEW

**Comment by rgerhards** [comment]
This pull request **introduces 5 alerts** and **fixes 6** when merging 9cf29f31dfd0608d878a3c995c2a2b8c1d69e62c into b40e29fd6297d78ec1d179b26768436ba635d429 - [view on LGTM.com](https://lgtm.com/projects/g/rsyslog/rsyslog/rev/pr-941ffd9dbd624b3d36f0af3af858bed4d65f56c3)

**new alerts:**

* 3 for Unreachable code
* 1 for Missing docstring
* 1 for Encoding error

**fixed alerts:**

* 6 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by rgerhards** [comment]
This pull request **introduces 2 alerts** and **fixes 6** when merging 09a8ed93332f02a581cc3c8f3175f25e111de3df into b40e29fd6297d78ec1d179b26768436ba635d429 - [view on LGTM.com](https://lgtm.com/projects/g/rsyslog/rsyslog/rev/pr-e6006b25cdca75d458df0609172067a825cd6d96)

**new alerts:**

* 1 for Missing docstring
* 1 for Encoding error

**fixed alerts:**

* 6 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alorbach** [comment]
lgtm is showing only alerts for deleted file "statslog-splitter.py" now.

**Comment by rgerhards** [comment]
ultra-fast reply from the lgtm.com guys: One of the new ones is missing in the report as the file was not change in the new commit: https://lgtm.com/projects/g/rsyslog/rsyslog/snapshot/51e31c2740563e493aa4e380ebd4dff7bbd5f82a/files/plugins/impstats/statslog-graph.py?sort=name&dir=ASC&mode=heatmap&showExcluded=true

@alorbach can you confirm?

For "Module None does not have a docstring" a fix is underway on the lgtm side (aka "don't care for now, will disappear).

**Comment by rgerhards** [comment]
This pull request **introduces 4 alerts** and **fixes 6** when merging a848392c027be2594ad5dc34b37db6bd39d077e6 into 99a339eb3e82c002091131dab4a73f67a3c3daa4 - [view on LGTM.com](https://lgtm.com/projects/g/rsyslog/rsyslog/rev/pr-d67b4f1cff73451221164d00dd31bd166127d808)

**new alerts:**

* 3 for Testing equality to None
* 1 for Unused import

**fixed alerts:**

* 6 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by rgerhards** [comment]
This pull request **fixes 6 alerts** when merging c8da318ded499a3bbfda47d2ac9cc9dc99a4541c into 99a339eb3e82c002091131dab4a73f67a3c3daa4 - [view on LGTM.com](https://lgtm.com/projects/g/rsyslog/rsyslog/rev/pr-d9373a52c12ab0afa52f586efddbf90c3f2dd0f1)

**fixed alerts:**

* 6 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by alorbach** [comment]
Should be all fixed now. Those 6 alerts are already fixed o.O

**Comment by rgerhards** [comment]
> Should be all fixed now. Those 6 alerts are already fixed o.O

lgtm looks at the commit as whole, so it is right in saying that the 6 alerts are fixed *compared to master*.

**Comment by alorbach** [comment]
Understood.... than all issues should be fixed

**Comment by rgerhards** [comment]
yeah... still let's wait for CI, even though it is just cosmetic here ;-)

**Pull request merged**
