### PR TITLE
Adding new format support for error file in omelasticsearch bulk insert mode

### PR DESCRIPTION
**Pull request by CodeHarsh**
Currently omelasticsearch dumps entire post data and response in error file in case for a failure in bulk insert mode. Wanted to introduce two format flags in action to format data in error file (Both of the flags can be used independently as well as together).

1. erroronly => This flag checks the response stream and logs only failed requests and response.
2. interleaved => This flag interleaves the request to its response and dumps it as pair.

When both flags are used we get only failed request in an interleaved format.

sample: action(server="localhost"
    XXX
    type="omelasticsearch"
    XXX
   errorfile="bad_message.log"
   erroronly="on"
   interleaved="on")

BugFix:
While checking if my code is causing any leaks or not, I found a valgrind error for "pWrkrData->batch.data" not sure if that was intentional or not. but I fixed it anyway.

### CODE REVIEW

**Comment by rgerhards** [comment]
I have begun to look into these patches. I haven't reviewed much, but I see that you use C++ style comments ("//"). Can you please change them to C-style, because C++ style breaks compilation on some platforms.

**Comment by rgerhards** [comment]
It also looks like the commits should be a little bit squashed. It's not absolutely vital, but would look better.

**Comment by CodeHarsh** [comment]
I have made changes for comment style and also corrected file name causing Travis failure.
I will try to squash the commits (i am new to git) and update.
Also not sure why threadingmqaq.sh test failed due to my changes.

**Comment by rgerhards** [comment]
Thx! I have restarted the travis test. I guess the threadingmqaq.sh has nothing to do with your changes. I think there is already an issue tracker for that test, as the test harness itself (not the code) seems to have an occasional race here. If the next run is OK, all is fine, else I'll investigate.

**Comment by CodeHarsh** [comment]
Hi Rainer, I have squashed commits into logical entities.

**Comment by CodeHarsh** [comment]
Hi Rainer,
Any update on this?

**Comment by rgerhards** [comment]
I still hope to get this into the next release (Apr 7th). But I admit I've slipped asking for feedback. So let's do that now: @radu-gheorghe any concerns?

**Comment by radu-gheorghe** [comment]
@rgerhards no concerns, it looks good to me. Thanks for the patch, @CodeHarsh!

**Comment by CodeHarsh** [comment]
Thanks @radu-gheorghe.
Very happy to hear this.

**Comment by rgerhards** [comment]
@CodeHarsh If no unexpected problem occurs during the multi-env testbench runs (none expected), we should be ready for 8.9.0 next week :-) Thanks for your help.

Would you also mind an update the doc at https://github.com/rsyslog/rsyslog-doc ?

**Pull request merged**
