### PR TITLE
Thorougher state-file renaming and cleaning

### LINKED ISSUE #3646: in some cases, inode-only statefile is left after creation state file filename with hash
### Expected behavior
when logfile grows, statefile should rename itself from `imfile-state:<inode>` to `imfile-state:<inode>:<hash>` so only the state file with relevant filename remains.

### Actual behavior
When rsyslogd starts and processes logfile from configuration, then it calculates hash/file_id and correctly tries renaming old inode-only statefile to the new filename including hash.
This can be seen working in this debug log:
```
1794.978609646:imfile.c       : imfile.c: pollFileReal enter, act 0x7f3918000c60, pStrm (nil), name '/var/log/test.log'
1794.978615968:imfile.c       : imfile.c: pollFileReal enter, edge 0x55859e4995a0
1794.978621488:imfile.c       : imfile.c: pollFileReal enter, edge->instarr 0x55859e499650
1794.978633279:imfile.c       : imfile.c: getStateFileName for '/var/log/test.log'
1794.978646803:imfile.c       : imfile.c: getStateFileName:  state file name now is imfile-state:10549370
1794.978657831:imfile.c       : imfile.c: file_id 'd8bffdcae7c306d3' obtained, closing monitoring file handle
1794.978670595:imfile.c       : imfile.c: getFileID for '/var/log/test.log', file_id_hash 'd8bffdcae7c306d3'
1794.978679342:imfile.c       : imfile.c: trying to open state for '/var/log/test.log', state file '/var/spool/rsyslog/imfile-state:10549370:d8bffdcae7c306d3'
1794.978693857:imfile.c       : imfile.c: state file /var/spool/rsyslog/imfile-state:10549370:d8bffdcae7c306d3 for /var/log/test.log does not exist - trying to see if inode-only file exists
1794.978702338:imfile.c       : imfile.c: found inode-only state file, renaming it now that we know the file_id, new name: /var/spool/rsyslog/imfile-state:10549370:d8bffdcae7c306d3
1794.978719063:imfile.c       : imfile.c: opened state file /var/spool/rsyslog/imfile-state:10549370 for /var/log/test.log
1794.978765292:imfile.c       : stream.c: file stream /var/log/test.log params: flush interval 0, async write 0
1794.978786325:imfile.c       : stream.c: file '/var/log/test.log' opened as #14 with mode 384
1794.978802523:imfile.c       : strm 0x7f3918002df0: stream.c: opened file '/var/log/test.log' for READ as 14
1794.978812882:imfile.c       : strm 0x7f3918002df0: stream.c: file 14 seek, pos 0
1794.978826606:imfile.c       : imfile.c: breopenOnTruncate 0 for '/var/log/test.log'
1794.978836827:imfile.c       : strm 0x7f3918002df0: stream.c: file 14 read 4096 bytes
1794.978860269:imfile.c       : imfile.c: getStateFileName for '/var/log/test.log'
1794.978872085:imfile.c       : imfile.c: getStateFileName:  state file name now is imfile-state:10549370
1794.978878427:imfile.c       : imfile.c: persisting state for '/var/log/test.log', state file '/var/spool/rsyslog/imfile-state:10549370:d8bffdcae7c306d3'
```

Problem is if the logfile grows while rsyslog is running. Then it leaves the old inode-only state file in place and seems to skip the logic regarding statefile renaming altogether.
In debug log there is no trace of that, and it immediately starts using the new filename with hash.
```
9694.485269885:main Q:Reg/w0  : wti.c: main Q:Reg/w0: worker IDLE, waiting for work.
9716.796348453:imfile.c       : imfile.c: INOTIFY event: watch was MODIFID
9716.796370089:imfile.c       : imfile.c: in_processEvent process Event 2 for
9716.796378024:imfile.c       : imfile.c: in_processEvent process Event 2 is_file 1, act->name '/var/log/test.log'
9716.796384275:imfile.c       : imfile.c: fs_node_notify_file_update: act->name '/var/log/test.log'
9716.796391084:imfile.c       : imfile.c: pollFileReal enter, act 0x7f510c000c60, pStrm 0x7f510c002da0, name '/var/log/test.log'
9716.796397323:imfile.c       : imfile.c: pollFileReal enter, edge 0x55b6924395a0
9716.796402833:imfile.c       : imfile.c: pollFileReal enter, edge->instarr 0x55b692439650
9716.796410731:imfile.c       : stream.c: checkTruncation, file /var/log/test.log, iBufPtrMax 0
9716.796420071:imfile.c       : strm 0x7f510c002da0: stream.c: file 13 read 4096 bytes
9716.796442443:imfile.c       : imfile.c: getStateFileName for '/var/log/test.log'
9716.796450141:imfile.c       : imfile.c: getStateFileName:  state file name now is imfile-state:10549370
9716.796463246:imfile.c       : imfile.c: file_id 'd8bffdcae7c306d3' obtained, closing monitoring file handle
9716.796471205:imfile.c       : imfile.c: getFileID for '/var/log/test.log', file_id_hash 'd8bffdcae7c306d3'
9716.796477947:imfile.c       : imfile.c: persisting state for '/var/log/test.log', state file '/var/spool/rsyslog/imfile-state:10549370:d8bffdcae7c306d3'
9716.796544551:imfile.c       : imfile.c: getStateFileName for '/var/log/test.log'
9716.796555200:imfile.c       : imfile.c: getStateFileName:  state file name now is imfile-state:10549370
9716.796561884:imfile.c       : imfile.c: persisting state for '/var/log/test.log', state file '/var/spool/rsyslog/imfile-state:10549370:d8bffdcae7c306d3'
9716.796655985:imfile.c       : imfile.c: getStateFileName for '/var/log/test.log'
9716.796667836:imfile.c       : imfile.c: getStateFileName:  state file name now is imfile-state:10549370
```

### Environment
- rsyslog version: 8.1904.0
- platform: Amazon Linux AMI release 2018.03(rhel based distro)

### LINKED ISSUE #3960: Imfile rename to hash-style state file limited
### Expected behavior
When monitored file exceeds the hash-style state file limit, old (inode-only) state file is removed

### Actual behavior
When monitored file exceeds the hash-style state file limit (currently 512B) old inode-style state file is left and can later cause log loss if the same inode is reused for another monitored file. State file renaming (so the old one is not present) only happens when file grows over hash threshold with rsyslog **not** running , which is in reality very rare condition combination.

### Steps to reproduce the behavior
Configure file monitor
Input test data (less than 512B)
Restart rsyslog
Input more data
Now there are two state files for one file

### Environment
- rsyslog version: 8.1910.0 
- platform:Fedora 
- for configuration questions/issues, include rsyslog.conf and included config files

### PR DESCRIPTION
**Pull request by jvymazal**
Now checking if file-id changes and reanming - cleaning state file
accordingly and always checking and cleaning old inode-only style
state files.

closes #3960
closes #3646
closes #3646

### CODE REVIEW

**Comment by jvymazal** [comment]
After further testing few more problems were found, namely that file_id was set constant within rsyslog run, so if changed (truncation) the saved state-file would have incorrect hash leading to mismatch after rsyslog restart.
Also inode-only state files were left over which could be later picked up when inode is reused and cause data loss (although probably only 512B)

closes #3960 
closes #3646 
closes #3646

**Comment by jvymazal** [comment]
@rgerhards it seems that `pmdb2diag_parse.sh`, `imtuxedoulog_errmsg_no_params-vg` and `imtuxedoulog_errmsg_no_params-vg` tests are quite flaky, do we know about this?

**Comment by rgerhards** [comment]
> it seems that `pmdb2diag_parse.sh`, `imtuxedoulog_errmsg_no_params-vg` and `imtuxedoulog_errmsg_no_params-vg` tests are quite flaky, do we know about this?

if so, it's new. I'll have a look, but don't manage to do it today.

**Comment by rgerhards** [comment]
@jvymazal this doesn't look like a flake. I took a look at the CentOS 7 fail and saw this:
```
rsyslogd: imfile.c:1264: getFileID: Assertion `act->fd >= 0' failed.
```
points directly to imfile. Thus I did not check any other testbench logs.

**Comment by jvymazal** [comment]
Alright, did not notice that one, thanks for pointer. Now that I see it, do you think it is better to always close and re-open file on persist or keep it opened the whole time? I am not that much familiar with performance/resource cost implications of this (or whether is there any difference at all).

**Comment by rgerhards** [comment]
> Now that I see it, do you think it is better to always close and re-open file on persist or keep it opened the whole time?

just a quick thought: keeping it open is most probably more performant. But it may complicate things more than it is worth...

**Comment by davidelang** [comment]
On Tue, 26 Nov 2019, Rainer Gerhards wrote:

>> Now that I see it, do you think it is better to always close and re-open file on persist or keep it opened the whole time?
>
> just a quick thought: keeping it open is most probably more performant. But it may complicate things more than it is worth...

keeping it open will perform better, but flush once in  while to be sure that 
the data gets to disk or you may loose it in an OS memory cache if the system 
crashes

David Lang

**Comment by jvymazal** [comment]
> keeping it open will perform better, but flush once in while to be sure that the data gets to disk or you may loose it in an OS memory cache if the system crashes

in this case I am using the open fd only to read from file, so there is no real risk of data loss

**Comment by jvymazal** [comment]
On my side this should now cover all scenarios we could think of, so we should be good to merge

**Pull request merged**
