### PR TITLE
omkafka: add support for dynamic keys

### PR DESCRIPTION
**Pull request by ludobrands**
Hi,

we needed a way to force the kafka partition based on the data being pushed. Pretty much the subject of #1421. Here is a patch that allows to use a template to provide the partitioning key.

A new configuration property "dynaKey" is added that, when "on", changes the value of property "key" to a template names instead of a constant value. This is similar in approach to the DynaTopic implementation.  

Our system uses mmjsonparse to extract from the message the property we use as a key. The config we are using  (the relevant part) :
```
module(load="omkafka")
module(load="mmjsonparse")

template(name="json_log" type="list") {
  constant(value="{")
    constant(value="\"@timestamp\":\"")  property(name="timereported" dateFormat="rfc3339")
    constant(value="\",\"tags\":[\"") property(name=".tag") constant(value="\"]")
    constant(value=",\"ctnewlog\": true,")
    property(name="$!all-json" position.from="2")
}

template(name="message_guid_template" type="list") {
  property(name="$!message_guid")
}
...
                action(type="mmjsonparse" cookie="")
                action(type="omkafka"
                        partitions.auto="on"
                        dynaKey="on"
                        key="message_guid_template"
                        template="json_log"
...                
                )
``` 

PR for documentation will follow.

### CODE REVIEW

**Comment by rgerhards** [comment]
Thx for the PR. You have probably seen that CI has raised some issues. It would also be great (and speed up merging) if you could add a test for the new functionality. If not, I'll see that I craft one when I have time and amend it to the PR.

**Comment by rgerhards** [comment]
side-note: as I know we have some flakes inside the CI, I have checked that there exist actual problems with the PR. Just so that you know.

**Comment by ludobrands** [comment]
Down to 1 codestyle issue (tab size is 4 in my IDE) and an error in travis CI that doesn't seem to be linked to my changes. 

No problem to create a test case for this. Had a look a tests/omkafka.sh. As a simple test I imagine the following:
1) create kafka topic with 2 or more partitions
2) set up a rsyslog config with a property value for the key template that is set from an env var
3) set env var to a random value and send M messages to rsyslog. 
4) repeat step 3) N times with different values for the env var 
5) for each partition P in the topic : kafkacat -p P -f '%k' ... | uniq | wc -l. Sum of line counts has to be N. If not, messages with same key where sent to different partitions.  

What do you think? 

Has the docker image everything to run the test?

**Comment by ludobrands** [comment]
Added tests/omkafkadynakey.sh. It uses the 7th digit of the kafka msg as key. So values 0 to 9. The check does a line count on `kafkacat ...-f '%p %k\n' | sort | uniq` which counts the number of partition-key combinations. The count has to equal 10. Sample stdout output of kafkacat:
```
root@a46b5623bd7f:/home/devel/rsyslog/tests# kafkacat -b localhost:29092 -e -C -o beginning -t HNyjt9vf -f '%p %k\n' | sort | uniq
0 4
0 5
0 6
0 7
1 0
1 1
1 2
1 3
1 8
1 9
```
All checks are OK now except for a new one in Codacy/PR introduced by omkafkadynakey.sh. Since those lines come from omkafka.sh and no expansion is expected, I think the failure has to be ignored. 

No clue what yesterday's travis-ci failure was about.

Documentation changes are in https://github.com/rsyslog/rsyslog-doc/pull/759

**Comment by rgerhards** [comment]
@ludobrands The new test is missing in ./tests/Makefile.am, so it is not executed. Can you have a look?

**Comment by ludobrands** [comment]
Yes, that was on purpose. Wanted to share the test methodoly and get some feedback on it before executing it on a system that isn't mine.

**Comment by rgerhards** [comment]
@ludobrands just FYI: CI is currently pretty busy - we may have flakes. I keep an eye on this and let you know if there is a real issue.

**Comment by rgerhards** [comment]
@ludobrands could you please squash the commits and best rebase to master? I did the merge conflict handling, but a squash would change the commit hash and so this would look unmerged. It's cosmetic, I know, but often confusing to folks coming in via google. Sry for not doing the merge somewhat earlier :-(

**Comment by rgerhards** [comment]
@ludobrands just FYI: if yo do not have time to rebase/squash, I'll do it next week,

**Comment by rgerhards** [comment]
@ludobrands 

> if yo do not have time to rebase/squash, I'll do it next week,

done - let's see how CI works out.

**Comment by rgerhards** [comment]
Solaris is false positive, also openCSW workers are now down - irgnoring

**Pull request merged**
