### PR TITLE
[WIP] http output module for posting logs to REST API

### PR DESCRIPTION
**Pull request by ctramnitz**
initial WIP PR for omhttp as suggested in #1797 
error handling has to be revamped to remove ES specific items

### CODE REVIEW

**Comment by rgerhards** [comment]
thx for the PR, much appreciated. I am away part of this week, so the review could take a couple of days. One thing I see immediately: can you move the plugin to the ./contrib directory, pls. That's where we usually start things that are not directly supported by the core dev team.  Depending on user reaction and if you have time to keep working on it, things can later migrate over to fully supported. Thx again!

**Comment by rgerhards** [comment]
please have a look, there is still quite a bit of inconsistent indention. It also looks like the impstats counters need some work. Probably a good idea to have a second look at the code before I do the final review. It would be appreciated if you could rebase to current master, so that CI can run again. Thx,

**Comment by rgerhards** [comment]
as there seems to be no more interest by @ctramnitz in pursuing this further BUT the PR looks like it could be useful for some folks, I have asked @PascalWithopf to fix the issues up and submit a new PR with the functionality.

We will totally remove the stats counters as they look highly suspicious - some are for sure wrong, for others I do not know. Better have no than wrong counters.

Once @PascalWithopf PR is and mergable, we can close this one here as UNMERGED.

**Comment by ctramnitz** [comment]
I am still interested, however I didn't have time to pursue it further. If someone else has resources to improve the suggested areas please go ahead, otherwise I may revisit this in a few weeks.

**Comment by rgerhards** [comment]
> I am still interested, however I didn't have time to pursue it further. If someone else has resources to improve the suggested areas please go ahead, otherwise I may revisit this in a few weeks.

that's great to hear. Let's merge what @PascalWithopf does and it would be great if you could later on check what we than have merged and do further improvements.

**Comment by rgerhards** [comment]
core functionality merged via https://github.com/rsyslog/rsyslog/pull/2993

**Pull request closed without merging**
