### PR TITLE
Fix journald excessive reloading behavior

### PR DESCRIPTION
**Pull request by jvymazal**
This is workaround for possible imjournal interaction with systemd
where journal invalidate fix is not present. The code tries to
detect SD_JOURNAL_INVALIDATE loop and not reload after each call.

### CODE REVIEW

**Comment by jvymazal** [comment]
This fixes #2931 
It works around journal  rotation detection bug and makes imjournal usable again even for people with systemd without [this](https://github.com/systemd/systemd/pull/5580/commits/09e1b51bf1a07bbc27a2036769860b909b0647e4) fix.

**Comment by rgerhards** [comment]
Thx!

I should probably re-enable the journal tests at least for the PR. Let me do that (hopefully soon). I'll then restart the related CI workers.

**Comment by jvymazal** [comment]
Ok, thanks, I have tried to look at logs you linked in the parent issue, however I am unable to determine what is wrong from them.

**Comment by rgerhards** [comment]
We see some issues again: https://build.rsyslog.com/#/builders/175/builds/660/steps/6/logs/test-suite_log

Not sure if this time it is related to busy log on the CI system...

**Comment by rgerhards** [comment]
I have re-initiated the run

**Comment by jvymazal** [comment]
Ok, I tried to go trough the log file:

On actual test output file there are only two messages (rsyslog start & shutdown), that is strange.
Next, here is what is in the journal on the bot (trimmed to relevant entries), in this order:
```
Oct 26 13:32:11 centos7-5-w3-1vcpu-1gb-fra1-02 rsyslogd[17327]: imfile: on startup file '/var/lib/buildbot/slave/rsyslog_centos7-5/build/tests/rstb_848663_1ee4d6b7.input' does not exist but is configured in static file monitor - this may indicate a misconfiguration. If the file appears at a later time, it will automatically be processed. Reason: No such file or directory [v8.39.0.master]
Oct 26 13:32:11 centos7-5-w3-1vcpu-1gb-fra1-02 rsyslogd[17327]:  [origin software="rsyslogd" swVersion="8.39.0.master" x-pid="17327" x-info="http://www.rsyslog.com"] start
Oct 26 13:32:11 centos7-5-w3-1vcpu-1gb-fra1-02 rsyslogd[17327]:  [origin software="rsyslogd" swVersion="8.39.0.master" x-pid="17327" x-info="http://www.rsyslog.com"] exiting on signal 15.
Oct 26 13:36:05 centos7-5-w3-1vcpu-1gb-fra1-02 imjournal_test[22377]: TestBenCH-RSYSLog imjournal This is a test message - 1540560965 - rstb_110547_944b496a
```
So, as you can see, rsyslog starts, exits almost immediately (within a second) and then, after almost 4 minutes, the tests message finally arrives.

Ant thoughts on this?

**Comment by rgerhards** [comment]
> So, as you can see, rsyslog starts, exits almost immediately (within a second) and then, after almost 4 minutes, the tests message finally arrives.
> 
> Ant thoughts on this?

strange - might this be caused by the journal being too busy?

**Comment by rgerhards** [comment]
@jvymazal FYI: I have re-initiated the test once again; prime reason this time is I want to see if I can gather coverage data. This does not work on the containers, as we do not have journal there running (nor systemd). I also hope the new run might bring up some more interesting info.

**Comment by rgerhards** [comment]
@jvymazal merging this now, it's definitely an improvement. I'll keep an eye on journal test performance and keep you posted if there is anything interesting.

**Pull request merged**
