### PR TITLE
tls bugfix: parameter 'StreamDriver.CRLFile' not known

### PR DESCRIPTION
**Pull request by century6**
imtcp: fix parameter 'StreamDriver.CRLFile' cannot be recognized in input()
omfwd: fix parameter 'StreamDriver.CRLFile' cannot be recognized in action()

Fixes: 844d1795a2b1 ("TLS CRL Support Issue 5081")

### CODE REVIEW

**Review by Cropi — CHANGES_REQUESTED** [review]
Hello,
I did a very quick look and in imtcp, the `streamdriver.crlfile` should be used as a module parameter and instance parameter as well. You patch does not support the former. Btw, thanks for pointing it out.

**Comment by century6** [comment]
> Hello, I did a very quick look and in imtcp, the `streamdriver.crlfile` should be used as a module parameter and instance parameter as well. You patch does not support the former. Btw, thanks for pointing it out.

I did not find such a description in the [document](https://www.rsyslog.com/doc/configuration/modules/imtcp.html). But perhaps this is a good idea.

**Comment by century6** [comment]
@Cropi Hello, I have added a commit [0126118511e9](https://github.com/rsyslog/rsyslog/pull/5402/commits/0126118511e9ad88748480ae178bf367aba3cebf), please review it. :)

**Review by rgerhards — APPROVED** [review]

**Comment by century6** [comment]
> solaris CI builders have env issues. So OK to merge with them failing.

It seems that this PR has been closed instead of being merged.

**Comment by rgerhards** [comment]
> It seems that this PR has been closed instead of being merged.

I think I accidentelly pressed the wrong button - sorry! I want to wait for the other builders to pass.

**Comment by century6** [comment]
> > It seems that this PR has been closed instead of being merged.
> 
> I think I accidentelly pressed the wrong button - sorry! I want to wait for the other builders to pass.

OK. : )

**Pull request merged**
