### PR TITLE
reverted str2num() bSuccess return to be consistent with past behavior

### PR DESCRIPTION
**Pull request by jvymazal**
attempt to solve #1476

### CODE REVIEW

**Comment by rgerhards** [comment]
I am not sure if this is the right path to take. That fixed an actual error, albeit I see that this fix causes change to existing behavior. Still, I think the new way of doing things is correct... Let's see what @davidelang means...

**Comment by davidelang** [comment]
In other languages, sending anything (including a null string) other than a valid number to the str2num() equivalent function returns 0, not -1 as is happening here (looking at the num2ipv4 tests in #1413 )

Since we have allowed $!var == 0 to be the same as $!var == "" in the past, we need to support that going forward (it's arguably wrong, but not insanely wrong, so backwards compatibility should win)

looking at the str2num function in rainerscript.c, we convert strings that contain text by bailing out at the first non-digit value, so str2num("a") = 0, with a failure code, which would be an argument against str2num("") = 0 with a success code.

I feel like I'm missing some background here just looking at the issues and pull requests. what was the misaddressing that could happen that was noticed in #1412 ?

but I would expect str2num("") to return 0 and num2ipv4("0") to return "0.0.0.0" so I don't see a problem with num2ipv4("") returning "0.0.0.0"

so I think the right thing to do here is to make the change listed here. But I would like more info on the potential problems this could cause.

**Comment by jvymazal** [comment]
I would agree with @davidelang , to be consistent I would say that if $!var == 0 is same as $!var == "" it should go like num2ipv4("0") is same as num2ipv4(""), hence the testbench commit.

**Comment by rgerhards** [comment]
I agree with you and @davidelang Just let me check if we need to look at some related code.

On the misadressing: I don't remember all details, but @jgerhards  found out that in some cases it happend and could even lead to a segfault. I think @jgerhards found this as a side-effect of running tests for the ip42num function. It had something to do with empty string (or so). So the fix is actually important. As @jvymazal recommened and @davidelang agreed, we should keep old semantics, but need to make sure the original problem is fixed.

**Pull request merged**
