### PR TITLE
NEW INPUT MODULE:: impcap, network packets input module

### PR DESCRIPTION
**Pull request by frikilax**
this module uses libpcap ([a network library by TcpDump](https://www.tcpdump.org/)) to give information about network packets transiting on the network

### CODE REVIEW

**Comment by frikilax** [comment]
Hello @rgerhards !
This is (finally) the replacement PR for #3432, IMPCAP module !

I'm currently working on some tests, but as this module is a bit particular, I need your help to know what can be tested with confidence:
- what kind of environment are the tests run on ?
- if it's run on several environments, can we skip tests depending on if conditions are not met ? (I'm very new to this, I'm not clear on if/how it can be done)
- I don't know if I can tests things like promiscuity, datalink type and the likes, is there a guaranteed environment with network interface(s) ? can some be created ? (bridges for example ?)

I will also work on the documentation

**Comment by frikilax** [comment]
this replaces #3432

**Comment by rgerhards** [comment]
> * what kind of environment are the tests run on ?

on "popular platforms" - no more specifics by intention, because everyone may run the testbench on every machine he likes. If you know, however, that something does not work e.g. on Solaris, the test can detect and skip this environment. But this should not be used as an excuse to ignore known-bad runs (except it is documented that a specific module is not available on said platform).

> * if it's run on several environments, can we skip tests depending on if conditions are not met ? (I'm very new to this, I'm not clear on if/how it can be done)

if you let me know a concrete sample, I can gladly help with that.

> * I don't know if I can test things like promiscuity, datalink type and the likes, is there a guaranteed environment with network interface(s) ? can some be created ? (bridges for example ?)

That's actually a problem. I admit I do not know how we could create a test env for this. @davidelang  do you have an idea/suggestion?

**Comment by davidelang** [comment]
On Tue, 26 Nov 2019, Rainer Gerhards wrote:

>> * I don't know if I can test things like promiscuity, datalink type and the 
>> likes, is there a guaranteed environment with network interface(s) ? can some 
>> be created ? (bridges for example ?)
>
> That's actually a problem. I admit I do not know how we could create a test 
> env for this. @davidelang do you have an idea/suggestion?

This is a problem, it requires making multiple VMs with theappropriate network 
configs for the test,I think that's more than the test harness is designed to be 
ble to do.

David Lang

**Comment by frikilax** [comment]
I assumed this would be somewhat complicated...
We can still use the "file" parameter to read a .pcap file and test the parsers (this parameter was first created for debugging purposes), but it will remain near impossible to test every functionality (and some should be trusted by the libpcap maintainers anyway)

**Comment by rgerhards** [comment]
> We can still use the "file" parameter to read a .pcap file and test the parsers (this parameter was first created for debugging purposes), but it will remain near impossible to test every functionality (and some should be trusted by the libpcap maintainers anyway)

I think this is an excellent solution given the complexity of the situation. I would appreciate if you could go forward in this direction.

**Comment by rgerhards** [comment]
@frikilax regarding the alignment issue, pls have a look here: https://github.com/rsyslog/rsyslog/pull/3719

**Comment by frikilax** [comment]
Provided all required tests pass and there are no changes requested, I consider this PR to be ready to be merged !

**Comment by rgerhards** [comment]
@frikilax 

> @rgerhards, Provided all required tests pass and there are no changes/addition requested, all is good to be merged on my part for this PR !

sorry - I completely missed this out in all the stress caused by the Corona crisis. Will now finally see to move it forward...

**Comment by rgerhards** [comment]
@frikilax I wonder if you would be willing to rebase to current master? If not, I can do it :-)

**Comment by frikilax** [comment]
> @frikilax I wonder if you would be willing to rebase to current master? If not, I can do it :-)

Done !

**Comment by rgerhards** [comment]
Merci!

**Comment by rgerhards** [comment]
@frikilax thx for your patience, it's finally merged :-)

**Pull request merged**
