### PR TITLE
Issue 2098 (logctl.c)

### PR DESCRIPTION
**Pull request by HugoSoszynski**
* Made the logctl usertool ISO C90 compliant.
 * Made the logctl usertool use a homogeneous coding style.

### CODE REVIEW

**Comment by rgerhards** [comment]
Thx a lot for the patch. I'll see that I enable building of that tool on some buildbot slaves. This may generate interim CI failures. I'll have a look at all of this and report when I am done.

**Comment by rgerhards** [comment]
I notice that some of the warning that still exist stem back to libbson. It researched and the issue seems to be fixed in more recent versions. I currently try to upgrade the build slaves, but maybe we need to add a workaround so that others can build without libbson upgrade.

**Comment by HugoSoszynski** [comment]
@rgerhards I posted a possible workaround in the issue #2108

**Comment by rgerhards** [comment]
@HugoSoszynski Thanks, indeed it is! I didn't get back to that issue after my forced departure to different work the past couple of days, so I didn't remeber (now I do, I actually read it a while ago when you posted). I'll still try to see if I can get one buildbot slave on the newer version so that we have this at hand as well. I won't spent too much time, though...

**Comment by rgerhards** [comment]
ok, I give up on the new library version for now. Preparing the work-around ;-)

**Comment by rgerhards** [comment]
"fixing" it via https://github.com/rsyslog/rsyslog/pull/2214

**Comment by rgerhards** [comment]
@HugoSoszynski do **not** close this issue -- I am working the merge into another PR to do a multi-PR solution process to nail the lib issue. All will look correctly merged when I am done (at least that's the plan ;)).

**Comment by rgerhards** [comment]
merging via PR https://github.com/rsyslog/rsyslog/pull/2214

**Pull request merged**
