### PR TITLE
default rules use container_name_and_id; include rulebase files in dist

### PR DESCRIPTION
**Pull request by richm**
Change the default filename rules to use container_name_and_id
Include the rulebase files in the dist / source tarball

### CODE REVIEW

**Comment by richm** [comment]
@davidelang

**Comment by rgerhards** [comment]
@richm @davidelang "bug" label would be correct?

**Comment by richm** [comment]
@rgerhards yes - I'm sure David would agree this is a bug

**Comment by davidelang** [comment]
Yes, there is a default value that doesn't work.

**Comment by rgerhards** [comment]
In the interim I have used:
```
- mmkubernetes bugfix: default rules use container_name_and_id
  also include rulebase files in dist
  Thanks to Richard Megginson for fixing the issue.
```
maybe it's sufficient...

**Comment by davidelang** [comment]
The rulebase file was in the source tree, but not included in the dist packages.

This solves that and gets the rulebase file to the admins who need it.

David Lang

**Pull request merged**
