### PR TITLE
omprog: added error handling and transaction support for external plugins

### PR DESCRIPTION
**Pull request by jsiwrk**
(Submitting this PR again; I have cleaned up my fork.)

I've implemented this planned feature myself as a personal challenge, to have some fun and learn. What's your opinion? Did you intend to implement it this way?

I have manually tested the patch and it seems to work very well. Also, the CI tests show no regression (although I'm not sure if the omprog module was sufficiently covered).

For my part the patch would be ready to merge, EXCEPT that I have not implemented any automated test. Sorry for that. I would need some guidance on how to do it. On the other hand I'm not sure if I will be able to dedicate enough time to this personal project in the short term, so it would be great if someone else could implement at least a first basic test.

Other pending things apart from the tests:
* Update the rest of the documentation. At least, add reference doc about the new omprog settings. I the patch is finally accepted I could contribute to this, I think it'll be easy.
* The clang analyzer gives a (presumably false) warning I don't know how to eliminate.
* I'm pretty confident the Python skeleton is sufficiently pythonic. However I'm a Python newbie, so it would be great if someone with more knowledge could review it.
* It seems rsyslog does not require the standard getline function to be available, and I didn't find any quality implementation of it within the rsyslog code. So I implemented my own getline within omprog.c, but probably should be placed somewhere else, since it is reusable.

Note: I had to reorder functions in omprog.c due to new dependencies between them. I realise this will make comparing changes a bit difficult, sorry for that. I've not attempted to minimize this with forward declarations since I haven't seen them used elsewhere.

### CODE REVIEW

**Comment by jsiwrk** [comment]
clang gives a warning in my code related to the strcmp macro expansion I don't know how to eliminate:
```
omprog.c:663:6: warning: The right operand of '-' is a garbage value
        if(!strcmp((const char*) line, "OK")) {
```
(The const cast is my last attempt to eliminate the warning, with no success.) I'm sure it's a false warning, but it seems it's causing the CI to fail (correct?). Could you help me please? I'm stuck with this issue.

**Comment by rgerhards** [comment]
@jsiwrk: that's a static analyzer error message - probably a false positive, but one we need to work around. I'll try to use the static analyzer on your branch and see what exactly it reports if run interactively.

**Comment by rgerhards** [comment]
wow...it's a pretty big patch, we need to review it in-depth. Just FYI

**Comment by rgerhards** [comment]
ok, the static analyzer in my machine is a slightly different (newer) version and it does not "detect" this "problem" - bad. I'll have a look at the bare code and try to guess what triggers the diagnostic :-(

**Comment by rgerhards** [comment]
OK, you did not give me permission to write back to your branch. This is what I tried:
```
Author: Rainer Gerhards <rgerhards@adiscon.com>
Date:   Wed Sep 6 09:03:20 2017 +0200

    work around static analyzer false positive

diff --git a/plugins/omprog/omprog.c b/plugins/omprog/omprog.c
index 2c1cdf1..fc5b6a7 100644
--- a/plugins/omprog/omprog.c
+++ b/plugins/omprog/omprog.c
@@ -660,7 +660,8 @@ readPipe(wrkrInstanceData_t *pWrkrData)
                ABORT_FINALIZE(RS_RET_SUSPENDED);
        }
 
-       if(strcmp(line, "OK") == 0) {
+       const char *const constOK = "OK"; /* static analyzer bails out if we strcmp "OK"... */
+       if(strcmp(line, constOK) == 0) {
                iRet = RS_RET_OK;
        } else if(strcmp(line, "DEFER_COMMIT") == 0) {
                iRet = RS_RET_DEFER_COMMIT;
```

**Comment by jsiwrk** [comment]
I think the problem is not related to the "OK" constant but the "line" argument... If your attempt doesn't work I will try initializing "line" to an empty string before calling readline, maybe clang is considering it has not been properly initialized (?). "Garbage value" seems to indicate this.

> you did not give me permission to write back to your branch

Sorry, this is my first public PR... I see the "Allow edits from maintainers" flag is already enabled for this PR. I have added you as a collaborator to my repo, will that suffice?

> wow...it's a pretty big patch, we need to review it in-depth

Sure! I hope you'll find it interesting. It seems a great feature since it enables rsyslog plugins to be implemented in any language with essentially the same power (I think) than native plugins.

**Comment by jsiwrk** [comment]
I think I have finally managed to fool the analyzer by moving the code to a separate function. (At least one clang job has successfully completed on my repo CI. I hope the PR will pass the full CI now.)

**Comment by rgerhards** [comment]
It would be great if you could rebase to master as this fixes some glitches we have seen in CI. I'll try to review asap, but this might take some more time. Sorry for that.

**Comment by jsiwrk** [comment]
Rebased to master.

**Comment by rgerhards** [comment]
@jsiwrk question for you: will you be available to work on fixes if users see a regression? If so, I could merge without doing a fully complete evaluation, aka "faster"

**Comment by rgerhards** [comment]
@jsiwrk sorry for the delay, but I am ready to finally move towards it. Would it be possible that you once more rebase it to current master? That would be very useful, especially as it would benefit from the new checker tools I build into the testbench. If not possible, I'll merge via a merge PR, not a big deal :-)

**Comment by jsiwrk** [comment]
@rgerhards: Yes, I would be willing to work on fixes. Let's say with a one-week delay or so.

OK, I'll rebase to master shortly.

**Comment by rgerhards** [comment]
that's great news! I'll see that I merge over the weekend at latest!

**Comment by rgerhards** [comment]
oh, and BTW: have a look at the PR after the rebase -- the new CI system might have something to complain ;-)

**Comment by jsiwrk** [comment]
Rebased to master. It seems two checks have failed with a "Not enough space" error, which is related to your build infrastructure I imagine. Three other checks are pending at the time I'm writing this. Let me know if I need to update something in the PR.

**Comment by rgerhards** [comment]
Looks great, thx! The critital tests have passed (Ubuntu16 with the new static analyzer). The solaris slaves currently have issues, we are working with OpenCSW (who provides them) on a solution. Right now, the work-around is to restart, what I have done. I don't expect any problems being detected by them.

**Comment by rgerhards** [comment]
@jsiwrk Thanks again for all your good work. I finally merged, sorry it took so long. I also did a good review, albeit not totally in-depth. But what I saw looked very nice. I'll have Coverity also scan the code soon, let you know if something comes up.

Again, thanks for this great contribution -- I think it will be very valuable for the community!

**Comment by rgerhards** [comment]
@jsiwrk Coverity scan also looks good!

**Comment by jsiwrk** [comment]
@rgerhards: Thanks for merging. I will try to find time to add more documentation (reference doc on the new omprog parameters) and (most importantly) some automated tests.

**Pull request merged**
