### PR TITLE
Issue #1629: implement 'fileoffset' as imfile metadata 

### PR DESCRIPTION
**Pull request by derekjsonar**
As per the discussion in the mailing list here and issue #1629:
http://lists.adiscon.net/pipermail/rsyslog/2017-June/044498.html

### CODE REVIEW

**Comment by derekjsonar** [comment]
It would be great for this PR to make the v8.28 milestone, if possible. 

As per the CONTRIBUTING guidlines I have added an rsyslog-doc PR here: 
https://github.com/rsyslog/rsyslog-doc/pull/348

If there's something else I can do to make the v8.28 milestone please advise.

**Comment by rgerhards** [comment]
We are already past the 8.28 merge frame; however I have some more late merge, so it might be possible...

**Comment by rgerhards** [comment]
The PR basically looks pretty good, but I would like to have a testbench test to ensure the new functionality works as expected.

**Comment by rgerhards** [comment]
@davidelang do you think this should be optional so that we save the write in those (potentially frequent) cases the file offset is not needed? I tend to think "no", because in the imfile context this is still pretty lightweight, and may affect only very heavy users... which would make sense to wait until somone complains.

**Comment by davidelang** [comment]
I think there is far more of a win working to improve all variable performance than in adding options to enable and disable different pieces of metadata. There is a cost to every option added, and I don't see a lot of value in disabling this.

**Comment by derekjsonar** [comment]
If I add a script alongside one of the tests/imfile-wildcards* that verifies some of the fileoffset functionality is that automagically registered as a testbench test? I'm happy to give this a shot but I'm unfamiliar with your testbench system -- if you have any pointers for me or more documentation, please let me know. Thanks!

**Comment by rgerhards** [comment]
That would be great. Actually all you need to do is copy such a test as proposed, be sure it checks the offset. It does not auto-register, but it's a simple to do: open ./testbench/Makefile.am and search for existing test. Add new test to the same spots. That's all. The CI system will then automatically apply the new tests. It is advised to use ```make check TESTS="new-test.sh"``` to verify the new test locally before pushing to the PR. Any questions, just let me know.

**Comment by rgerhards** [comment]
One more question as I have not been able to dig into the details: what exactly is the offset showing? I would assume the file offset where the message started. Is that right? If so, that should probably be explicitly mentioned in the doc.

Is it obeyed correctly in all cases, e.g. if imfile is doing block reads because the unprocessed data is large?

**Comment by derekjsonar** [comment]
Ok -- I'll work on adding some tests.

As for the behaviour, if you had 
```
$template offsets,"%$!metadata!filename%^$!metadata!fileoffset%^%msg%"
```

And we had an imfile input watching `test.txt` with the following lines:
```
hello
rsyslog
fileoffsets
```

The resulting output messages would be:
```
test.txt^6^hello
test.txt^14^rsyslog
test.txt^26^fileoffsets
```

So the fileoffset is the number of bytes including the new line of all preceding input messages including the current one.

I'm not sure how to trigger block reads -- if that's one of the existing testbench examples, I can incorporate that.

**Comment by rgerhards** [comment]
Block reads happen if the file contains more than one line since the last read. The simplest way to trigger it is to create a file with a couple of lines before startup. I think the after-the-msg offset is a bit unusual, though I understand it's simplicity. All in all, I get the impression we should not rush merging this after the merge window has closed but give some room for more comments.

**Comment by rgerhards** [comment]
@kortemik I'd really love to get your feedback on the handling of offset here.

**Comment by rgerhards** [comment]
@derekjsonar sorry, too late for 8.28. Anyways, 8.29 will be out 8/8 ;-)

**Comment by davidelang** [comment]
I understand that at the time the metadata is created, the line has been read 
in, so the pointer address you are reading is at the end of the line.

But if we have trivial access to the line length, I think we should subtract it 
so that the offset points at the beginning the line we are reporting.

By trivial access, I mean if we have the length in a variable already. If we 
have to run a loop to count the bytes in some string to get the length, it's 
probably not worth it.

Or, if we can move the creation of the metadata variable up to the beginning of 
the read rather than the end, so that it grabs the data before reading the 
line...

I know that when using this to troubleshoot what's going wrong when reading a 
file, having it 'point at the start of the next line' instead of pointing at the 
start of the current line would confuse me for a bit.

**Comment by rgerhards** [comment]
@davidelang I tend to merge this patch as experimental with the doc explicitly saying the offset calculation might change in the future. I guess I won't be able to look into that before 8.29 release window close (tomorrow) but I think the patch is useful as is.

Comments anyone?

**Comment by davidelang** [comment]
sounds reasonable.
kk

**Comment by kortemik** [comment]
I think we can test this for now, but need to see into the other chunking
feature later!

-Mikko

**Comment by rgerhards** [comment]
Do **NOT** close #1633, it will automatically be merged and closed when this PR here is merged.
I have based new PR #1758 on this PR; however it contains the change to make fileoffset point to the begin of the message, not the end.

**Pull request closed without merging**
