### PR TITLE
Do not create empty objects when accessing non-existent keys

### LINKED ISSUE #4430: accessing a non-existing key creates an empty parent object
Hello,

Here is a behavior that is a bit annoying.
I tried to have a look at it a while ago but seems to be a bit difficult for me...

### Expected behavior

I would expect that rainerscript statement  `if ($!foo!bar != "") then ...` do not create a `$!foo` empty object if `$!foo` did not exist before the statement is executed.

### Actual behavior

Performing a condition (eg: check for an empty string) on a subtree key that do not exists (depth > 1 from the root container), creates an empty "parent" object. Depending on your context, you may end up with (kind of...) annoying garbage when producing object documents (for instance to index in ES).

I think I could live with it if I was able to check for object type on the parent before performing the condition, or maybe just having a sort of isset() test function. However that really feels like a bug, so I felt it was a good idea to start sharing on this topic, because Rainer or someone else could have an idea for a quick fix!

### Steps to reproduce the behavior

```
unset $!; 

if ($!source!ip == "") then
    set $!source_ip_was_empty_or_not_set = 1;
else
    set $!source_ip_was_empty_or_not_set = 0;

if ($!a!b!c!d == "") then
    set $!a_b_c_d_was_empty_or_not_set = 1;
else
    set $!a_b_c_d_was_empty_or_not_set = 0;  
```
Produces:
```
{ "$!": { "source_ip_was_empty_or_not_set": 1, "a": { "b": { "c": { } } }, "a_b_c_d_was_empty_or_not_set": 1 } }
```

### Environment
- rsyslog version: 8.2006.0
- platform: CentOS 8

### LINKED ISSUE #4436: hang condition in some plugins due to param-passing mode
A plugin can instruct rsyslog to provide template content as JSON. This is used very seldomly, currently only seen in omjournal and ommongodb, Even more, this use does not look valid (to be left for other issues). So the practical consequences of this bug look like nil.

Rsyslog core hangs when
* OMSR_TPL_AS_JSON passing mode is requested by plugin
* at least one message or local variable is present in message object
* the template uses subtree mode
* the subtree path contains at least one non-existing component

Under these conditions, rsyslog enters an infinite loop.

Severity: none, as the OMSR_TPL_AS_JSON option is not used by any important plugin and seems not to work in the two plugins that seem to support it.

### PR DESCRIPTION
**Pull request by julthomas**
This is a proposal for Github issue rsyslog/rsyslog#4430:
accessing a non-existing key creates an empty parent object
https://github.com/rsyslog/rsyslog/issues/4430

When looking up an object property, the tree of intermediate
object containers was ceated by get and del functions. The
patch is an attempt to fix that behavior by passing 0 to the
bCreate argument of jsonPathFindParent().

There is also one case where the return value of
jsonPathFindParent() was not checked, in the recurssive call
of jsonPathFindParent() itself. This was leading to infinite
loops if bCreate was 0.

closes #4430 
closes #4436

### CODE REVIEW

**Comment by rgerhards** [comment]
Thx, for the PR. I'll evaluate. I would suspect that there are some side-effects, but CI looks fine. Co-incidentally I am working on the `exist()` (#4385) function right now.

**Comment by julthomas** [comment]
Thank you Rainer.
Indeed the exist() function would be great to have as well!

**Comment by rgerhards** [comment]
@julthomas if things turn out well, I'll probably merge your PR first (neat and lean) and rebase mine. But I guess we need some more check to ensure we do not accidently break things. Will see that I create and merge them first, than we can carry on. I'll possibly focus on #4435 first so that I do not lose content by jumping to other things. So pls bear with me maybe a couple of days.

**Comment by rgerhards** [comment]
As a side-note, I think the endless loop you discovered could affect existing functionality as well. It's one of the first things on my tests-to-create list.

**Comment by julthomas** [comment]
OK Rainer no worries. So you now I've been running the patch for a while 
now on a setup with lots of liblognorm and $! manipulations (an 
Elasticsearch front); so far I did not see problems.

**Comment by rgerhards** [comment]
I found the bug: #4436 -- I guess this PR also fixes it, but will verify.

**Comment by rgerhards** [comment]
@julthomas yes, it fixes #4436 ; it will not add a test to CI as the whole code path looks pretty unused, and hard to test due to no valid way to use it ;-)

**Review by rgerhards — APPROVED** [review]
Looks like you have exactly found and fixed the cause -- thx!

**Pull request merged**
