### PR TITLE
omhttp: add basic support for Loki Rest

### PR DESCRIPTION
**Pull request by dmolik**
Loki is a new message indexer and querier from Grafana Labs. See
https://github.com/grafana/loki for details on Loki.

This change provides the initial message structure to send bulk message
payloads to the Loki Rest endpoint. omhttp, recieved a new bulk message
format called lokirest. Additionally, the plugin relies on the user to
provide the correct "stream" read message format.

A loki template must be json compatible and include a "stream" key of
key value tags, and a values key of an array of 2 element arrays, where
each 2 element array is the unix epoch in nanoseconds followed by an
unstrectured message.

An example:

    template(name="array_loki" type="string" string="{\"stream\":{\"host\":\"%HOSTNAME%\",\"facility\":\"%syslogfacility-text%\",\"priority\":\"%syslogpriority-text%\",\"syslogtag\":\"%syslogtag%\"},\"values\": [[ \"%timegenerated:::date-unixtimestamp%000000000\", \"%msg%\" ]]}")

### CODE REVIEW

**Comment by dmolik** [comment]
in reference to #3976

**Comment by dmolik** [comment]
forced pushed on the lgtm alert

**Comment by dmolik** [comment]
Added tests

**Comment by rgerhards** [comment]
FYI: we currently have some flakes in CI. I am working on this.

**Comment by dmolik** [comment]
No worries I have to rebase, so let me know when you want to try another ci run. In the meantime I'll update documentation.

**Comment by rgerhards** [comment]
doc PR: https://github.com/rsyslog/rsyslog-doc/pull/862

**Comment by rgerhards** [comment]
@dmolik Thanks for the well-crafted PR including doc. Actually I am very happy to be able to merge it! :-)

**Comment by dmolik** [comment]
Thank you!

**Pull request merged**
