### PR TITLE
omkafka: Add ability to dump librdkafka statistics to a file

### PR DESCRIPTION
**Pull request by pcullen65**
Use statsFile to specify statistics output file; also requires setting statistics.interval.ms confparam to a non-zero value.

### CODE REVIEW

**Comment by pcullen65** [comment]
I don't believe the two buildbot failure are related to the changes in this PR. As my first PR to rsyslog, please let me know if there's anything else I need to do. Thanks.

**Comment by rgerhards** [comment]
Thx for the PR! The CI failure is indeed unrelated, I'll handle it. Anything else, I let you know after review.

**Comment by rgerhards** [comment]
@pcullen65 It would be great if you could add the relevant doc at https://github.com/rsyslog/rsyslog-doc

**Comment by rgerhards** [comment]
> also requires setting statistics.interval.ms confparam to a non-zero value

I wonder if this is something that the code should check, At a minumum, it should be documented in a way that is expected to not be overlooked ;-)

**Comment by rgerhards** [comment]
I would be great if you could craft a new test based on some of the kafka tests. Understood, though, if too much effort ;-)

**Comment by pcullen65** [comment]
See PR #769 in rsyslog-docs project for corresponding documentation update.

**Pull request merged**
