### PR TITLE
add property options to support ISO week/year number

### PR DESCRIPTION
**Pull request by mbarbon**
This addresses the issues with date-week reported in #2845

### CODE REVIEW

**Comment by rgerhards** [comment]
please add doc to https://github.com/rsyslog/rsyslog-doc/

**Comment by mbarbon** [comment]
> please add doc to https://github.com/rsyslog/rsyslog-doc/

I created https://github.com/rsyslog/rsyslog-doc/pull/959 (it delegates the actual explanation on ISO weeks to Wikipedia, let me know if you prefer me to add more details directly to the docs)

**Comment by rgerhards** [comment]
sry, for the delay, i was distracted. Somehow CI also did not fire correctly. Could you do me a favor and do a 
```
git commit --amend #without Changes!
git push -f
```
locally just to initiate a new CI run. Would be great. Else, I'll craft a dummy mirror PR to get this fired.

**Comment by rgerhards** [comment]
as of 4840 CI passes, so we are good to merge

**Pull request merged**
