### PR TITLE
imfile: re-enable support for readind old-style state files

### PR DESCRIPTION
**Pull request by rgerhards**
see also https://github.com/rsyslog/rsyslog/issues/2231#issuecomment-376862280

### CODE REVIEW

**Comment by sjvs** [comment]
Hi @rgerhards: can you point me at the lgtm failure that you report in d8504e4? It's not immediately obvious to me why enabling mmkubernetes shouldn't work. As far as I can see on lgtm.com the C/C++ analysis after enabling mmkubernetes worked fine:

Here's the info for the original merge commit: https://lgtm.com/projects/g/rsyslog/rsyslog/rev/1c78e8c59ef98d4934d9cb19959c4fa86dd9eff2

And here's the analysis status for a more recent commit: https://lgtm.com/projects/g/rsyslog/rsyslog/rev/c4577375c21eac555592e07c94a8454ad424965d

**Comment by rgerhards** [comment]
@sjvs thx again for your help! I was a bit stunned as well. The commit was amended, so I do not know how to get the previous URL for that one. If you see it inside the system, it is the previous PR on this branch. If you also do not see it, I can craft a new testing PR based on master. Pls let me know.

**Comment by sjvs** [comment]
I can see that some commits in #2592 were analysed by lgtm.com, but I can't find any analysis or build failures in our logs. Are you sure the problem wasn't related to the branch being unmergeable or something like that?

I'll keep on digging and will let you know if I found anything! In the meantime it may be worth re-enabling mmkubernetes in this PR to see whether the analysis succeeds.

**Comment by rgerhards** [comment]
@sjvs strange - now it works. I know for sure it did not for at least two runs in a row :-S I'll keep it enabled and ping you should the problem re-occur. 

Ahh, I see one issue with mmkubernetes: it does not check for liblognorm but uses it. It looks like some of the lgtm.com build VMs have 2.0.3+ available, some not (transition process?)

**Comment by richm** [comment]
@rgerhards I've been mostly using liblognorm 2.0.2 (RHEL7) - to build with 2.0.2, you have to set `-DNO_LOADSAMPLESFROMSTRING=1` in CFLAGS since `ln_loadSamplesFromString` is only available in 2.0.3 and later.  I could not find another way to automatically detect the presence of this function, or the liblognorm version, at compile time.  I suppose I should have added an AC_CHECK_FUNC or something like that.

as for libfastjson, I've been using libfastjson-0.99.4 (RHEL7)

**Pull request merged**
