### PR TITLE
Configurable connection timeout for omrelp

### PR DESCRIPTION
**Pull request by nbrownus**
Exposes the connection timeout added in [librelp#29](https://github.com/rsyslog/librelp/pull/29) pull request.

### CODE REVIEW

**Comment by rgerhards** [comment]
@mbrownus: just in case you didn't notice, the patch did not pass CI testing.

**Comment by nbrownus** [comment]
@rgerhards the tests should pass once [librelp#29](https://github.com/rsyslog/librelp/pull/29) is merged and a new build of librelp is made

**Comment by rgerhards** [comment]
@nbrownus FYI: I currently have some trouble with the RELP TLS test. Not sure if it is new trouble, or just trouble not yet seen. I am investigating, but unfortunately it's not very consistent...

**Comment by rgerhards** [comment]
I had to revert the librelp changes, as they broke at least TLS. See https://github.com/rsyslog/librelp/pull/32

**Comment by nbrownus** [comment]
Found the issue and created a new pr rsyslog/librelp#33

```
./sndrcv_relp_tls.sh 
===============================================================================
[sndrcv_relp.sh]: testing sending and receiving via relp
------------------------------------------------------------
Test: ./sndrcv_relp_tls.sh
------------------------------------------------------------
rsyslogd started with pid  27952
rsyslogd started with pid  27952
  PID TTY          TIME CMD
27983 ?        00:00:00 rsyslogd
rsyslogd2 started with pid  27983
rsyslogd2 started with pid  27983
00001 open connections
starting run 1
Sending 50000 messages.
00050000 messages sent
runtime: 0.045
00001 close connections
End of tcpflood Run
Shutting down instance 2
imdiag[13501]: mainqueue empty
imdiag[13500]: mainqueue empty
```

**Comment by rgerhards** [comment]
merged via #1078 -- this one does not appear as merged as I needed to rebase and thus the commit hash changed.

**Pull request closed without merging**
