### PR TITLE
Fix passing the value to EscapeChar.

### PR DESCRIPTION
**Pull request by lonicerae**
* Properly handle the EscapeChar after refactor.

### CODE REVIEW

**Comment by rgerhards** [comment]
do you have a sample conf that trigges the behavior?

**Comment by Cropi** [comment]
I see that in `doGetChar`, the handler function `setParserControlCharacterEscapePrefix` is called with the appropriate escape character, which is type of `uchar`. However, `setParserControlCharacterEscapePrefix` expects it to be `uchar *`, that's where the segfault happens.

I would rather use a different type than `uid_t`, as it's usually used to hold a used ID. Ideally a replacement could be `uchar`.

**Review by Cropi — APPROVED** [review]
LGTM!
I tried out the both `parser.controlcharacterescapeprefix` and `$controlcharacterescapeprefix` versions, it works. Thanks for the patch.

**Comment by Cropi** [comment]
Can we add this to the next milestone? Thanks.

**Comment by rgerhards** [comment]
thx for the reminder AND the PR. Now merged.

**Pull request merged**
