### PR TITLE
ompipe: add action parameter tryResumeReopen

### PR DESCRIPTION
**Pull request by julthomas**
Hello Rainer,

Sometimes we need to reopen a pipe after an ompipe action gets suspended. Sending an HUP signal to rsyslog does the job but requires an interaction with rsyslog. The patch adds support for a new boolean option, tryResumeReopen, for the ompipe action. It mimics what an HUP signal would do.

We have issues with ompipe in the following context:
- ompipe writes to a Nagios 4 command fifo
- Nagios gets restarted
- The rsyslog ompipe action suspends but never resumes, even with action.resumeinterval and action.resumeintervalmax set to small values, and action.resumeretrycount set to -1. I believe the select() call always returns 0.

Using this patch works for us. It adds option tryResumeReopen and keeps the current behavior by default ("off" by default). I am not sure if it is properly designed, would you consider including it?

Best regards,
Julien

### CODE REVIEW

**Comment by rgerhards** [comment]
Thx for the PR, much appreciated. Please note: CI is currently a bit flaky as I work on it. Any real issue I let you know.

**Comment by rgerhards** [comment]
please add doc to https://github.com/rsyslog/rsyslog-doc/

**Comment by julthomas** [comment]
Hello Rainer,

Proposed pull-request for the documentation:
rsyslog/rsyslog-doc#881

Regards,
Julien

**Comment by julthomas** [comment]
I have a doubt about the mutex lock on the close and -1 reset on the file descriptor.
It is not taken as well in doHUP, what do you think?
Julien

**Comment by rgerhards** [comment]
> I have a doubt about the mutex lock on the close and -1 reset on the file descriptor.
> It is not taken as well in doHUP, what do you think?

sry for the delay ... it's an exceptional time... I reviewed the comment and originally, on quick look, it seemed to be a question about this PR. That was why I didn't merge quickly. Now I see it is a related but different issue. I think you are right, will try a patch. That also means I can finally merge this PR :-)

Thanks again for your help and patience.

**Pull request merged**
