### PR TITLE
lexer.l: change to PRAGMA macros

### PR DESCRIPTION
**Pull request by rgerhards**

### CODE REVIEW

**Comment by pduveau** [comment]
Hi @rgerhards, I don't think that moving rsyslog.h above system includes is a good idea. I think you should move all includes in %top block and put the pragmas at the end of the block as well.

**Comment by pduveau** [comment]
Ok as soons as this RP is merged. I'll rebase again.

**Comment by rgerhards** [comment]
did this as side-activity while in the meeting. Will merge when CI is through. Thx for the suggestion!

**Comment by rgerhards** [comment]
@pduveau merged - some Solaris is missing in CI, but one is through so I think it was OK to merge. Solaris workers are right now veeeery slow. I guess OpenCSW is having issues.

**Pull request merged**
