### PR TITLE
Add configuration item `queue.samplinginterval` for queue

### PR DESCRIPTION
**Pull request by zacharyzhao**
For solving problem mentioned in issue #1135, New configuration item `queue.samplinginterval` is added, providing a way setting a interval of sampling logs by line.

### CODE REVIEW

**Comment by rgerhards** [comment]
I have rebased to current master so that we can get a good testbench run.

**Comment by rgerhards** [comment]
sorry for being so late. Could you please also update the queue parameters doc in the rsyslog-doc page. Otherwise, nobody knows about the new parameters, which means it is not usable.

**Comment by zacharyzhao** [comment]
OK, thanks for reply, I will do it soon.

**Comment by rgerhards** [comment]
Thx, much appreciated. Looking forward to the PR.

**Pull request merged**
