### PR TITLE
imgssapi: Incooperate changes from tcpsrv subsystem

### PR DESCRIPTION
**Pull request by Whissi**
Commit 5c5a7a3ed509dfb39b451c806646ab67782f6eda introduced an additional parameter "oserr".

Fixes: https://github.com/rsyslog/rsyslog/issues/1838

### CODE REVIEW

**Comment by Whissi** [comment]
I am wondering about the ```!= RS_RET_OK``` check. Is this still required? You removed it in other places due to commit 75063e54b2a95416c0fd32b2ae1df9b8db776b5c but not in *imgssapi.c*.

**Comment by rgerhards** [comment]
ah, our actions crossed :-) I also have begun to work on this. Will merge your one first, and add my changes on top of it. I am also looking to activate imgssapi build in travis, let's see how this works out.

On the iRet check: it's an error, you should remove it.

**Comment by Whissi** [comment]
I pushed 2 additional commits: I removed the iRet value check and also tried to enable Kerberos on Travis. Not sure why the two commits not showing up here...

**Comment by rgerhards** [comment]
GitHub seems to have some issues. I have a working Travis ci patch in my
branch. It's more than just seeing the option. But I cannot fully test at
the moment. If say let's wait for GitHub before doing more out of sync.

Rainer

Sent from phone, thus brief.

Am 17.10.2017 18:17 schrieb "Thomas Deutschmann" <notifications@github.com>:

**Comment by rgerhards** [comment]
@Whissi I could now verify (personal travis) that my new CI test actually caught the error and now works. I would appreciate if you could remove commit 30b0ea4 from your patch. I'll then merge your one first and after that mine (https://github.com/rsyslog/rsyslog/pull/1855 which also corrects the other build issues in imgssapi).

**Comment by rgerhards** [comment]
looks like due to the github issues yesterday travis did not pick up all of my commit -- at least it is now also showing additional errors. I will be working on that over the day...

**Comment by Whissi** [comment]
I dropped commit 30b0ea4 as requested.

**Comment by rgerhards** [comment]
thanks!

**Pull request merged**
