### PR TITLE
OMMONGODB :: Add other supported formats for 'time' and 'date' fields

### PR DESCRIPTION
**Pull request by frikilax**
This replaces PR #3432 ommongodb part.

All credits goes to @KGuillemot.

### CODE REVIEW

**Comment by rgerhards** [comment]
@frikilax do we need some doc update?

**Comment by frikilax** [comment]
> @frikilax do we need some doc update?

@KGuillemot ?

**Comment by frikilax** [comment]
> > @frikilax do we need some doc update?
> 
> I would say no, but I would like @KGuillemot to validate this

OK confirmed, this does not require a doc update

**Comment by rgerhards** [comment]
> OK confirmed, this does not require a doc update

thx, so we are ready for merge :-)

**Pull request merged**
