### PR TITLE
add new system property $now-unixtimestamp

### PR DESCRIPTION
**Pull request by rgerhards**
Among others, this may be used as a monotonic counter
for doing load-balancing and other things.

Thanks to Nicholas Brown for suggesting this feature.

### CODE REVIEW

**Comment by nickbroon** [comment]
This is fantastic, thanks @rgerhards !

Just to link to the original email discussion: http://rsyslog-users.1305293.n2.nabble.com/timegenerated-utc-or-high-precision-now-utc-td7596138.html

**Comment by nickbroon** [comment]
Just to check; will this property be available outside of templates as well? So that it can used as part of arithmetic expression, in the same way the that 'parse_time($timegenerated)', as I see in the code change that it's returned as a string not an integer.

That is; could $now-unixtimestamp replace parse_time($timegenerated) in the below?

```
# Get Unix timestamp of current message
set $.tnow = parse_time($timegenerated);

# Rate limit info to 5 every 60 seconds
if ($!severity == 6 and $!facility == 17) then {
  if (($.tnow - $/trate) > 60) then {
    # 5 seconds window expired, allow more messages
    set $/trate = $.tnow;
    set $/ratecount = 0;
  }
  if ($/ratecount > 5) then {
    # discard message
    stop
  } else {
    set $/ratecount = $/ratecount + 1;
  }
}
```

**Comment by rgerhards** [comment]
@nickbroon yes -- I have just amended the test case to cover this scenario as well. Thx for pointing this out. Is it OK if I use your sample inside the doc as a use case?

**Comment by nickbroon** [comment]
Thanks for confirming @rgerhards 
You are welcome to use the above snippet as an example in the docs.

**Comment by nickbroon** [comment]
Fab, thanks @rgerhards :-)

**Pull request merged**
