### PR TITLE
omelasticsearch - add support for CA cert, client cert auth

### PR DESCRIPTION
**Pull request by richm**
This allows omelasticsearch to perform client cert based authentication
to Elasticsearch.
Add the following parameters:
`tls.cacert` - Full path and filename of the file containing the CA cert
               for the CA that issued the Elasticsearch server(s) cert(s)
`tls.mycert` - Full path and filename of the file containing the client
               cert used to authenticate to Elasticsearch
`tls.myprivkey` - Full path and filename of the file containing the client
                  key used to authenticate to Elasticsearch

### CODE REVIEW

**Comment by richm** [comment]
docs: https://github.com/rsyslog/rsyslog-doc/pull/613

**Comment by richm** [comment]
@portante

**Comment by richm** [comment]
rsyslog fedora26x64 rsyslog test failed - valgrind?  I don't see how this is related to my PR?

**Comment by rgerhards** [comment]
@richm sorry for the silence, deep inside complex refactoring. The valgrind test caught indeed something unrelated - a test instability :-( I have re-initiated the test run and will baby-sit it. If a real problem comes up, I'll let you know.

**Comment by rgerhards** [comment]
I have analyzed the Fedora CI issue, and it is a testbench bug.  I am working on it. That said, I feel now well to finally merge. Thanks again for the PRs!

**Pull request merged**
