### PR TITLE
replaced gethostbyname() with getaddrinfo() call

### PR DESCRIPTION
**Pull request by jvymazal**
Gethostbyname() is generally considered obsolete, is not reentrant and cannot really work with IPv6. This is only place in rsyslog where this call remained.

### CODE REVIEW

**Comment by rgerhards** [comment]
I would suggest to squash the commits as they seem to only correct the first one. A rebase would make the solaris tests pass (if they don't hurt compilation there).

**Comment by rgerhards** [comment]
something seem to have gone wrong with the merge... Even though it was no rebase, it should not see the commits as separate. Did you rewrite history on the merged commits?

**Comment by rgerhards** [comment]
In other words: which is the commit that you would like to have applied? I'll cherry-pick it and create a new PR for it...

**Comment by jvymazal** [comment]
I tried not to rewrite history, and I agree that something seems off with the merge, the commit is here: https://github.com/jvymazal/rsyslog/commit/9b8f9476466d00a1ed8296c680ea4dd209766d0f

**Comment by rgerhards** [comment]
replaced by #1518

**Pull request closed without merging**
