### PR TITLE
mmkubernetes - support for metadata cache expiration

### PR DESCRIPTION
**Pull request by richm**
New parameters for mmkubernetes (module and action):

* `cacheexpireinterval`
If `cacheexpireinterval` is -1, then do not check for cache expiration.
If `cacheexpireinterval` is 0, then check for cache expiration.
If `cacheexpireinterval` is greater than 0, check for cache expiration
if the last time we checked was more than this many seconds ago.

* `cacheentryttl` - maximum age in seconds for cache entries

New statistics counters:

* `podcachenumentries` - the number of entries in the pod metadata cache.
* `namespacecachenumentries` - the number of entries in the namespace
  metadata cache.
* `podcachehits` - the number of times a requested entry was found in the
  pod metadata cache.
* `namespacecachehits` - the number of times a requested entry was found
  in the namespace metadata cache.
* `podcachemisses` - the number of times a requested entry was not found
  in the pod metadata cache, and had to be requested from Kubernetes.
* `namespacecachemisses` - the number of times a requested entry was not
  found in the namespace metadata cache, and had to be requested from
  Kubernetes.

### CODE REVIEW

**Comment by richm** [comment]
@nhosoi

**Comment by richm** [comment]
I think the Codacy/PR Quality Review is listing false positives (among other things, it thinks a JSON file is JavaScript source!)

**Comment by richm** [comment]
not sure what the docker-ubuntu16 failure is

**Comment by rgerhards** [comment]
> not sure what the docker-ubuntu16 failure is

looks like a flake, I have restarted

**Comment by rgerhards** [comment]
> I think the Codacy/PR Quality Review is listing false positives (among other things, it thinks a JSON file is JavaScript source!)

I am unsure - especially the complaint about NULL ptr assignment is usually right and worth fixing. I'll have a look as soon as I find time (just came back after a copule of days being away, so it may take till mid-week).

**Comment by rgerhards** [comment]
@richm can you have a look at https://app.codacy.com/app/rsyslog/rsyslog/pullRequest?prid=3239414 -- this sounds like a valid concern.

**Comment by richm** [comment]
continuous-integration/travis-ci/pr is failing in an unrelated test - can you restart that test?

**Comment by richm** [comment]
another unrelated failure - buildbot/rsyslog docker-ubuntu18-distcheck rsyslog failed in FAIL: msgvar-concurrency.sh

**Comment by richm** [comment]
buildbot/rsyslog docker-centos6 failures also look unrelated

**Comment by rgerhards** [comment]
Looking into flakes now - let you know if s/t needs your attention.

**Comment by rgerhards** [comment]
Side-Note: that caused the "flake" ;) https://github.com/rsyslog/rsyslog/pull/3582

**Comment by rgerhards** [comment]
I made a mistake in the race hardening, so it occurred ;) https://github.com/rsyslog/rsyslog/pull/3582 just now hopefully it's the final fix.

**Pull request merged**
