### PR TITLE
Fix crash when using property parameter controlcharacters="escape"

### PR DESCRIPTION
**Pull request by hakman**
This is a fix for [issue 367](https://github.com/rsyslog/rsyslog/issues/367).

### CODE REVIEW

**Comment by rgerhards** [comment]
quick question: we are moving rsyslog towards ASL 2.0, but msg.c is still under GPL. Could you license your **patch** under ASL 2.0?

**Comment by hakman** [comment]
I am ok with ASL 2.0 for the patch. Should I do anything special to the patch for this to happen?

**Comment by rgerhards** [comment]
no, thx. It's recorded here in the issue tracker, that's good enough

**Comment by rgerhards** [comment]
merged into master-candidate, will migrate from there into master

**Pull request merged**
