### PR TITLE
Trivialfixes

### PR DESCRIPTION
**Pull request by davidelang**
fix may be uninitialized warning after checking that all codepaths do properly initialize the variables

fixed missing const on variable declarations

### CODE REVIEW

**Comment by rgerhards** [comment]
before I merge, let me first check why these did not come up on the testbench. I think I have changed it to require warning-free build. Also, we need to re-set the pragmas after the affected code. Finally, I know from the work that I have done in this regard that older gcc (Ubuntu 12.04 IIRC) doesn't like this inside functions. Just FYI!

**Comment by rgerhards** [comment]
Ah, the travis integration I mentioned is not yet completed. I am working on it on this here:

https://github.com/rgerhards/rsyslog/pull/22

Note: it's not a real PR, but rather a tracker for me to find it in travis.

**Comment by rgerhards** [comment]
@davidelang I have undone some of the #pragmas, because at least on the testbench it now compiles warning free. Please let me know if you still see warnings in your build. Then we need to find out why the testbench does not come up with them. I expect that this evening everything is included in master branch.

**Comment by davidelang** [comment]
pmciscoios.c: In function 'parse2':
pmciscoios.c:266:17: warning: 'iHostname' may be used uninitialized in this 
function [-Wmay
be-uninitialized]
    MsgSetHOSTNAME(pMsg, bufParseHOSTNAME, iHostname);
                  ^



mmutf8fix.c: In function 'doAction':
mmutf8fix.c:229:6: warning: 'strtIdx' may be used uninitialized in this function 
[-Wmaybe-u
ninitialized]
   int strtIdx, endIdx;
       ^
mmutf8fix.c:216:20: warning: 'seqLen' may be used uninitialized in this function 
[-Wmaybe-u
ninitialized]
   *endIdx = strtIdx + seqLen;
                     ^
mmutf8fix.c:227:9: note: 'seqLen' was declared here
   int8_t seqLen, bytesLeft = 0;
          ^


There were also these that I did not try to address

lookup.c: In function 'lookupBuildTable':
lookup.c:138:2: warning: 'json_object_object_get' is deprecated (declared at 
/usr/include/libfastjson/json_object.h:350) [-Wdeprecated-declarations]
   jtab = json_object_object_get(jroot, "table");
   ^
lookup.c:145:3: warning: 'json_object_object_get' is deprecated (declared at 
/usr/include/libfastjson/json_object.h:350) [-Wdeprecated-declarations]
    jindex = json_object_object_get(jrow, "index");
    ^
lookup.c:146:3: warning: 'json_object_object_get' is deprecated (declared at 
/usr/include/libfastjson/json_object.h:350) [-Wdeprecated-declarations]
    jvalue = json_object_object_get(jrow, "value");

**Comment by rgerhards** [comment]
This is gcc, right? What CFLAGS do you use? I wonder why I don't get these types of warnings inside the testbench. There is a probably closely related issue, where I get some under clang static analyzer while I don't get them without.

You are right with lookup.c: these will go away when either a) libfastjson is used (upcoming version, not current one) or b) when janmeya's full implementation is merged (guess so). So I didn't address them either.

**Pull request merged**
