### PR TITLE
Improving nsd ossl logs for better debugging

### PR DESCRIPTION
**Pull request by Dinesh-Ramakrishnan**
Currently the nsd_ossl module doesn't contains logs for few failure scenarios.  This commit adds those additional logs.
Also we have added the nsd_ossl tag to the logs for better identification

### CODE REVIEW

**Review by alorbach — APPROVED** [review]
This looks fine to me, very useful addition to openssl error / info output.

**Comment by rgerhards** [comment]
@Dinesh-Ramakrishnan thx for the PR. Regarding the CI fail, I suspect you need to check openssl version number and downgrade reporting if needed

**Comment by alorbach** [comment]
@Dinesh-Ramakrishnan 
For older OpenSSL Versions, there needs to be a check because SSL_get_shared_curve  is available since OpenSSL 1.0.2 and the build is failing now on Centos6. 

You can use this: 
#if OPENSSL_VERSION_NUMBER >= 0x10002000L
#endif

**Comment by rgerhards** [comment]
@Dinesh-Ramakrishnan pls also use Tabs for indention, that's the style we use inside rsyslog

**Comment by Dinesh-Ramakrishnan** [comment]
Thank you very much for the comments.  I will address the same and update this pr

**Comment by Anusha-Pai95** [comment]
@rgerhards Rainer Gerhards , Thank you so much for your comments. I have addressed all your comments regarding indentation and version compatibility of the api. But I see there is commit squash issue. we may need to merge all the 6 commits as a single commit. I see that code inspect failure. If possible can that be taken care by the infra or it should be explicitly taker care?

**Comment by rgerhards** [comment]
@Dinesh-Ramakrishnan thx for your persistence! I would appreciate if you could squash, but I can also do this for you. In any case, it would make sense to re-word the commit text to what the commit actually does. Much like description here in github issue. Remember: github may go away in the future, but your commit log won't. So the only real thing is the commit text.

**Comment by Anusha-Pai95** [comment]
@rgerhards , We have squashed all the commits and all the checks are passed now. Are we good to merge this pull request to the upstream?

**Review by rgerhards — APPROVED** [review]
LGTM

**Comment by rgerhards** [comment]
> We have squashed all the commits and all the checks are passed now. Are we good to merge this pull request to the upstream?

I think so, but let's give @alorbach a final chance to have a look

**Comment by alorbach** [comment]
Looks good (Y) can go for merge ;)

**Pull request merged**
