### PR TITLE
testbench: fixed imfile parallel issues

### PR DESCRIPTION
**Pull request by alorbach**
- Fixed timing issues in some imfile wildcard/regex tests
- Added touch command in imfile wildcard tests to make sure directories exist before files are created in it if IO is under stress. 
- changed content checking in some tests to use "content_check_with_count" with check timeouts instead of using fixed sleeptimes.

### CODE REVIEW

**Comment by rgerhards** [comment]
please do a rebase, I added a new imfile test; may be worth looking at it

**Comment by alorbach** [comment]
thats the content check with sort I added in imfile-wildcards.sh test... will look into this tomorrow.

**Comment by alorbach** [comment]
The sort command creates different results onsome plattforms. I guess we need to skip the content check in imfile-wildcards.sh

**Comment by rgerhards** [comment]
> The sort command creates different results onsome plattforms. I guess we need to skip the content check in imfile-wildcards.sh

what exactly are the differences? Usually, we can work around that.

**Comment by alorbach** [comment]
Sort on ubuntu 16: 
`HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.10.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.11.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.1.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.2.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.3.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.4.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.5.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.6.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.7.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.8.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./'$RSYSLOG_DYNNAME'.input.9.log, fileoffset: 0
HEADER msgnum:00000001:, filename: ./'$RSYSLOG_DYNNAME'.input.11.log, fileoffset: 17
HEADER msgnum:00000002:, filename: ./'$RSYSLOG_DYNNAME'.input.11.log, fileoffset: 34`

Sort on Ubuntu 18 arm: 
`HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.1.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.10.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.11.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.2.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.3.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.4.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.5.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.6.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.7.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.8.log, fileoffset: 0
HEADER msgnum:00000000:, filename: ./rstb_709934_b2adf52a.input.9.log, fileoffset: 0
HEADER msgnum:00000001:, filename: ./rstb_709934_b2adf52a.input.11.log, fileoffset: 17
HEADER msgnum:00000002:, filename: ./rstb_709934_b2adf52a.input.11.log, fileoffset: 34`

**Comment by davidelang** [comment]
besides the failed variable substatution, this looks like the difference between 
an alpha and numberic sort, there should be an option to force either rather 
than taking the default.

David Lang

**Comment by alorbach** [comment]
Indeed. Anyway, we changed the way filenumbers are generated to workarround that issue.. lets see how the tests run through now.

**Pull request merged**
