### PR TITLE
Add tests for variable name comparison regressions

### LINKED ISSUE #617: Local variable comparisons do not work
This does not appear to work on v8.14.0:
```
set $.foo = "foo";
set $.bar = "foo";
if ($.foo == $.bar) then {
    *.* /var/log/rsyslog-debug.log;RSYSLOG_DebugFormat
}
```

### PR DESCRIPTION
**Pull request by portante**
Don't change the first character of the variable name, since we need
that depending on its name space. Instead, determine the proper root
variable string that should be used.

Fixes #617.

### CODE REVIEW

**Comment by portante** [comment]
I'll update with a unit test shortly.

**Comment by portante** [comment]
Okay, I have posted a number of tests ahead of an actual fix.

The first patch, "Enable rscript comparison tests", `48321f9`, just adds a few existing comparison tests as a base line.  The second patch, "Tests to verify string variable comparisons", `92f4f08`, adds explicit and exhaustive testing of json, local, and global variables.

The third test fails, which is trying to mirror what is reported in #617.  But I still have not figured out why it fails.

**Comment by rgerhards** [comment]
moving to 8.16, as the releated changes also don't make it into 8.15.

**Comment by portante** [comment]
I updated the title as this PR has morphed from originally trying to fix a problem to just enabling a set of tests to help catch regressions in variable name comparisons.

**Pull request merged**
