### PR TITLE
omhttp: Fix dynrestpath param in batch mode

### PR DESCRIPTION
**Pull request by alorbach**
Modified omhttp: Fix dynrestpath param in batch mode

When batchmode was used, the templates could not be used to    
expand dynrestpath. We are now storing the restpath param 
within the batch data if we are in batch mode.

- testbench: Added tests for omhttp dynrestpath param
  Testing setting the restpath by template - one with batch mode
  and one without batch mode

closes: https://github.com/rsyslog/rsyslog/issues/4567

### CODE REVIEW

**Comment by gintrator** [comment]
@alorbach Note that will lead to unexpected results if the dynamic path is based on a message attribute that is inconsistent among messages in the same batch.

To correctly do dynamic paths with batching, we'll need to "key" batches internally by the dynamic path and only post the messages that map to the same key to that path. 

Otherwise, everything in a batch will get posted to whatever the last message's dynamic path evaluated to, which is pretty similar to a static path configured for the whole action. In theory, every message in a batch could resolve to a different dynamic path.

**Comment by rgerhards** [comment]
At least for a quick fix, we could (and probably should for a first try) check if the dynpath changes and, if so, terminate the previous batch at this point, commit, start a new one and continue as described.

**Comment by alorbach** [comment]
I see what you mean. At the moment how the action is build, it is simple not possible to have unique dynrestpathes for each message in the batch. It would require some more rework on that action in order to split the batch and submit the messages based on the dynrestpath as key.

I think the approach from @rgerhards can be done within this PR and would be possible to implement quickly.

**Comment by rgerhards** [comment]
I would strongly opt to have it fixed quickly, even though this can cause performance issues (that's the same as in other spots). Of course, we should add a warning to the doc. If we see complaints, we can look at a better method.

**Comment by alorbach** [comment]
@gintrator I changed the PR as recommended by Rainer - the batch will be finalized and restarted once the dynpath changes. Can you confirm that this solution is working for you?

**Comment by gintrator** [comment]
Looks like it produces correct behavior, good by me!

**Pull request merged**
