### PR TITLE
Update pmsnare: allow different tab escapes

### PR DESCRIPTION
**Pull request by shane-lawrence**
When `escapecontrolcharacters="off"`, if an incoming Snare event's fields are only separated by tabs, pmsnare will mangle the message because an actual tab character is smaller than `"#011"`.

Sample message:
```
<14>May 17 02:25:10 SL-Win2008R2DC.lab.home MSWinEventLog	1	Security	606129	Wed May 17 02:25:10 2017	4634	Microsoft-Windows-Security-Auditing	N/A	N/A Success Audit	SL-Win2008R2DC.lab.home Logoff	An account was logged off.	Subject:	Security ID:	S-1-5-21-1004336348-1177238915-682003330-512	Account Name:	SL-WIN2008R2IIS$	Account Domain:	LAB	Logon ID:	0x9648a78	Logon Type:	3	This event is generated when a logon session is destroyed. It may be positively correlated with a logon event using the Logon ID value. Logon IDs are only unique between reboots on the same computer. 984658
```

Resultant message without the fix:
```
FROMHOST: 'localhost', fromhost-ip: '::1', HOSTNAME: 'SL-Win2008R2DC.lab.home', PRI: 14,
syslogtag 'MSWinEventLog', programname: 'MSWinEventLog', APP-NAME: 'MSWinEventLog', PROCID: '-', MSGID: '-',
TIMESTAMP: 'May 17 02:25:10', STRUCTURED-DATA: '-',
msg: ' ecurity	606129	Wed May 17 02:25:10 2017	4634	Microsoft-Windows-Security-Auditing	N/A	N/A Success Audit	SL-Win2008R2DC.lab.home Logoff	An account was logged off.	Subject:	Security ID:	S-1-5-21-1004336348-1177238915-682003330-512	Account Name:	SL-WIN2008R2IIS$	Account Domain:	LAB	Logon ID:	0x9648a78	Logon Type:	3	This event is generated when a logon session is destroyed. It may be positively correlated with a logon event using the Logon ID value. Logon IDs are only unique between reboots on the same computer. 984658'
escaped msg: ' ecurity606129Wed May 17 02:25:10 20174634Microsoft-Windows-Security-AuditingN/AN/A Success AuditSL-Win2008R2DC.lab.home LogoffAn account was logged off.Subject:Security ID:S-1-5-21-1004336348-1177238915-682003330-512Account Name:SL-WIN2008R2IIS$Account Domain:labLogon ID:0x9648a78Logon Type:3This event is generated when a logon session is destroyed. It may be positively correlated with a logon event using the Logon ID value. Logon IDs are only unique between reboots on the same computer. 984658'
inputname: imptcp rawmsg: '<14>May 17 02:25:10 SL-Win2008R2DC.lab.home MSWinEventLog ecurity	606129	Wed May 17 02:25:10 2017	4634	Microsoft-Windows-Security-Auditing	N/A	N/A Success Audit	SL-Win2008R2DC.lab.home Logoff	An account was logged off.	Subject:	Security ID:	S-1-5-21-1004336348-1177238915-682003330-512	Account Name:	SL-WIN2008R2IIS$	Account Domain:	LAB	Logon ID:	0x9648a78	Logon Type:	3	This event is generated when a logon session is destroyed. It may be positively correlated with a logon event using the Logon ID value. Logon IDs are only unique between reboots on the same computer. 984658'
```
This change allows tabs to be escaped according to the default settings (#011), a custom prefix (?011), C-style (\t), or not at all (    ). It does not affect other modules, as this is the only module that specifically depends on how tabs are escaped. 

Normally, the global settings from the config file will be used to determine how tabs are represented. Support for the new version of the config system has been added, and it's possible to override the global settings for a specific instance of a parser when loading it. This may be useful if, for example, the module receives Snare messages relayed from another rsyslog which has different escape settings.

Many test cases have been added to verify that the module is working correctly.

### CODE REVIEW

**Comment by shane-lawrence** [comment]
Travis worked on my fork, but failed on the PR when testing omprog-cleanup-vg.sh. I didn't make any changes to the failing module at all. All of the other build tests passed, so I'm sure this is a fluke. I can't trigger a Travis rebuild, but if you want I can close and re-open the PR to get a clean test.

**Comment by shane-lawrence** [comment]
Travis looks good now. Please let me know if any changes are required.

**Comment by rgerhards** [comment]
Just FYI: you actually always can trigger a Travis run. You just need to

git commit --ammend

Your head commit without changes and push -f.

I have Connectivity problems at the moment, looks like a bigger problem for
the Telco provide. I am working via backup and will look in more depth when
everything is working normally again.

Rainer

Sent from phone, thus brief.

Am 05.06.2017 19:58 schrieb "Shane P. Lawrence" <notifications@github.com>:

**Comment by shane-lawrence** [comment]
Good to know, I'll keep that in mind for next time. Thank you!

**Pull request merged**
