### PR TITLE
Drop messages that were rejected due to 'RD_KAFKA_RESP_ERR_MSG_SIZE_T…

### PR DESCRIPTION
**Pull request by n2yen**
…OO_LARGE' error.

### CODE REVIEW

**Comment by n2yen** [comment]
Ran into an issue where kafka processing rates would drop significantly. The idea is to avoid continually resubmit messages that are too large, such as per kafka configuration, "message.max.bytes".

**Comment by rgerhards** [comment]
sounds like a good idea! would you mind updating the doc as well?

**Comment by n2yen** [comment]
Will do!

**Comment by fivesheep** [comment]
Actually, it's more than just this error. in kafka, there's a concept called retriable exceptions and a handful non-retriable exceptions which msg too large is one of them. It's better to include all the non-retriable ones if possible

**Comment by n2yen** [comment]
hi @fivesheep @rgerhards, 
Would you be opening a separate PR to handle all non-retry-able exceptions? 
We would need to carefully identify them from all the possible rd kafka error returns...

**Comment by rgerhards** [comment]
@n2yen 

> Would you be open to having a separate PR to handle all non-retry-able exceptions?
> We would need to carefully identify them from all the possible rd kafka error returns...

sorry I overlooked this. For sure I appreciate all PRs that help improve the state of rsyslog and it's modules!

**Pull request merged**
