### PR TITLE
Remove leading whitespace in front of CPP directives

### PR DESCRIPTION
**Pull request by portante**
Seems like the leading whitespace is not a real problem, but noticed it reviewing another patch and thought I'd submit the cleanup for consideration.

### CODE REVIEW

**Comment by rgerhards** [comment]
More out of curiosity: Is this a requirement? I tend to indent the hash together with the rest as I think this is more readable (and I know it's not done consistently).

**Comment by portante** [comment]
I don't think this is a requirement, see https://gcc.gnu.org/onlinedocs/gcc-2.95.3/cpp_1.html#SEC3.  So if you don't feel this is work taking in, we can just drop this.

**Comment by rgerhards** [comment]
After thinking over it, I think we should drop it. C90 and C99 support either style. To me, the code looks more readable with the hash NOT at the start of the line. Does this sound reasonable to you?

**Comment by portante** [comment]
No problem by me, thanks.

**Pull request closed without merging**
