### PR TITLE
Update rscryutil.c

### PR DESCRIPTION
**Pull request by wizard1024**
Added opportunity to decrypt not closed log file (without appropriate record END: xxx in <name>.encinfo file)

### CODE REVIEW

**Comment by alorbach** [comment]
I get this error when trying to make rscryutil: 
--
rscryutil.c: In function ‘doDecrypt’:
rscryutil.c:290:25: error: label ‘end’ used but not defined
                         goto end;
--
There is no end lable, perhaps it should be goto done; ?

**Comment by wizard1024** [comment]
Thanks. Updated.

**Comment by alorbach** [comment]
Have you tested the patch? 

I have tried it using my sample config, and rscryutil isn't able to decrypt until rsyslog is closed. 
At least in my configuration.

**Comment by wizard1024** [comment]
Yes. Tested on Centos. rsyslogd installed from repo. Typical usage:
http://pastebin.com/tL2UiuYB
Usage of ./rscryutil - usage of modified tool.

**Comment by alorbach** [comment]
Nevermind, was my bad. I was accidentally testing with the installed rscryutil, not the compiled one in my git directory. Works fine, I will merge the patch soon.

**Pull request merged**
