### PR TITLE
Enhanced symlink rotation support

### PR DESCRIPTION
**Pull request by jvymazal**
Now watching target directory as well to properly catch rotation
of files monitored via symlink.

Also fixed a bug in file move handling, previously state file could be deleted when `node` had more than one `edge`.

### CODE REVIEW

**Comment by jvymazal** [comment]
@rgerhards this is sort of follow-up to #2749 , found few other use-cases where original implementation still was not enough + found the rename bug in the process. The only CI fail is DA-queues which seems like a flake.

**Comment by rgerhards** [comment]
will merge after https://github.com/rsyslog/rsyslog/pull/2927 as I'd like to get coverity clean again.

**Comment by rgerhards** [comment]
Thankfully it my trick to "solve" the coverity false positive worked out ;-) So I feel now even better merging this one here. Thx again!

**Comment by rgerhards** [comment]
@jvymazal I already added this to the ChangeLog w/ previous merge:
```
- bugfix imfile: files which were loaded via symlink were not always followed
  They were stopped watching after being rotated.
```

I think this is sufficient. Or do I need to add some more info?

**Comment by jvymazal** [comment]
@rgerhards yes, I think we can leave it at that. For user it has enough information.

**Comment by rgerhards** [comment]
thx!

**Pull request merged**
