### PR TITLE
new mmgrok plugin

### PR DESCRIPTION
**Pull request by chenryn**
usecase metioned in https://github.com/rsyslog/liblognorm/issues/154

### CODE REVIEW

**Comment by rgerhards** [comment]
It looks like there is a file missing in that commit.

**Comment by chenryn** [comment]
leave `plugins/mmgrok` in Makefile.am, but all files rename to contrib/mmgrok. correct now.

**Comment by portante** [comment]
+1 I hope to try this next week.

**Comment by rgerhards** [comment]
merged into master-candidate, will move from there to master

**Pull request merged**
