### PR TITLE
Add mechanism to include extra CA files parameter

### LINKED ISSUE #4851: Encrypted messages are not delivered using the ossl driver and chained certificates
### Expected behavior
Encrypted messages are delivered via the ```ossl``` network stream driver using chained certificates.

### Actual behavior
Encrypted messages are **not** delivered via the ```ossl``` network stream driver using chained certificates.

### Steps to reproduce the behavior
Configure rsyslog in the following manner and try to send a message to the server side. I attached debug files from both instances as well. Seems like verification of chained certificates fails if the ossl driver is used. If I replace ossl with the gtls driver on both server and client sides, then everything works as expected.

Server config:
```
global(
    DefaultNetstreamDriverCAFile="/etc/rsyslog.d/ca-cert.pem"
    DefaultNetstreamDriverCertFile="/etc/rsyslog.d/server-cert.pem"
    DefaultNetstreamDriverKeyFile="/etc/rsyslog.d/server-key.pem"
)

module(
    load="imtcp"
    StreamDriver.AuthMode="x509/name"
    PermittedPeer="ci-vm-10-0-138-191.hosted.upshift.rdu2.redhat.com"
    StreamDriver.Mode="1"
    StreamDriver.Name="ossl"
)
input(type="imtcp" Port="6514")
```
</details>

Client config:
```
global(
    DefaultNetstreamDriverCAFile="/etc/rsyslog.d/ca-cert.pem"
    DefaultNetstreamDriverCertFile="/etc/rsyslog.d/client-cert.pem"
    DefaultNetstreamDriverKeyFile="/etc/rsyslog.d/client-key.pem"
)
local6.info action(type="omfwd"
    Protocol="tcp"
    Target="10.0.139.103"
    Port="6514"
    StreamDriver="ossl"
    StreamDriverMode="1"
    RebindInterval="50"
    StreamDriverAuthMode="x509/name"
    StreamDriverPermittedPeers="ci-vm-10-0-139-103.hosted.upshift.rdu2.redhat.com")
```

### Additional info
The problem seems to be in the ossl driver, because the ```gtls``` option works with the mentioned config and certificates.

<details>
<summary>Certificate creation(server)</summary>

```
pushd /etc/rsyslog.d
cat > ca-root.tmpl <<EOF
organization = "Organization"
unit = "GSS"
locality = "Locality"
state = "State"
country = CZ
cn = "rootca"
serial = 001
expiration_days = 365
dns_name = "$(hostname)"
ip_address = "127.0.0.1"
email = "root@$(hostname)"
crl_dist_points = "http://127.0.0.1/getcrl/"
ca
cert_signing_key
crl_signing_key
EOF

certtool --generate-privkey --outfile ca-root-key.pem
certtool --generate-self-signed --load-privkey ca-root-key.pem --template ca-root.tmpl --outfile ca-root-cert.pem

cat > ca.tmpl <<EOF
organization = "Organization"
unit = "GSS"
locality = "Locality"
state = "State"
country = CZ
cn = "ca"
serial = 002
expiration_days = 365
dns_name = "$(hostname)"
ip_address = "127.0.0.1"
email = "root@$(hostname)"
crl_dist_points = "http://127.0.0.1/getcrl/"
ca
cert_signing_key
crl_signing_key
EOF

certtool --generate-privkey --outfile ca-key.pem
certtool --generate-request --template ca.tmpl --load-privkey ca-key.pem --outfile ca-request.pem
certtool --generate-certificate --template ca.tmpl --load-request ca-request.pem  --outfile ca-cert.pem --load-ca-certificate ca-root-cert.pem --load-ca-privkey ca-root-key.pem

cat > ca2.tmpl <<EOF
organization = "Organization"
unit = "GSS"
locality = "Locality"
state = "State"
country = CZ
cn = "ca2"
serial = 003
expiration_days = 365
dns_name = "$(hostname)"
ip_address = "127.0.0.1"
email = "root@$(hostname)"
crl_dist_points = "http://127.0.0.1/getcrl/"
ca
cert_signing_key
crl_signing_key
EOF

certtool --generate-privkey --outfile ca2-key.pem
certtool --generate-request --template ca2.tmpl --load-privkey ca2-key.pem --outfile ca2-request.pem
certtool --generate-certificate --template ca2.tmpl --load-request ca2-request.pem  --outfile ca2-cert.pem --load-ca-certificate ca-cert.pem --load-ca-privkey ca-key.pem

cat > server.tmpl <<EOF
organization = "Organization"
unit = "GSS"
locality = "Locality"
state = "State"
country = CZ
cn = "server"
serial = 004
expiration_days = 365
dns_name = "$(hostname)"
ip_address = "127.0.0.1"
email = "root@$(hostname)
tls_www_server
EOF

certtool --generate-privkey --outfile server-key.pem --bits 2048
certtool --generate-request --template server.tmpl --load-privkey server-key.pem --outfile server-request.pem
certtool --generate-certificate --template server.tmpl --load-request server-request.pem  --outfile server-cert.pem --load-ca-certificate ca2-cert.pem --load-ca-privkey ca2-key.pem

cat server-cert.pem ca2-cert.pem ca-cert.pem > server-cert-tmp.pem
mv server-cert-tmp.pem server-cert.pem

```
</details>

<details>
<summary>Certificate creation(client)</summary>

```
pushd /etc/rsyslog.d
cat > client.tmpl <<EOF
organization = "Organization"
unit = "GSS"
locality = "Locality"
state = "State"
country = CZ
cn = "client"
serial = 004
expiration_days = 365
dns_name = "$(hostname)"
ip_address = "127.0.0.1"
email = "root@$(hostname)"
tls_www_client
EOF

certtool --generate-privkey --outfile client-key.pem --bits 2048
certtool --generate-request --template client.tmpl --load-privkey client-key.pem --outfile client-request.pem
certtool --generate-certificate --template client.tmpl --load-request client-request.pem  --outfile client-cert.pem --load-ca-certificate ca2-cert.pem --load-ca-privkey ca2-key.pem
cat client-cert.pem ca2-cert.pem > client-cert-tmp.pem
mv client-cert-tmp.pem client-cert.pem
```
</details>

Rsyslog server debug:
[rsyslog-server.debug.log](https://github.com/rsyslog/rsyslog/files/8500307/rsyslog-server.debug.log)

Rsyslog client debug:
[rsyslog-client.debug.log](https://github.com/rsyslog/rsyslog/files/8500308/rsyslog-client.debug.log)

Feel free to request more information. I can even provide the certificates(if needed) as these are used only in my testing lab.

### Environment
rsyslogd  8.2202.0-1.el8 (aka 2021.12) compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

### PR DESCRIPTION
**Pull request by sarroutbi**
This change allows to include additional CA files
so that no "unable to get issuer certificates" issue
is obtained when using chained cert files.
Proposed new parameter name is "NetstreamDriverCAExtraFiles"

fixes #4851

Documentation change:
https://github.com/rsyslog/rsyslog-doc/pull/974

Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

### CODE REVIEW

**Comment by sarroutbi** [comment]
Hello @rgerhards . Sorry for my ignorance, but I see in previous post a milestone was added for this change .. sorry but, what does it mean? It will be added "AS IS", it will be reviewed in that milestone, ... ?

Thank you very much

**Comment by rgerhards** [comment]
I want to merge it by that milestone, but I would @alorbach to review it before. Unfortunately he had no time for the last milestone and is currently out of office.

**Review by alorbach — APPROVED** [review]
To my understanding "SSL_CTX_load_verify_locations" can be called multipler times then. Do you have any hint in the OpenSSL documentation describing this behavior? 

Also can you add to the documentation, that this feature will only work for the OpenSSL driver (The GNUtls driver also uses these global variables).

**Comment by sarroutbi** [comment]
Hello @alorbach . Thanks for your revision.

> To my understanding "SSL_CTX_load_verify_locations" can be called multipler times then. Do you have any hint in the OpenSSL documentation describing this behavior?
> 
I didn't find any explicit instruction where this is used. However, for certain chain certificate scenarios, I observed "s_client" application was used with multiple calls to option "-CAfile". After having a look at the code, I realized this result on multiple calls to SSL_CTX_load_verify_locations

> Also can you add to the documentation, that this feature will only work for the OpenSSL driver (The GNUtls driver also uses these global variables).

Sure. I added extra information to documentation change to clarify it.

**Comment by alorbach** [comment]
> Hello @alorbach . Thanks for your review.
> 
> > To my understanding "SSL_CTX_load_verify_locations" can be called multipler times then. Do you have any hint in the OpenSSL documentation describing this behavior?
> 
> I didn't find any explicit instruction where this is used. However, for certain chain certificate scenarios, I observed "s_client" application was used with multiple calls to option "-CAfile". After having a look at the code, I realized this result on multiple calls to SSL_CTX_load_verify_locations

Thanks if it is being used that way in official openssl tools, the behavior should be expected and valid. I like to make sure that the behavior is documented and doesn't suddenly disappear in future versions.

**Pull request merged**
