### PR TITLE
Remove bad use of inotify_event structure

### PR DESCRIPTION
**Pull request by portante**
Fixes # 718.

We also clean up whitespace in a separate commit so that `git diff --check` is helpful in the future.

### CODE REVIEW

**Comment by portante** [comment]
@Dieken, because the entire call is now under the Debug flag, so there is no need to use the macro which does the same.

**Comment by rgerhards** [comment]
@portante sorry for possible post-vacation blureness: I fail to see how this fixes #718 As far as I see, the "mocked-up" ev only is used for display purposes. Could you point me bluntly to the point? ;)

Note that I am not saying the new method is better - it *is*. But I want to make sure #718 is actually fixed.

On the file display function: that was originally meant to be a temporary debug aid. I will remove it with https://github.com/rsyslog/rsyslog/commit/f4e9da0e6231e618104851c17f68b9f0ccb4e9d4. I know this will cause merge conflicts, but I'll solve them manually, so nothing you need to bother about.

**Comment by ymattw** [comment]
Well.. See the first comment under #718, the original contributor wrote
very detailed information in his commit log.

**Comment by zacharyzhao** [comment]
`evFileHelper.name` is not allocated and not used at all, in typical
case its address is the same as the local variable `etry` in the same
stack (compiler optimization), assigning to `evFileHelper.name[0]`
actually corrupts the etry data structure and crashes the program.

Here's an example output from gdb session.

```
(gdb) p &evFileHelper.name
$6 = (char (*)[]) 0x7ffff6dfc930
(gdb) p &etry
$7 = (wd_map_t **) 0x7ffff6dfc930
(gdb)
```

See clearly in my commit: 9213531

**Comment by rgerhards** [comment]
@zacharyzhao ah, now I see it - I hadn't looked at #719 at all, because that was already closed (abandoned IMO). But now I am a bit confused on given proper credits: looking at #718, #719 and #720 I think it would at least be useful to give credit to @zacharyzhao and @portante . Also, could @portante include the helpful commit text from #719 into his commit? I think that would be useful in the future.

**Comment by portante** [comment]
I hope @zacharyzhao gets the attribution.  I just quickly saw a small step of clean up.  I'll update the commit comment with the initial text from #719 referencing @zacharyzhao.

**Comment by ymattw** [comment]
I would suggest to merge #719 first because that's a minimal fix.  IMHO if you want to clean up useless variable, fix indention problem, or debug logging, better to do that in a separate pull request.

**Comment by portante** [comment]
@ymattw the simple fix does not appear to be right, as the `len` field is still set to a value that does not represent that allocated length of that structure.  I believe removing the variable entirely is the best path forward to eliminate confusion.

**Comment by rgerhards** [comment]
@portante if you like, I can merge things together manually. I'd indeed start with #719 and then merge this one on top. I need to do conflict resolution in any case, so that's probably not much extra work for me. Let me know.

**Comment by portante** [comment]
This is fine by me.  I am not worried about having my name on any patch, but would like to see the confusing piece of this code removed.  Thanks!

**Comment by rgerhards** [comment]
2016-01-14 18:07 GMT+01:00 Peter Portante <notifications@github.com>:

> This is fine by me. I am not worried about having my name on any patch,
>

I never wanted to imply this, sorry if it sounded so. I know that's not the
case!

My main intent was to safe you from doing work that's not strictly
necessary. I'll see that I can do the merge tomorrow (unfortunately quite
busy :-( ).

Thanks for all your help,
Rainer

**Pull request merged**
