### PR TITLE
Avoiding conditional directives that split up parts of statements.

### PR DESCRIPTION
**Pull request by RomeroMalaquias**

### CODE REVIEW

**Comment by portante** [comment]
Can you squash these two commits?

**Comment by rgerhards** [comment]
I admit I don't see an advantage in the new code. If I read it correctly, it introduces a temporary variable for what else could be done without one. The gain in clarity is neglegible from my PoV. Am I overlooking something?

**Comment by RomeroMalaquias** [comment]
@rgerhards, Hi, you're right, the new code introduces a temporary variable to improve code understanding and maintainability. I think that the question here is if the gain is really negligible.

**Comment by RomeroMalaquias** [comment]
@portante Hi, i can create another pull request with a single commit if the change is gonna be approved.

**Comment by rgerhards** [comment]
@protante @janmejay @theinric what's your stance at this? I admit I don't like this change, but am willing to let me convince it should be applied.

**Comment by theinric** [comment]
> Can you squash these two commits?

Agreed; if this is to be merged, they should be squashed.
In general, the commits in the PR should be "tidied up". E.g. no commits fixing your other commits in the PR..

> i can create another pull request with a single commit if the change is gonna be approved.

No need for that, just rebase the PR.

> Have you considered created a macro?

Agreed, this can probably be simplified further.

> In general, the style is to use conditional compilation to avoid doing tempoary things or duplicate code in cases where this is not strictly necessary.

I'd probably prefer a readable code to the most efficient code. Things like redundant temporary variables will most likely be removed by the compiler anyway.

> what's your stance at this?

Personally, I don't find the newer version more readable.

> <...> to improve code understanding and maintainability.

Could you please describe what functional gains are there? Aesthetics are subjective.

**Comment by janmejay** [comment]
I don't find it more readable either.

On Thu, Dec 10, 2015 at 7:43 PM, theinric <notifications@github.com> wrote:

> Can you squash these two commits?
>
> Agreed; if this is to be merged, they should be squashed.
> In general, the commits in the PR should be "tidied up". E.g. no commits
> fixing your other commits in the PR..
>
> i can create another pull request with a single commit if the change is
> gonna be approved.
>
> No need for that, just rebase the PR.
>
> Have you considered created a macro?
>
> Agreed, this can probably be simplified further.
>
> In general, the style is to use conditional compilation to avoid doing
> tempoary things or duplicate code in cases where this is not strictly
> necessary.
>
> I'd probably prefer a readable code to the most efficient code. Things
> like redundant temporary variables will most likely be removed by the
> compiler anyway.
>
> what's your stance at this?
>
> Personally, I don't find the newer version more readable.
>
> <...> to improve code understanding and maintainability.
>
> Could you please describe what functional gains are there? Aesthetics are
> subjective.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/pull/686#issuecomment-163630915>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by RomeroMalaquias** [comment]
@theinric , @janmejay 
There are no functional gains,
This change is only aesthetical, it's a suggestion based on code style guidelines from the Linux Kernel.
[Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)

**Comment by rgerhards** [comment]
finally decided that we keep our style. At least we would otherwise need to audit where else changes would be required.

**Pull request closed without merging**
