### PR TITLE
Add built-in function get_property() to access property vars

### PR DESCRIPTION
**Pull request by n2yen**
Provides ability to evaluate a rsyslog variable using dynamically
evaluated parameters.
  1st param is the rsyslog param, 2nd param is a key, can be an array
  index or key string.

Useful for accessing json sub-objects, where a key
needs to be evaluated at runtime. Can be used to access arrays as well.

see tests for examples

### CODE REVIEW

**Comment by n2yen** [comment]
Hi @rgerhards ,

Added documentation for this PR: https://github.com/rsyslog/rsyslog-doc/pull/915 - can you have a look when you get a chance?

cheers,
Nelson

**Comment by rgerhards** [comment]
sry for the long silence - have rebased to current master (also to get rid of CI issue), see #4571

Feel free to rebase if you like.

**Comment by n2yen** [comment]
sure no problem @rgerhards . I've rebased to current master just in case it's helpful.

**Comment by rgerhards** [comment]
@n2yen thx a lot for your persistance!

**Pull request merged**
