### PR TITLE
add missing dist files; add mmkubernetes to distcheck

### PR DESCRIPTION
**Pull request by richm**
These files were missing from make dist so not available
in source tarball distributions

### CODE REVIEW

**Comment by rgerhards** [comment]
Thx, but ... shouldn't `make distcheck` have detected this? Maybe there is some more issue than just the missing files.

**Comment by richm** [comment]
> Thx, but ... shouldn't `make distcheck` have detected this? Maybe there is some more issue than just the missing files.

Not sure - how do I check this locally?  Can someone verify that adding `--enable-mmkubernetes` to distcheck solves this problem?

**Comment by rgerhards** [comment]
@richm I'll have a look at CI today to see why it is not detected. Keeping this PR open so that I can see the actual issue.

**Comment by rgerhards** [comment]
@richm I see, you have already found and fixed the issue. Plus it brings up a new report - great!

**Comment by rgerhards** [comment]
@richm I think I found the cause of the current failure: https://github.com/rsyslog/rsyslog/pull/3689

I'll merge my PR once CI is done and will then re-init the failed tests here. I'll ping you if new problems occur.

**Pull request merged**
