### PR TITLE
Fix to reloading journal

### PR DESCRIPTION
**Pull request by portante**
WIP: psuedo code for fix to reloading journal after journald rotates its internal journal files.

### CODE REVIEW

**Comment by portante** [comment]
This is a proposed fix for https://github.com/rsyslog/rsyslog/issues/2436.

**Comment by rgerhards** [comment]
@portante Thx for your work. Do you consider it complete or still WiP?

**Comment by portante** [comment]
Yes, still trying to figure out why the cursor sometimes fails to be fetched.  It looks like we have to fetch the cursor before we call get_fd, but not sure yet.

**Comment by rgerhards** [comment]
> Yes, still trying to figure out why the cursor sometimes fails to be fetched. It looks like we have to fetch the cursor before we call get_fd, but not sure yet.

thx! please let me know when you consider it ready for merge. Will flag it as "no not merge" in the meantime.

**Comment by portante** [comment]
@rgerhards, this is ready for review, but realize I have not built and tested this myself yet.

See the conversation at https://github.com/systemd/systemd/issues/7998 for more background.

**Comment by portante** [comment]
FWIW, here is initial work on fixes to the docker journald log driver client: https://github.com/projectatomic/docker/pull/296

**Comment by portante** [comment]
Rather than polling every 1,024 messages calling `sd_journal_process()`, we could create a thread to "listen" to the inotify fd and do that, but it does not seem worth the effort given the intricate details of journal we'd need to know.

**Comment by rgerhards** [comment]
@portante There is a brace ```(``` missing ;-)

**Comment by rgerhards** [comment]
> Rather than polling every 1,024 messages calling sd_journal_process(), we could create a thread to "listen" to the inotify fd and do that, but it does not seem worth the effort given the intricate details of journal we'd need to know.

IMHO we should not go too deep into (non-documented?) journal details if we can avoid it. So I would stick with the current approach and see if any new problems come up with this. @portante do you agree? Do I overlook something?

**Comment by portante** [comment]
I agree @rgerhards.

**Comment by rgerhards** [comment]
@portante ok, so then we need to dig into undocumented journal land... Are you up to this?

**Comment by portante** [comment]
@rgerhards, I'm up for it.  I am hoping the discussion at https://github.com/systemd/systemd/pull/8032 will give us the necessary insight we need to do it correctly.

**Comment by portante** [comment]
Do you consider it worthwhile to take this patch as is, and then we work a follow-on patch for the out-of-band handling of journal file rotation?

**Comment by rgerhards** [comment]
@portante much appreciated, thank you!

**Comment by rgerhards** [comment]
> Do you consider it worthwhile to take this patch as is, and then we work a follow-on patch for the out-of-band handling of journal file rotation?

If I don't get it wrong, I think it **improves** the situation without any new negative effect. As such, I would consider it useful to merge. If you agree, I'll do later today (working on s/t else at the moment which I would like to finish first).

**Comment by portante** [comment]
Great, I'll see if I can't build a package for this with help from co-workers at Red Hat to confirm the behavior before we merge.  Then I'll rebase on top of latest and we can merge.

**Comment by rgerhards** [comment]
excellent - just let me know explicitly (not just by git push) when you think it is ready to merge. Will do than ASAP.

**Comment by portante** [comment]
@rgerhards, almost ready, I just found a small error handling bug and updated the commit.  We'll be testing soon.

**Comment by rgerhards** [comment]
@portante side-note: I identified some instability in CI testing, that's causing the failures you see. If you rebase to current master that should go away. Else I'll just re-submit. I am working on the root cause, it's probably a race in the test setup itself, but may be an actual failure in an unrelated component. So it takes some time to investigate. Current master has the prime culprit temporarily disabled.

**Comment by portante** [comment]
@rgerhards, this is ready to merge, thanks!

Later this evening I’ll rebase it just to be safe if you want.

**Comment by portante** [comment]
@rgerhards, rebased the patch and pushed it again.  It is ready to be merged.

We did some local testing with this patch applied to RHEL 7.4 v8.24.0 and did not see any file handle leaks, nor did we see any duplicate logs captured due to starting from the previously saved cursor.

I'll be posting the general methodology used for verifying all is good in another dedicated git repo.

**Comment by portante** [comment]
@rgerhards, any further word on merging this patch?

**Comment by rgerhards** [comment]
@portante sorry for the delay, will happen today. I got side-stepped by intense discussion on rsyslog-doc...

**Comment by rgerhards** [comment]
@portante sorry, took me a day more. The past ~ two weeks things tend to be a bit unexpected ;-) But now finally merged, and thanks once again for the contribution!

**Comment by portante** [comment]
Thanks @rgerhards!  Glad to help.  Now to consider imfile and symlinks ...

**Comment by rgerhards** [comment]
@portante careful with imfile! This is up for a big rewrite -- @alorbach and I originally planned this for 8.33, but due to all the doc work etc we can't make that goal. There are some design deficits that really need to be fixed. I guess the symlink functionality could be brought to work in current code, but that's probably a very unfriendly experience...

**Comment by rgerhards** [comment]
@portante see https://github.com/rsyslog/rsyslog/projects/4

**Pull request merged**
