### PR TITLE
Add fixed-width option

### PR DESCRIPTION
**Pull request by jite**
Pads a string with spaces up to toChar field if string is shorter, if
string is equal then nothing is done and if string is longer then it
gets truncated.

From mailing list patch proposal.

### CODE REVIEW

**Comment by rgerhards** [comment]
I think this is missing code for current-style template definitions. Have not thouroughly checked, though. Will do when I have a bit more time. If it is not present, we need this to be able to merge.

**Comment by jite** [comment]
Yes you're right, it does miss that. I'll update with a new patch.

**Comment by jite** [comment]
@rgerhards New patch proposal uploaded

**Comment by rgerhards** [comment]
merged into master-candidate, will migrate from there to master (after buildbot tests)

**Comment by rgerhards** [comment]
It would be great if you could also update the doc at https://github.com/rsyslog/rsyslog-doc so that others can actually use the feature.

**Comment by jite** [comment]
@rgerhards Absolutely. Should I write that it's available since rsyslog 8.13.0? Does it make it to that?

**Comment by rgerhards** [comment]
yup, it's already in the tree that becomes 8.13.0 :-)

**Pull request merged**
