### PR TITLE
libksi 3.4.0.1

### PR DESCRIPTION
**Pull request by vii5ard**
The latest libksi release has some compatibility breaking changes.

### CODE REVIEW

**Comment by rgerhards** [comment]
we need to wait for the libksi versioning to be in place before we can merge

**Comment by rgerhards** [comment]
We should also close https://github.com/rsyslog/rsyslog/issues/581 before merging this (even though it may not strictly be required for 3.4.0.1).

**Comment by alorbach** [comment]
Going to take care on issue https://github.com/rsyslog/rsyslog/issues/581 after merging because I can't compile with libksi 3.4.0.x without this patch.

**Comment by rgerhards** [comment]
@alorbach  I think this merge needs to be undone. As the versioning is not yet correct, we cannot build this version without getting into real big trouble. Anything that depends on this patch needs to wait until it can finally be merged.

**Comment by alorbach** [comment]
Pullrequest has been reverted with this commit until the versioning issue is being solved: 
https://github.com/rsyslog/rsyslog/commit/0fe7f1aa2837ebb8515083af91032d8fbdc6c381

**Comment by alorbach** [comment]
Pullrequest finally merged now.

**Pull request merged**
