### PR TITLE
Fix ffaup thread safety

### PR DESCRIPTION
**Pull request by ThibaudCartegnie**
ffaup fix : The ffaup function fails to work properly when it is used with multiple workers.
The faup_handler_t struct is not supposed to be shared between threads.

This may cause memory corruptions and race conditions when used inside of actions.

### CODE REVIEW

**Comment by frikilax** [comment]
I confirm there is a legitimate bug in the handling of the faup handler and that this development  resolves it

**Comment by rgerhards** [comment]
@ThibaudCartegnie can you please amend the exact description (like here in the issue) to the commit itself. Only so way we ensure the information is tied forever to the project, no matter what fate github will have over time. Thx!

**Comment by ThibaudCartegnie** [comment]
@rgerhards We found an easier fix that does not involve the __thread extension, I will push that solution instead of the one presented with a fixed commit message as you asked.

**Comment by rgerhards** [comment]
Merci! Merged.

**Pull request merged**
