### PR TITLE
Adds simple templating to omjournal

### PR DESCRIPTION
**Pull request by bobthemighty**
As per #769 I wanted to transform log lines before they were sent to the journal. 

I've hacked about a bit, and have something that works, based on the ommongodb module. Each entry in the OMSR_TPL_AS_JSON is dumped into the journal. The caveat is that if you don't include a MESSAGE field, then you don't see anything useful.

```
template(name="journaljson" type="list"){
 property(name="$!@message" outname="MESSAGE") 
 property(name="$!@fields!levelname" outname="LEVEL") 
 property(name="$!@fields!funcName" outname="CODE_FUNC")
 property(name="$!@fields!lineno" outname="CODE_LINE")
 property(name="$!@fields!filename" outname="CODE_FILE")
 property(name="syslogtag" outname="SYSLOG_IDENTIFIER")
}

action(type="omjournal" template="journaljson")
```

If you don't provide a template, then the module continues to behave as before.

Seems to build under both gcc and clang, though the static analyzer complains about a possible uninitialised value when I'm freeing the pointers to the iovec strings. I'm 99.5% convinced that it's a false positive, but if you've any suggestions on how I clean that up, I'm all ears.

I'd also really like to add a new property replacer for converting log level names (INFO, WARN, FATAL etc.) to syslog severity levels. Any pointers would be warmly welcomed.

### CODE REVIEW

**Comment by rgerhards** [comment]
Thanks for the patch.

I would suggest that you check the reasoning static analyzer provides: often, it then becomes clear that it is indeed a true problem. If it is a false positive, you should normally be able to easily work around it. But I have seen that travis didn't err out -- this may be a good sign, it may also be an indication of a problem in the travis environment.

I would also appreciate if you could squash commits. Those that you only used to correct yourself should better go away. If you haven't done this yet: ```git rebase -i``` is your friend.

Finally, it would be great if you could also update the documentation in our sister project https://github.com/rsyslog/rsyslog-doc

**Comment by rgerhards** [comment]
I had forgotten: have you already run static analyzer locally and looked at the elaborative report (the one shown via scan-view)? If not, that's definitely the next step to take.

**Comment by bobthemighty** [comment]
Hi Rainer,

Happy to oblige. Can you comment briefly on the property replacer?

I have log4j style level names in my incoming logs, and I want to map them
to syslog severity levels so that they end up correctly tagged in the
journal. I can see that there's some functionality in msg.c in this area,
but nothing that's obviously exposed to end-users. Am I missing something?
If not, would you be happy to accept a patch that added a new pair of
property replacers, one to map severity ints to names, and another to map
names to ints?

I *have* run the static analyser with scan-view. The warning I get tells me
that I may be trying to free an uninitialised value when I'm traversing an
array of iovec and freeing the string each one points to. I'll do a bit
more digging.

Thanks,

 -- Bob.

**Comment by rgerhards** [comment]
There are the syslogfacility-text and syslogseverity-text properties. They should do the trick?

regarding static analyer: iovec may actually be a false positive. We still should try very hard to find a work-around, as otherwise we get into trouble with automatted testing. There is some limited advise in the static analyzer doc itself (commenting out code during analyzer run as a last resort).

**Comment by bobthemighty** [comment]
My problem is that the incoming message will have been written with a fixed
severity: my data are coming from the docker syslog driver, which isn't
inspecting application logs.

If a docker container logs to stdout, then the syslog driver will send the
resulting message with severity LOG_INFO, if the container logs to stderr,
then the driver logs with LOG_ERR.

An application in the container will usually have chosen an appropriate log
level of its own accord, and that's the data I want to pull from the
incoming message.

On Wed, Feb 3, 2016 at 10:25 AM, Rainer Gerhards <notifications@github.com>
wrote:

> There are the syslogfacility-text and syslogseverity-text properties. They
> should do the trick?
>
> regarding static analyer: iovec may actually be a false positive. We still
> should try very hard to find a work-around, as otherwise we get into
> trouble with automatted testing. There is some limited advise in the static
> analyzer doc itself (commenting out code during analyzer run as a last
> resort).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/pull/770#issuecomment-179149717>.
>



-- 
Q. How many members of a demographic group does it take to perform a
specified task?

A. A finite number; one to perform the task, and the remainder to act in a
manner stereotypical of the group in question.

**Comment by rgerhards** [comment]
2016-02-03 11:34 GMT+01:00 bobthemighty <notifications@github.com>:

> My problem is that the incoming message will have been written with a fixed
> severity: my data are coming from the docker syslog driver, which isn't
> inspecting application logs.
>
> If a docker container logs to stdout, then the syslog driver will send the
> resulting message with severity LOG_INFO, if the container logs to stderr,
> then the driver logs with LOG_ERR.
>
> An application in the container will usually have chosen an appropriate log
> level of its own accord, and that's the data I want to pull from the
> incoming message.
>
>
would you mind taking this question to the rsyslog mailing list? Reason is
that we don't pollute this bug tracker, especially as I would need to go
pretty off-topic. Also, other members may have advise and for even others
it is educating.

Rainer

**Comment by bobthemighty** [comment]
@rgerhards I've rewritten the code to an uglier form that's more amenable to static analysis.

**Comment by rgerhards** [comment]
@bobthemighty I feel your pain, and have had it often enough myself. But the long-term benefits, I think, justify it. It would be much nicer if one could tell the static analyzer that this is a false positive, tough. I myself have currently two things that I am working  very hard on a workaround, which I have not yet found :-(

**Pull request merged**
