### PR TITLE
rainerscript: new function "http_request"

### PR DESCRIPTION
**Pull request by rgerhards**
closes https://github.com/rsyslog/rsyslog/issues/1977

### CODE REVIEW

**Comment by rgerhards** [comment]
@Whissi @mbiebl This creates a new build requirement for libcurl for rsyslog core. I think this is available on almost all modern systems by default. Anyhow, if you see a problem, let me know and I'll add an ability to disable the need for libcurl.

**Comment by Whissi** [comment]
Don't forget embedded devices. Please make this optional, i.e. allow to disable cURL integration via configure.

**Comment by mbiebl** [comment]
Fwiw, I share David's more general concerns in #1977 to build this directly into the core

**Comment by rgerhards** [comment]
OK, I'll first provide a switch to disable it.

Building it outside the core requires a whole new callable interface (for functions). Unfortunately I have no time to design and implement this ATM. So I hope it is OK to provide the switch initially.

In general, everything can be abused. It won't offer better performance if we do it via a message modification module. A prime legit case is to obtain AWS metadata and the like. I don't want to add a specialized function for each and every of such calls. With the ability to do a http request very easily and a bit of script logic, this is nicely and easily done.

**Comment by rgerhards** [comment]
FYI: PR for disabling: https://github.com/rsyslog/rsyslog/pull/2258

**Pull request merged**
