### PR TITLE
omelasticsearch: add optional timeout for the index operation

### PR DESCRIPTION
**Pull request by mbarbon**

### CODE REVIEW

**Comment by rgerhards** [comment]
please add doc to https://github.com/rsyslog/rsyslog-doc/

**Comment by rgerhards** [comment]
Thx for the PR!

**Comment by rgerhards** [comment]
I added some very basic doc. Though not good, it permits to merge this PR.

**Comment by mbarbon** [comment]
> I added some very basic doc. Though not good, it permits to merge this PR.

https://github.com/rsyslog/rsyslog-doc/pull/960 with a brief description.

**Pull request merged**
