### PR TITLE
do_inotify block only once for events

### PR DESCRIPTION
**Pull request by kortemik**
do_inotify block only once for events with timeouts. there is possible scenario where no data is available and read() enters blocking while poll() is released.

### CODE REVIEW

**Comment by kortemik** [comment]
the centos_6 cancelled after timeout may be a bug:
"rsyslogd debug: input thread term: timeout expired waiting on thread imfile termination - canceling"
though it was there all the time as EINTR is being used as poll restart condition without checking if shutdown is the cause of EINTR invocation. should be fixed now.

**Comment by rgerhards** [comment]
note: inotify is racy, thus it can happen that you get a notification but no data is left for reading

**Comment by kortemik** [comment]
i think this is now ready for merge

**Comment by rgerhards** [comment]
I cannot merge because this would introduce a bug. pls see https://github.com/rsyslog/rsyslog/pull/4445#issuecomment-712235951

**Comment by kortemik** [comment]
I am sorry for not understanding that the note was for me. Would it be possible to explain in very brief the bug introduced as I am unable to undestand how the functionality changes?

**Comment by kortemik** [comment]
I think the change introduced here changes the racy reading to be same for the triggered file as for the rest of the files:

current:
1) Inotify is triggered
2) Triggering file is read for new data
3) Rest of the files are read for timer expiration
4) more inotifys are processed *these may be at the end of the file already as well then*

new:
1) Inotify is triggered
3) All files are read for timer expiration, which includes the triggering file
2) Triggering files is read for data, *this may be at the end of the file already then*
4) more inotifys are processed *these may be at the end of the file already as well then*

therefore I find that the change introduced harmonises the way triggering and the future triggers are handled, by not making the triggering one as an exceptional one, so it should be easier to test the changes as well.

If I still have it wrong then please close.

**Comment by rgerhards** [comment]
@kortemik Please add relevant info to the commit message itself. Among others makes reviewing easier (also for distro packagers who think about back-porting). I am going through the code soon,

**Review by rgerhards — APPROVED** [review]
code looks good to me, but we need a more descriptive commit message

**Comment by rgerhards** [comment]
I don't know why this was closed when I fixed the commit message, but I have re-opened it at https://github.com/rsyslog/rsyslog/pull/4844

**Pull request closed without merging**
