### PR TITLE
add contrib module omhttp

### PR DESCRIPTION
**Pull request by PascalWithopf**
closes https://github.com/rsyslog/rsyslog/issues/1797
replaces https://github.com/rsyslog/rsyslog/pull/2782

### CODE REVIEW

**Comment by rgerhards** [comment]
core functionality will be merged via https://github.com/rsyslog/rsyslog/pull/2993

**Comment by darakian** [comment]
@PascalWithopf is it possible to get conf file example of using omhttp?
/*auf meine schlechte deutsch*/
Ist es möglich, ein beispiel fur ein conf file mit omhttp haben?

**Comment by PascalWithopf** [comment]
@darakian omhttp is used like the other actions
``action(type="omhttp" ...)``
If you look in the code https://github.com/rsyslog/rsyslog/blob/master/contrib/omhttp/omhttp.c#L143
you can see a list of all parameters you can use, most of them have a self describing name.

The two parameters restpath and dynrestpath work together. In restpath you can specify the path directly or when you set dynrestpath "on" you can specify a template name, and the template will be used for the restpath. That way you can use a dynamic restpath.

**Comment by davidelang** [comment]
On Tue, 20 Nov 2018, Pascal Withopf wrote:

> @darakian omhttp is used like the other actions
> ``action(type="omhttp" ...)``
> If you look in the code https://github.com/rsyslog/rsyslog/blob/master/contrib/omhttp/omhttp.c#L143
> you can see a list of all parameters you can use, most of them have a self describing name.
>
> The two parameters restpath and dynrestpath work together. In restpath you can specify the path directly or when you set dynrestpath "on" you can specify a template name, and the template will be used for the restpath. That way you can use a dynamic restpath.

hmm, every other case where we have an option for a dynamic parameter, it is 
given a different name.

If I could change history, making the system smart enough to figure out if the 
parameter is a template or not would be a good idea (eliminating even the 
dynrestpath=on requirement)

But since we can't change history, I think it would make more sense to make 
dynrestpath be the name of the template to use to be consistant with all other 
similar uses.

and if we do ever make the config parser smart enough to check if the 
file/restpath/etc parameter is the name of a template, then we can do the same 
thing here. (such a change would have a small, but non-zero chance of breaking 
existing configs, so it may require a global option to enable, but in the long 
run would simplify things)

David Lang

**Comment by darakian** [comment]
Many thanks for the help. For anyone that lands here due to a search I had my config in
```
/etc/rsyslog.d/my.conf
```
with the following
```
$template jsonRfc5424Template,"{\"type\":\"syslog\",\"host\":\"%HOSTNAME%\",\"role\":\"api-hello-app\",\"message\":\"<%PRI%>1 %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% %MSGID% %STRUCTURED-DATA% %msg:::json%\"}\n"

module(load="omhttp")
action(type="omhttp" server="127.0.0.1" serverport="8080" restpath="events" dynRestPath="off" usehttps="off" template="jsonRfc5424Template")
```
The template is in place because my log sink requires json formatted logging. One annoyance I came across was. 
usehttps = on/off does not jive with me. usehttps = yes/no does. Minor issue, but counterintuitive.

**Pull request merged**
