### PR TITLE
added test for imfile ReadMode=2

### PR DESCRIPTION
**Pull request by radu-gheorghe**
See https://github.com/rsyslog/rsyslog/issues/144

At the moment, the test fails because of that bug. A couple of notes:
- if you set ReadMode to 0, the test still fails (more headers than expected), but at least all data gets through
- when starting rsyslog, there's a warning about the deprecated use of StateFile. I guess the clean way around that is to remove the StateFile option from all imfile tests and change diag.sh to remove all imfile-state* files. I can do that as a separate PR if it's needed

### CODE REVIEW

**Comment by rgerhards** [comment]
On the state files: We should keep this in a couple of tests so that we can test if the legacy functionality still works. IMHO we need to do this as long as we support it. Most probably not for all tests, maybe a single one is sufficient. I would suggest to duplicate the test(s) in question with and without state file.

I'll merge this into one of my temp development branches first, which I will use to look into the issue. When fixed, we can merge everyting into master.

**Comment by rgerhards** [comment]
A quick question: would ASL 2.0 as lincese be fine with you, too? (Else I need to remove the test if we ever manage to move to ASL 2.0, thus the question).

**Comment by radu-gheorghe** [comment]
Yes, ASL2 is fine, sure. I was just copying it from the imfile-basic test.

**Comment by rgerhards** [comment]
I have merged this into my feature branch, which contains the fix. I think both togehter should hit master branch. This will happen once the feature branch passed all tests.

**Comment by rgerhards** [comment]
This is merged, but does not show up as merged probably due to a rebase.

**Pull request closed without merging**
