### PR TITLE
Clarify the meaning of loadConf and RunConf

### PR DESCRIPTION
**Pull request by Cropi**
The PR intends to clarify the meaning of loadConf and runConf. These were originally introduced to facilitate a later move to dynamic config loads.  Over the years, the use of these pointers has become unclear. 

- loadConf was intended for candidate config (the new one)
- runConf for the currently running config

### CODE REVIEW

**Comment by rgerhards** [comment]
The systemd check is a CI issue. Some images seem to have changed, I am investigating this. Not a merge blocker.

Note: I'll probably move this to the Feb '22 release as I am preparing Dec today (to keep a bit away from xmas).

**Comment by Cropi** [comment]
Sure, take your time. There is no need to rush, especially before the holidays:)

**Comment by Cropi** [comment]
Regarding the "buildbot/rsyslog ElasticSearch codecov" failing test, is there a way to find out which test did not pass?

**Comment by rgerhards** [comment]
> Regarding the "buildbot/rsyslog ElasticSearch codecov" failing test, is there a way to find out which test did not pass?

Maybe the CI Worker was overwhelmed (unlikely, but). To check, I reinitiated a new run.

**Comment by rgerhards** [comment]
Note: Journal CI probably requires CI worker update. Ignoring issue for now.

**Pull request merged**
