### PR TITLE
Fix mmnormalize_regex failure for rule w/ noeol

### PR DESCRIPTION
**Pull request by portante**
Looks like at least on Fedora 21 with liblognorm 1.1.2-2, this test
fails because of the missing newline character before EOF.

Partial fix for the failure reported in #605.

### CODE REVIEW

**Comment by portante** [comment]
@theinric, this we should get into Fedora, too.

**Comment by rgerhards** [comment]
sorry, I think this crossed: https://github.com/rsyslog/rsyslog/pull/627
I merged from top to bottom of the list ;)

**Comment by rgerhards** [comment]
Thanks for the fix. @theinric: I suggest you do NOT enable regex by default. IMHO its a bad idea. See also: https://github.com/rsyslog/liblognorm/issues/143

**Comment by rgerhards** [comment]
merged to master-candidate

**Pull request merged**
