### PR TITLE
Fix ElasticSearch Test broken by ES incompatibility

### PR DESCRIPTION
**Pull request by richm**
https://github.com/rsyslog/rsyslog/issues/4684
According to https://discuss.elastic.co/t/unknown-setting-thread-pool-bulk-queue-size/180120
The setting `thread_pool.bulk` has been renamed to `thread_pool.write`
"The bulk threadpool was renamed to write in 6.3.0, and support for the legacy bulk name was removed in 7.0.0 133."

### CODE REVIEW

**Comment by richm** [comment]
@rgerhards This PR is incomplete, but this is as far as I can go.  It seems that ES7 has changed the bulk api in some way that causes the response not to register any bulk rejections.  As far as I can tell, the good records are being correctly stored, and the bad records are being correctly rejected.  So one option is to change the test to skip looking for bulk index rejections (alternately, skip that check on ES6 or later).  I'll see if I can find someone - @praiskup @Cropi @portante - any interest in fixing this?

**Comment by portante** [comment]
> @rgerhards This PR is incomplete, but this is as far as I can go. It seems that ES7 has changed the bulk api in some way that causes the response not to register any bulk rejections.

So if one overwhelms an ES V7 instance, you no longer see bulk rejections (status code in each response action payload of 429)?

> As far as I can tell, the good records are being correctly stored, and the bad records are being correctly rejected.

For "bulk rejection" (429) to happen, the Elasticsearch instance has to have exhausted its `thread_pool.write` count of threads.  Then a new request which can't be queued should see that response.  This test appears to be designed to make that happen, but perhaps the queue size setting is being ignored for some reason?  Has anybody stood up an Elasticsearch V7 instance to verify that setting `thread_pool.write.queue_size` to one actually does what we expect?

>  So one option is to change the test to skip looking for bulk index rejections (alternately, skip that check on ES6 or later). I'll see if I can find someone - @praiskup @Cropi @portante - any interest in fixing this?

If the goal of this test is to verify that the retry ruleset works, then just dropping the check for bulk index rejections from the test is fine.

But it appears that the code is retrying lots of records, which it shouldn't (400s, duplicates on create, etc.) where the re-try should not be once, but continuously until they get through.

**Comment by rgerhards** [comment]
> It seems that ES7 has changed the bulk api in some way that causes the response not to register any bulk rejections.

Yeah - I tried the change myself, but saw that the test failed. It looks like (already discussed) ES changed not only the name but also semantics (I really hate braking changes, don't know why folks always do that...). I am good with anything that solves the situation. At worst, we need to remove the test if with newer ES it is impossible to actually test the functionality. So any work-around is appreciated. To go forward, I'll possibly disable the test temporarily in my PR, so that we can pursue integrating the proposed new functionality (which addresses another breaking change...).

**Comment by rgerhards** [comment]
I have now updated the current development state to ES 7 (via https://github.com/rsyslog/rsyslog/pull/4683). I did so by temporarily disabling the test. You now need to rebase and remove the "disabling lines" at the top (https://github.com/rsyslog/rsyslog/blob/master/tests/es-bulk-retry.sh#L4). Then we see how any new test works out.

**Comment by richm** [comment]
> > It seems that ES7 has changed the bulk api in some way that causes the response not to register any bulk rejections.
> 
> Yeah - I tried the change myself, but saw that the test failed. It looks like (already discussed) ES changed not only the name but also semantics (I really hate braking changes, don't know why folks always do that...).

The good news is that Elasticsearch only does breaking changes for major releases (e.g. semantic versioning).  The bad news is that ES has had several major releases in the past few years . . .

> I am good with anything that solves the situation. At worst, we need to remove the test if with newer ES it is impossible to actually test the functionality.

It will require someone doing some intensive investigation + trial-and-error to figure out how to test the bulk rejection handling with ES7.  I just don't have time to do this, which is why I was hoping @Cropi @praiskup could do this, or maybe @portante knows someone interested in rsyslog + elasticsearch.

> So any work-around is appreciated. To go forward, I'll possibly disable the test temporarily in my PR, so that we can pursue integrating the proposed new functionality (which addresses another breaking change...).

I think it is best for now to disable the test.

**Comment by rgerhards** [comment]
@richm ack, sounds good.

If you could do me nevertheless the favor to rebase and remove the skip lines inside the test. That would leave this tracker here open for anyone potentially following up. I can also do it myself (assuming you permitted admin pushes), but this always sounds a bit "unclean" to me ;-) But don't feel pressed, I'll do in a few days if needed.

**Comment by rgerhards** [comment]
@radu-gheorghe can you help with the new semantics in ES 7?

**Comment by radu-gheorghe** [comment]
Certainly! I had a quick look and this line looks wrong: https://github.com/rsyslog/rsyslog/blob/master/tests/es-bulk-retry.sh#L112

We define a type, but types are not supported anymore, so the `test-type` level can go out entirely. I don't know if this is enough to fix the test, feel free to ping me if it doesn't. It's been a long time since I fiddled with rsyslog tests :( So if you want me to look deeper, can you give me a quick list of reproduction steps? Or a link to where they are?

**Comment by rgerhards** [comment]
@radu-gheorghe thx for the quick reply, much appreciated. I'll update this PR now so that everyone can see the test failure. I'll also point you to the code in question and will check if your tipp already helps solve the situation.

**Comment by radu-gheorghe** [comment]
Great! You're welcome! Just @ ping me if I can help with anything.

**Comment by rgerhards** [comment]
@radu-gheorghe I checked the suggestion on line 112 ("type") and this is actually only executed when ES 5 is used.
I have also rebased and modified the test to be executed now with ES 7.14, Please have a look e.g. at https://github.com/rsyslog/rsyslog/pull/4685/checks?check_run_id=3621086247 (go to the "error log" step, not the one github opens - "error log" is right below)

In a nutshell, the issue is that ES is configured in a way that should trigger errors, which are then retried. @portante has described this much better in https://github.com/rsyslog/rsyslog/pull/4685/checks?check_run_id=3621086247 than I can ;-) -- actually, I have no idea (due to lack of ES know-how) of how exactly the test is supposed to work.

The problem is that seemingly not only the syntax of ES config parameter `thread_pool.bulk` has changed but also the semantic. This seems to break the test fail/success detection.

I hope I could clarify. The current cure is to disable the test (and remove it in the long term if we cannot re-enable it). It would be better to know what actually happens and how to fix the test. At worst, the test may indeed bring up an issue in rsyslog code which we see only with ES 7, but which we misunderstand as an ES 7 semantic change. So I don't like to disable the test as a cure without knowing what's happening ;-)

**Comment by radu-gheorghe** [comment]
Let me start with the complaints :)
- I still don't know how to reproduce this issue in isolation so I can poke around until I can find a fix
- maybe the link to @portante's comment was a bad copy-paste? But I read this thread carefully, so I guess I didn't miss it

Now let me explain my understanding of the test as it stands:
- we're sending 100 messages
- we're assuming some will fail with 429 and we'll retry them
- in the end, all should get in successfully, but we should see the rejected counts
- the rejected counts are actually [kept by rsyslog](https://github.com/rsyslog/rsyslog/blob/6eaec67cf97f57b6e076091dd3b1e781cedbe92c/plugins/omelasticsearch/omelasticsearch.c#L2251) when it gets 429s

Finally, here are my findings so far:
- I checked the script that generates the config. Looks OK to me, with the exception of `>>` which looks like it appends to something, I'm not sure if that file is already there. If it's not, we should be good. The config is OK
- the thread pool settings are applied, I could check that via `curl localhost:9200/_cat/thread_pool?h=name,size,queue_size`
- my feeling is that we're betting on a race. We're sending 100 messages (in batches of 16? that's the default, I think) and we're hoping that one thread on the Elasticsearch side with a queue of 1 would be slow enough to reject. But we don't have such guarantees
- unfortunately, we can't force ES to reject by setting any thread values to 0 :(
- with values set to 1, if I do a simple `while true; do curl -X POST -H 'Content-Type: application/json' 'http://localhost:9200/test/_doc' -d '{"foo": "bar"}'; done`, I get no rejections. Elasticsearch outperforms bash+curl :)
- one change to ES 7 was moving to a default of 1 shard (from 5). This might make the race harder for the test, because writes would spawn one thread per bulk per shard. One bulk would spawn 6 threads before (one for "coordination" and 5 per shard) and it would spawn just one now. So maybe a simple fix could be to force the number of shards, by adding it to the index creation process, like:

```
curl -s -H 'Content-Type: application/json' -XPUT localhost:${ES_PORT:-19200}/rsyslog_testbench/ -d '{
  "settings": {
    "index.number_of_shards": 10
  },
  "mappings": {
    "properties": {
      "msgnum": {
        "type": "integer"
      }
    }
  }
}
'
```

That said, with the above, I still couldn't get rejections with curl :( But maybe with rsyslog we can, especially if we use multiple worker threads (do we, by default?) and/or a lower batch size (e.g. 2 or even 1 message). It would still be a race and a hack, but maybe if we consistently "win" it, we'd be good :)

I'd love to get to the bottom of this, but my main blocker is my inability to reproduce the issue in isolation. Worst case scenario, I'd reproduce bits (e.g. set up rsyslog with that config on a local ES), but I'm not sure if that would fix the test - especially since I would suggest changes that I won't be able to test (e.g. maybe a syntax error would sneak in...).

Still, maybe the above helps!

**Comment by rgerhards** [comment]
@radu-gheorghe Thanks for the thoughtful reply.

The link to @portante's reply was correct, but maybe I understood it not sufficiently to evaluate it ;-)

Re local repo, sorry for the slim info. There are various ways to do it. The best possibility, IMHO, is to use a docke container. We use containers inside CI, and so you could use the very same environment that CI uses. The container also has the advantage that you do not need to get all the build dependencies.

Is docker OK with you? If so, I will provide detail instructions - it's not much, but you need the right pieces.

**Comment by rgerhards** [comment]
Well, just in case: ;-)
```
$ cd some-workdir
$ git clone https://github.com/rsyslog/rsyslog.git
$ cd rsyslog
$ export RSYSLOG_DEV_CONTAINER='rsyslog/rsyslog_dev_base_ubuntu:20.04'
$ devtools/devcontainer.sh --rm -ti
# Now inside container
$ devtools/run-configure.sh
$ make -j
# rsyslog built
$ cd tests
$ ./es-bulk-retry.sh
# Test runs, and can be edited :-)
```

**Comment by richm** [comment]
> Let me start with the complaints :)
> 
>     * I still don't know how to reproduce this issue in isolation so I can poke around until I can find a fix
> 
>     * maybe the link to @portante's comment was a bad copy-paste? But I read this thread carefully, so I guess I didn't miss it
> 
> 
> Now let me explain my understanding of the test as it stands:
> 
>     * we're sending 100 messages

We're sending a single HTTP message - a bulk api request - which consists of 100 operations, all of which are to create a new record in ES.

> 
>     * we're assuming some will fail with 429 and we'll retry them

yes

> 
>     * in the end, all should get in successfully, but we should see the rejected counts

Actually, half of the messages should get accepted successfully, and half should be rejected due to syntax error (response.badargument)

> 
>     * the rejected counts are actually [kept by rsyslog](https://github.com/rsyslog/rsyslog/blob/6eaec67cf97f57b6e076091dd3b1e781cedbe92c/plugins/omelasticsearch/omelasticsearch.c#L2251) when it gets 429s

yes

> 
> 
> Finally, here are my findings so far:
> 
>     * I checked the script that generates the config. Looks OK to me, with the exception of `>>` which looks like it appends to something, I'm not sure if that file is already there. If it's not, we should be good. The config is OK

note that in bash, if you use `>>` and the target file does not exist, it will be created

> 
>     * the thread pool settings are applied, I could check that via `curl localhost:9200/_cat/thread_pool?h=name,size,queue_size`
> 
>     * my feeling is that we're betting on a race. We're sending 100 messages (in batches of 16? that's the default, I think) and we're hoping that one thread on the Elasticsearch side with a queue of 1 would be slow enough to reject. But we don't have such guarantees

yes, that's essentially it - and this seems to work with ES 5 and earlier

> 
>     * unfortunately, we can't force ES to reject by setting any thread values to 0 :(

1 is the minimum

> 
>     * with values set to 1, if I do a simple `while true; do curl -X POST -H 'Content-Type: application/json' 'http://localhost:9200/test/_doc' -d '{"foo": "bar"}'; done`, I get no rejections. Elasticsearch outperforms bash+curl :)

That isn't doing the same operation - that's a "simple" record addition, not a bulk record index operation.  You would need to create a rather large JSON blob to simulate a bulk index operation.  Something like https://github.com/openshift/origin-aggregated-logging/blob/master/test/zzzz-bulk_rejection.sh, especially around https://github.com/openshift/origin-aggregated-logging/blob/master/test/zzzz-bulk_rejection.sh#L138

> 
>     * one change to ES 7 was moving to a default of 1 shard (from 5). This might make the race harder for the test, because writes would spawn one thread per bulk per shard. One bulk would spawn 6 threads before (one for "coordination" and 5 per shard) and it would spawn just one now. So maybe a simple fix could be to force the number of shards, by adding it to the index creation process, like:
> 
> 
> ```
> curl -s -H 'Content-Type: application/json' -XPUT localhost:${ES_PORT:-19200}/rsyslog_testbench/ -d '{
>   "settings": {
>     "index.number_of_shards": 10
>   },
>   "mappings": {
>     "properties": {
>       "msgnum": {
>         "type": "integer"
>       }
>     }
>   }
> }
> '
> ```
> 
> That said, with the above, I still couldn't get rejections with curl :( But maybe with rsyslog we can, especially if we use multiple worker threads (do we, by default?) and/or a lower batch size (e.g. 2 or even 1 message). It would still be a race and a hack, but maybe if we consistently "win" it, we'd be good :)

ok, sounds good

> 
> I'd love to get to the bottom of this, but my main blocker is my inability to reproduce the issue in isolation. Worst case scenario, I'd reproduce bits (e.g. set up rsyslog with that config on a local ES), but I'm not sure if that would fix the test - especially since I would suggest changes that I won't be able to test (e.g. maybe a syntax error would sneak in...).
> 
> Still, maybe the above helps!

**Comment by radu-gheorghe** [comment]
Thanks, @rgerhards and @richm ! Yes, Docker is perfectly fine, let me try it out and come back.

**Comment by rgerhards** [comment]
@radu-gheorghe I made a small mistake in the docker instructions: it's not `make -j` but `make -j check TESTS=`. The latter builds the testbench tools (but does not run the tests). Tools are needed to run the test manually.

**Comment by radu-gheorghe** [comment]
Thanks, @rgerhards! Unfortunately, `make -j check TESTS=.` fails with:

```
miniamqpsrvr.c: In function 'amqp_srvr':
miniamqpsrvr.c:456:9: error: 'frame.data' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  456 |     p = amqpFieldFprintf("Exchange:", frame.data + 2);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
miniamqpsrvr.c:507:19: error: 'frame.datalen' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  507 |     if (frame.data[frame.datalen-1] != '\n')
      |                   ^
miniamqpsrvr.c:294:20: error: 'frame.method' may be used uninitialized in this function [-Werror=maybe-uninitialize]
  294 |  amqp_frame_type_t frame;
      |                    ^~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:3538: miniamqpsrvr-miniamqpsrvr.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/rsyslog/tests'
make[1]: *** [Makefile:3827: check-am] Error 2
make[1]: Leaving directory '/rsyslog/tests'
make: *** [Makefile:924: check-recursive] Error 1
```

But then I did `make -j` and that seemed to work. I'll keep going, I seem to be able to reproduce the issue.

**Comment by rgerhards** [comment]
> Unfortunately, `make -j check TESTS=.` fails with:

that's interesting, because it is the same environment... I'll check.

**Comment by radu-gheorghe** [comment]
I think I found a fix. I'm not sure how good it is, because there are things I'm surely missing in how the test framework runs. Maybe others can comment.

Changes:
- `thread_pool.bulk` -> `thread_pool.write`. I'm not sure if we even need the conditional logic there, maybe we'll just support ES 7+?
- `searchType="test-type` -> `searchType="_doc". Similarly, already in the PR
- added 10 shards, as written above. At this point I get bulk rejections, but not all messages are there
- I think the missing messages are also due to a race: Elasticsearch is [near-realtime](https://www.elastic.co/guide/en/elasticsearch/reference/current/near-real-time.html), your view on an index might be outdated until the next refresh
- I added `curl --silent localhost:${2:-$ES_PORT}/rsyslog_testbench/_refresh` to `diag.sh`'s `es_getdata()`, right before the `_search` call. This should ensure we get an updated view on the index. And now the test works (on my machine)

We're still betting on a bit of a race with size=1, but I don't see a better option. If it helps, I can prepare a commit (to this PR) with my changes to the index settings and diag.sh. But maybe others see better options, other things to improve?

**Comment by rgerhards** [comment]
Thx - I am just supporting the plumbing here, guess it is a call for @richm. Maybe a PR might be useful for him, and I guess it's no real work to do (neither is drop it later on ;-))

**Comment by richm** [comment]
> I think I found a fix. I'm not sure how good it is, because there are things I'm surely missing in how the test framework runs. Maybe others can comment.
> 
> Changes:
> 
>     * `thread_pool.bulk` -> `thread_pool.write`. I'm not sure if we even need the conditional logic there, maybe we'll just support ES 7+?

doesn't matter to me

> 
>     * `searchType="test-type` -> `searchType="_doc". Similarly, already in the PR
> 
>     * added 10 shards, as written above. At this point I get bulk rejections, but not all messages are there
> 
>     * I think the missing messages are also due to a race: Elasticsearch is [near-realtime](https://www.elastic.co/guide/en/elasticsearch/reference/current/near-real-time.html), your view on an index might be outdated until the next refresh
> 
>     * I added `curl --silent localhost:${2:-$ES_PORT}/rsyslog_testbench/_refresh` to `diag.sh`'s `es_getdata()`, right before the `_search` call. This should ensure we get an updated view on the index. And now the test works (on my machine)

mine too - tested on fedora 34 - works fine with the changes you suggested

> 
> 
> We're still betting on a bit of a race with size=1, but I don't see a better option.

Right.

A radical option would be to use a "mock" elasticsearch - a fake http server that returns specific responses/error codes.  We took a similar approach for rsyslog mmkubernetes testing since we didn't want to install an entire Kubernetes cluster for the test - instead, we create a mock k8s api server - https://github.com/rsyslog/rsyslog/blob/master/tests/mmkubernetes_test_server.py - the drawback for this is that Elasticsearch seems to change its api pretty often, so you would be continually trying to keep the mock http server in sync with the actual Elasticsearch behavior . . .

> If it helps, I can prepare a commit (to this PR) with my changes to the index settings and diag.sh. But maybe others see better options, other things to improve?

I think your changes are fine.

**Comment by radu-gheorghe** [comment]
Thanks, @richm. Excuse my git noobness, but I can't push another commit to this PR, because I think I don't have permissions to your clone:

```
$ git push richm richm-fix-es-bulk-setting:fix-es-bulk-setting
remote: Permission to richm/rsyslog.git denied to radu-gheorghe.
fatal: unable to access 'https://github.com/richm/rsyslog.git/': The requested URL returned error: 403
```

So I'm attaching a patch [here](https://github.com/rsyslog/rsyslog/files/7209044/rsyslog.patch.txt), maybe you can apply it? Or if you give me permissions, I can push the change? Or maybe I'm missing something?

**Comment by richm** [comment]
> Thanks, @richm. Excuse my git noobness, but I can't push another commit to this PR, because I think I don't have permissions to your clone:
> 
> ```
> $ git push richm richm-fix-es-bulk-setting:fix-es-bulk-setting
> remote: Permission to richm/rsyslog.git denied to radu-gheorghe.
> fatal: unable to access 'https://github.com/richm/rsyslog.git/': The requested URL returned error: 403
> ```
> 
> So I'm attaching a patch [here](https://github.com/rsyslog/rsyslog/files/7209044/rsyslog.patch.txt), maybe you can apply it? Or if you give me permissions, I can push the change? Or maybe I'm missing something?

I would suggest that you take over this work - close this PR, and open your own PR.

**Comment by radu-gheorghe** [comment]
OK, I'll try to do that next week (sorry, I'm swamped right now).

**Comment by rgerhards** [comment]
@radu-gheorghe thx again for the effort - and be relieved, I'll handle the point from here on (except when I run into ES issues again). I guess I can update the PR due to my project admin rights, else I'll create a new one. I let you know the outcome.

**Comment by radu-gheorghe** [comment]
Thanks Rainer! And thanks, Richard! 🙏

**Comment by radu-gheorghe** [comment]
Sweet! You're welcome and thanks for the update!

**Pull request merged**
