### PR TITLE
tests: omhttp: add Python 3 compatibility

### PR DESCRIPTION
**Pull request by Whissi**
Fixes: https://github.com/rsyslog/rsyslog/issues/3599

### CODE REVIEW

**Comment by rgerhards** [comment]
@Whissi Thx for the PR. To detect these things in the future immediately: can you suggest how I need to change one of the existing environments (or create a new one) so that Python 3 is default? I know I could use gentoo, but you know I don't know how to set it up ;-) -- or is it easier with containers?

**Comment by Whissi** [comment]
We do have https://github.com/gentoo/gentoo-docker-images.
You still have to switch Python default to Py3 I think and we only publish "stable" stage3 images yet (so you don't get latest bits).

But you should be able to do the same with Debian/Ubuntu for example:

1. Make sure Python 3 is installed, `apt install python3`
2. Switch default Python using `update-alternatives --config python` (you have to 'install' alternatives first)

Keep in mind that this might break the system if packages like apt will only work with system's original Python version. In this case I recommend to do all apt calls first (update, install deps...) and just before starting to build rsyslog, manually change `/usr/bin/python` symlink.

**Comment by rgerhards** [comment]
ok, changing the default does not work - it breaks buildbot. I wonder why it does, because they support python 3, but I guess that doesn't really help ;-)

**Comment by rgerhards** [comment]
@Whissi will merge now as release is immanent. Nevertheless, would you be willing to help us create a CI container based on the gentoo-provided one? When we do it together, it should not be too hard. We probably need to a new issue if we take that route.

**Pull request merged**
