### PR TITLE
Percentile module to track percentile metrics via impstats

### PR DESCRIPTION
**Pull request by n2yen**
Brief overview:
To configure tracking percentile metrics in rainerscript:
User would need to define:
  - which percentile to track, such as [p50, p99, etc.]
  - window size - note, this correlates directly with memory usage to
  track the percentiles.

To track a value, user would call built-in function `percentile_observe()` in their configurations to
record an integer value, and percentile metrics would be emitted every
impstats interval.

### CODE REVIEW

**Comment by n2yen** [comment]
Just putting the PR to gauge interest - welcome feedback, for improvements, thanks!

**Comment by rgerhards** [comment]
please add doc to https://github.com/rsyslog/rsyslog-doc/

**Comment by n2yen** [comment]
> please add doc to https://github.com/rsyslog/rsyslog-doc/

yes will do.

**Comment by rgerhards** [comment]
@n2yen did you have a chance to add doc? I would like to include this in next weeks scheduled stable and for this I would prefer to merge tomorrow.

**Comment by n2yen** [comment]
Hi @rgerhards , yes, I'll work on getting this out today!

**Pull request merged**
