### PR TITLE
Fix Github workflow file

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by rgerhards** [comment]
@orgads just to be sure: the "fix" is the additional comment, so nothing really changed? Just asking as it looks a bit like the patch is partial...

**Comment by orgads** [comment]
It's not an additional comment. I just fixed the indentation. The YAML file was broken.

**Comment by orgads** [comment]
`daqueue-invld-qi.sh` fails, but obviously it's unrelated to this change. The same test failed in #4705.

**Comment by alorbach** [comment]
bGlblSrvrInitDone is a leftover from the refactoring and the variable can be fully removed.

@orgads could you rebase your branch on the current master? I tried checking out your branch but it did not have the "sndrcv_tls_ossl_anon_ciphers.sh" test merged (Was added recently).

**Comment by rgerhards** [comment]
@orgads thx

@alorbach I think removing the variable doesn't look like the right cure. We need to check why the race is triggered, this sounds pretty odd.

**Comment by alorbach** [comment]
I will look into the the anon init issue in a seperated pr

**Comment by orgads** [comment]
I moved the removal of bGlblSrvrInitDone to #4715, and set `continue-on-error` for this job, so you can merge it and investigate the failure afterwards.

When you solve it, just remove the `continue-on-error`.

**Comment by rgerhards** [comment]
Thx again for the PR and your persistence!

**Pull request merged**
