### PR TITLE
Add "fsync" option for imjournal

### PR DESCRIPTION
**Pull request by jvymazal**
The new option makes possible to force physical write of stateFile
to persistent storage, ensuring we do not lose/duplicate messages
in case of hard crash or power loss.

### CODE REVIEW

**Comment by jvymazal** [comment]
Creating doc-pr now, @rgerhards can you get this to 8.1908 ? (to know which version should I put to docs as starting)

Thanks

**Comment by rgerhards** [comment]
> can you get this to 8.1908

yup!

**Comment by rgerhards** [comment]
doc: https://github.com/rsyslog/rsyslog-doc/pull/836

**Comment by rgerhards** [comment]
sry, I was too quick to merge :-( -- the new option will not work because uit is missing in the `modpdescr` table - so the config system does not know about it.

Shall I fix or will you do? Both fine to me.

**Comment by jvymazal** [comment]
Sorry, overlooked that bit, I will add it, the same branch is ok?

**Comment by rgerhards** [comment]
perfect, thx! I should have spotted this before merge ;-)

**Pull request merged**
