### PR TITLE
Solaris

### PR DESCRIPTION
**Pull request by dago**
These changes are required to allow compilation on Solaris 10 with GCC.

### CODE REVIEW

**Comment by rgerhards** [comment]
@dago I am working on CI, thus a couple of flakes...

I just wonder why we do not get build errors on the Solaris 10 workers without this patch. Do you have an explanation?

**Comment by dago** [comment]
The warnings are only activated when compiling with GCC, so when you compile with GCC on other platforms the code path is not used and if you compile with Sun Studio in Solaris the warnings are not activated. The CI only uses Sun Studio to build on Solaris.

**Comment by dago** [comment]
You can have a look at the OpenCSW CI buildbot which shows the first errors: https://buildfarm.opencsw.org/buildbot/builders/rsyslog-solaris10-i386/builds/1292/steps/shell_2/logs/stdio

**Comment by rgerhards** [comment]
> You can have a look at the OpenCSW CI buildbot which shows the first errors: https://buildfarm.opencsw.org/buildbot/builders/rsyslog-solaris10-i386/builds/1292/steps/shell_2/logs/stdio

mhhh... this is strange. Have a look at https://build.rsyslog.com/#/builders/73/builds/2980
Steps 12+ use gcc. Do we need to fix something in our CI?

**Comment by dago** [comment]
It looks like that after the autoreconf not everything is rebuilt. I'd suggest to add something like `gmake distclean` and then cleanly configure again (or just use different targets for Sun Studio and GCC).

**Comment by rgerhards** [comment]
> It looks like that after the autoreconf not everything is rebuilt. I'd suggest to add something like `gmake distclean` and then cleanly configure again (or just use different targets for Sun Studio and GCC).

Doh! I overlooked that there is no `clean` at all. Will fix CI (when done with the other CI work currently going on) and merge only after that - so that I have a test case to know for sure this works ;-)

Thx!

**Comment by rgerhards** [comment]
looks like there is a small glitch in building: https://build.rsyslog.com/#/builders/73/builds/2996/steps/15/logs/stdio

**Comment by dago** [comment]
Ah yes, I wrapped that with an #ifdef but missed the commit:
```
diff --git a/runtime/rsyslog.h b/runtime/rsyslog.h
index dd256a8..85d4d30 100644
--- a/runtime/rsyslog.h
+++ b/runtime/rsyslog.h
@@ -198,7 +198,9 @@
 #define        LOG_LPR         (6<<3)  /* line printer subsystem */
 #define        LOG_NEWS        (7<<3)  /* network news subsystem */
 #define        LOG_UUCP        (8<<3)  /* UUCP subsystem */
+#if !defined(LOG_CRON)
 #define        LOG_CRON        (9<<3)  /* clock daemon */
+#endif
 #define        LOG_AUTHPRIV    (10<<3) /* security/authorization messages (private) */
 #define        LOG_FTP         (11<<3) /* ftp daemon */
 #if defined(_AIX)              /* AIXPORT : These are necessary for AIX */
```

**Comment by rgerhards** [comment]
> Ah yes, I wrapped that with an #ifdef but missed the commit:

should I amend a commit to fix this? Wanted to ask before going ahead...

**Comment by dago** [comment]
I just added the commit, was waiting to be pushed anyway :-)

**Comment by rgerhards** [comment]
looks like we have another one: https://github.com/rsyslog/rsyslog/pull/4100 ;-)

**Comment by rgerhards** [comment]
finally ;-)

**Comment by dago** [comment]
Thanks for merging this so quickly! OpenCSW buildbot is now also clean: https://buildfarm.opencsw.org/buildbot/waterfall?category=rsyslog

**Pull request merged**
