### PR TITLE
Always using curly braces makes your life much safer (some compile warnings fixed)

### PR DESCRIPTION
**Pull request by mostolog**
Related to https://github.com/rsyslog/rsyslog/issues/1115

### CODE REVIEW

**Comment by mostolog** [comment]
Any idea why it's suse giving errors?

**Comment by rgerhards** [comment]
If you can rebase to current master, the suse problems will go away. If you can't I'll later create a merge PR to get a full testbench run.

**Comment by mostolog** [comment]
If you agree, I could try to regex all .c/.h files to "prettify" the curly braces this way:
Of course, I would've to successfully built before PR.

```
int main () {
    if (foo) {
        foo;
        bar;
    } else {
        foo;
    }
    do {
        bar;
    } while (foo);
}
```

**Comment by mostolog** [comment]
Just issued a new/wide one, closing this

**Pull request closed without merging**
