### PR TITLE
Improvement on ommongodb: mongo-c-driver with TLS and replicaset

### PR DESCRIPTION
**Pull request by jjourdin**
Hello,

We propose improvements on the existing ommongodb output module. The major improvement is the use of the mongo-c-driver library instead of the deprecated mongo-client library.

New features are :

 *   Handle TLS connexion to mongodb
 *  Handle MongoDB Replicasets
 *   Added the 'ssl_ca' and 'ssl_cert' directives to configure tls connexion
 *   Added 'uristr' directive to configure the connexion uri in the form of 'mongodb://...'

Example configuration:
```
action(
     type="ommongodb" 
     uristr="mongodb://vulture:9091,vulture2:9091/?replicaset=Vulture&ssl=true" 
     ssl_cert="/var/db/mongodb/mongod.pem" 
     ssl_ca="/var/db/mongodb/ca.pem" 
     db="logs" 
     collection="syslog")
```
The "uristr" directive overrides the 'uid', 'pwd', 'server' and 'serverport' directives. To create the uri, please refer to the official MongoDB Connection String documentation.

uid, pwd, server and serverport directives are useless now, but still supported in this module, to preserve compatibility with existing configuration.

Feel free to contact us at aDvens if you have any questions: jeremie.jourdin@advens.fr / hugo.soszynski@advens.fr

Regards,

Hugo & Jérémie

### CODE REVIEW

**Comment by rgerhards** [comment]
It would be great if you could also update the doc at https://github.com/rsyslog/rsyslog-doc/blob/master/source/configuration/modules/ommongodb.rst

**Comment by rgerhards** [comment]
> Feel free to contact us at aDvens if you have any question

Do you also watch the github issue or is email required?

**Comment by jjourdin** [comment]
We will update the documentation. If there are any issue feel free to assign to me.

**Comment by rgerhards** [comment]
a rebase to current master will make that current freebsd CI failure go away

**Comment by HugoSoszynski** [comment]
Hello,

After reading the logs of the failed builds on Travis it seems that they failed due to the installation of libmongo-client-dev instead of libmongoc-dev in the build environment: libmongoc being the new dependency needed for ommongodb as specified in the merge request message.

Do we need to make any change or is it up to you to do so ?


Regards,

Hugo.

**Comment by rgerhards** [comment]
> Do we need to make any change or is it up to you to do so ?

You have control over travis. It's probably installed in .travis.yml in the root or here: https://github.com/rsyslog/rsyslog/blob/master/tests/travis/install.sh

**Comment by HugoSoszynski** [comment]
Hello,

As long as the tests are done on Ubuntu 14.04 LTS and the libmongoc-dev package is not available on this version, is it okay to fetch the mongo-c-driver Github repository and compile it for the build ?

I know this solution is not perfect but after some research, it looks like this is a rare case and most distributions now includes the package.


Regards,

Hugo.

**Comment by rgerhards** [comment]
Yeah, it's unfortunately increasingly becoming a problem that the Travis images are too outdated. I'd say let's build the dependency if we do not have a package. We just need to check that we do not do that in too many parallel builds, because of runtime limits in Travis.

**Comment by rgerhards** [comment]
@HugoSoszynski I am also working on getting the ubuntu16 buildbot slave in shape to compile ommongodb. It provides the best clang static analyzer output.

**Comment by HugoSoszynski** [comment]
Hello,

We are currently testing with our Travis. While testing, we have a problem with the libbson embedded with the mongo-c-driver. Libbson is not able to pass its ./configure because it's unable to find the pthread library necessary on non-windows environments.

 - The libpthread-stubs0-dev is installed.
 - The ./configure works without any problem on an Ubuntu 14 VM I use for local testing.
 - The configure.ac and the .m4 associated strictly follow the autotools documentation.
 - I did not found any working solution on Google.

This is becoming kind of a problem.
As rsyslog and some of its plugins uses pthread, I wondered if you had any idea.


Regards.

**Comment by HugoSoszynski** [comment]
Hello,

We finally found that Autotools try to compile C code to check the presence of libpthread, which code generate 4 warnings. The early set of -Werror in the Travis environment would cause the Aututools code not to compile and return that libpthread is not available. We simply deactivated -Werror during the mongo-c-driver compilation and put it back right after.

During our tests on our Travis, only one test failed, this test was about Kafka (https://travis-ci.org/jjourdin/rsyslog/jobs/300122201#L4110).


Regards.

**Comment by rgerhards** [comment]
Thanks! If you would like to have a cleanly looking PR, you can rebase to current master to make CI pass. The kafka guys removed a file that CI needs and we needed to change the file name. It's ugly, but unfortunately the only way to do it currently. I fixed this yesterday (problems began to appear around yesterday noon).

**Comment by HugoSoszynski** [comment]
Hello,

I would like to know if there is a way to access the buildbot logs please.
Clicking on the _Details_ link is not working on my side (just an infinite loading in my browser) and after a check at the contributing doc, I saw nothing about this.


Thank you.

**Comment by rgerhards** [comment]
> I would like to know if there is a way to access the buildbot logs please.

it's running on port 8010 - do you block this?

**Comment by rgerhards** [comment]
I also had a quick look at the CentOS 7 buildbot slave. Libmongoc-dev is missing there too. Trying ```yum install libmongoc-dev libmongoc-devel``` does not bring up a package, nor does yum search. Also missing there? Or can you suggest an install source. I guess same story for Centos 6...

**Comment by HugoSoszynski** [comment]
Thank you, I will soon have access to the buildbot.
The libmongoc-dev is not available in the default repositories, it requires the use of repositories from the Fedora project.
I'm waiting to have a look to the builbot to find a generic solution.

**Comment by rgerhards** [comment]
> The libmongoc-dev is not available in the default repositories, it requires the use of repositories from the Fedora project.

I enabled what is safe to enable on CentOS 7: ```yum --enablerepo=extras install epel-release``` Unfortunately, they do not contain the package. Will look to build manually.

**Comment by rgerhards** [comment]
ok, from source bails out due to missing g++, which I can't find for CentOS 7. So as it looks, we unfortunately cannot even build-test it on CentOS 7. That's a bit of a shame as that platform is frequently used. If you have an idea how to build it without diverging too much from a "save" CentOS base, I am all ears.

**Comment by deoren** [comment]
> @rgerhards: ok, from source bails out due to missing g++, which I can't find for CentOS 7. 

Looks like you need the `gcc-c++` package:

`# yum provides g++`
```
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.wdc1.us.leaseweb.net
 * extras: reflector.westga.edu
 * updates: mirror.jax.hugeserver.com
base/7/x86_64/filelists_db                                                                                                                                                                  | 6.7 MB  00:00:04     
extras/7/x86_64/filelists_db                                                                                                                                                                | 494 kB  00:00:00     
updates/7/x86_64/filelists_db                                                                                                                                                               | 2.1 MB  00:00:00     
gcc-c++-4.8.5-16.el7.x86_64 : C++ support for GCC
Repo        : base
Matched from:
Filename    : /usr/bin/g++
```

**Comment by HugoSoszynski** [comment]
So I looked at the logs from the ubuntu16 build.
ommongodb cannot compile because Ubuntu 16 uses an outdated version of libmongoc: 1.3.1 and we are now at version 1.8.1.
Those versions have a difference in the fields of the mongoc_ssl_opt_t structure. Not compiling because of a scalar initialization of this particular struct.

I will fix the code to work with both versions as long as we do not use this specific field.

**Comment by rgerhards** [comment]
> Looks like you need the gcc-c++ package:

Doh! I thought I had tried that, but... Now it's there. I'll modify the buildbot conf so that Centos7 will also try to build mongodb. Just so that you know should a new error pop up there (oh, the joys of multi-distro development... ;-))

**Comment by rgerhards** [comment]
re-initiated Centos7 build. If it fails, I'll check if I screwed up with my CI updates and will fix that. I'll let you know in any case.

**Comment by HugoSoszynski** [comment]
It looks like the missing lib on Centos7 is libmongo-client, this is not the lib used by ommongodb but it is used for the logctl usertool.

**Comment by rgerhards** [comment]
@HugoSoszynski I think we should not use multiple mongo libraries, that will probably result in a mess. So logctl needs to be updated as well.

**Comment by rgerhards** [comment]
Congrats! Special thanks to @HugoSoszynski for the presistence in driving this forward - much appreciated. I am sure this is a great addition to rsyslog.

**Comment by algernon** [comment]
As rsyslog was the last big user of libmongo-client, thank you @HugoSoszynski for this work! Will make it easier to properly retire the library and eventually drop it from distributions. \o/

**Comment by rgerhards** [comment]
@algernon ... and thanks for developing libmongo-client in the first place! Was much appreciated.

**Pull request merged**
