### PR TITLE
the return value judgment of recv is err in CheckConnecttion

### PR DESCRIPTION
**Pull request by wsp1991**

### CODE REVIEW

**Comment by wsp1991** [comment]
close https://github.com/rsyslog/rsyslog/issues/4227

**Comment by wsp1991** [comment]
> This change looks just plainly wrong. Can you describe why you made it and why it is correct?

the recv（）function RETURN VALUE
       These calls return the number of bytes received, or **-1 if an error occurred.  In the event of an error, errno is set to indicate the error.**

       **When a stream socket peer has performed an orderly shutdown, the return value will be 0 (the traditional "end-of-file" return).**

       Datagram sockets in various domains (e.g., the UNIX and Internet domains) permit zero-length datagrams.  When such a datagram is received, the return value is 0.

       The value 0 may also be returned if the requested number of bytes to receive from a stream socket was 0.

---> so when the return value is 0, the errno is not set. 
> This change looks just plainly wrong. Can you describe why you made it and why it is correct?

**Comment by wsp1991** [comment]
> This change looks just plainly wrong. Can you describe why you made it and why it is correct?
recv() function RETURN VALUE
       These calls return the number of bytes received, or -1 if an error occurred.  In the event of an error, errno is set to indicate the error.

       When a stream socket peer has performed an orderly shutdown, the return value will be 0 (the traditional "end-of-file" return).

       Datagram sockets in various domains (e.g., the UNIX and Internet domains) permit zero-length datagrams.  When such a datagram is received, the return value is 0.

       The value 0 may also be returned if the requested number of bytes to receive from a stream socket was 0.
---> so when the return value is 0, the errno is not set. only the return value is -1,the errno is set.

**Comment by wsp1991** [comment]
> This change looks just plainly wrong. Can you describe why you made it and why it is correct?


>recv()functon RETURN VALUE
       These calls return the number of bytes received, or -1 if an error occurred.  In the event of an error, errno is set to indicate the error.
       When a stream socket peer has performed an orderly shutdown, the return value will be 0 (the traditional "end-of-file" return).
       Datagram sockets in various domains (e.g., the UNIX and Internet domains) permit zero-length datagrams.  When such a datagram is received, the return value is 0.
       The value 0 may also be returned if the requested number of bytes to receive from a stream socket was 0.

---> so when the return value is 0, the errno is not set. only the return value is -1,the errno is set.

**Comment by rgerhards** [comment]
Thx for the clarification on the errno, I had overlooked the part. Sorry for the noise.

I just now need to see how I handle this PR which actually addresses two things. I think we also need to fixup the commit descriptions so that it is clearer what the commit does and why. I will probably create two separate PRs out of this one with the updated commit text.

**Comment by rgerhards** [comment]
@wsp1991 can you comment on why the second commit does what it does? In which situations does the segfault occur?

First commit is now handled by https://github.com/rsyslog/rsyslog/pull/4417

**Comment by rgerhards** [comment]
@wsp1991 I assume you envision a race because iLenProgram name is not guarded by mutex. This could indeed be an issue if the update happens in an related thread. However, I think a better fix for that would be to protect the full sequence with mutex look.

I have replaced the second commit by https://github.com/rsyslog/rsyslog/pull/4418 -- feedback is appreciated.

**Comment by rgerhards** [comment]
"merged" by other PRs mentioned in conversation.

@wsp1991 thx for the PR, as you can see it has been merged, albeit in an unusual way.

**Pull request closed without merging**
