### PR TITLE
omkafka: make maxoutqsize resettable

### PR DESCRIPTION
**Pull request by flisky**
This fixes up #574.

### CODE REVIEW

**Comment by rgerhards** [comment]
@alorbach any concerns re this PR? Looks more like a bugfix for me, but I wonder if there is a hard reason for the current implementation.

**Comment by rgerhards** [comment]
@flisky can you please rebase to current master. That will make CI failure go away, most probably.

**Comment by flisky** [comment]
No lucky, still the same failure - `line too long (121)`.

**Comment by rgerhards** [comment]
ah, I see what goes on. Wonder why it wasn't triggerred before on master. Anyhow. Fix is underway...

**Comment by rgerhards** [comment]
@flisky I would appreciate if you could rebase once again. This should finally solve the issue. There actually was a CI bug in master -- sorry for that.

**Pull request merged**
