### PR TITLE
Fixing issue #1267: allow lmsig_ksi to configure file persmissions

### PR DESCRIPTION
**Pull request by allanpark**
Enabling lmsig_ksi module to use the same file permissions as omfile. Tested manually.

### CODE REVIEW

**Comment by rgerhards** [comment]
If I read correctly, you can use different  permissions for the KSI files and the log files. I assume this is intentional (makes sense to me)?

**Comment by allanpark** [comment]
Yes, this is intentional.

**Comment by rgerhards** [comment]
Note: the debian failure is unrelated and present as the PR code is not rebased to latest master branch.

**Comment by rgerhards** [comment]
It would be good if you could also update the rsyslog-doc project, so that the new features are actually known.

**Pull request merged**
