### PR TITLE
Escape \ for JSON_ESCAPE

### LINKED ISSUE #1126: Backslash (\) character is not properly escaped
It seems that the "\" character is not properly escaped when option.json="on" is used.

version used: rsyslogd 8.18.0

Configuration file:
```
template(name="template_test" type="list" option.json="on") {
        constant(value="{")
        constant(value="\"@timestamp\":\"")       property(name="timereported" dateFormat="rfc3339")
        constant(value="\",\"@src_event\":\"")    property(name="hostname")
        constant(value="\",\"@severity\":\"")     property(name="syslogseverity-text")
        constant(value="\",\"@facility\":\"")     property(name="syslogfacility-text")
        constant(value="\",\"@program\":\"")      property(name="programname")
        constant(value="\",\"message\":\"")       property(name="msg")
        constant(value="\"}")
}
```

**Message received:**
`<164>Aug 22 2016 09:30:52: %ASA: Deny udp src Internet:1.2.3.4/100(LOCAL\user) dst WAN:5.5.5.5/100 by access-group "access-group"
`

**After handling:**
```
{"@timestamp":"2016-08-22T09:30:52+02:00",
"@src_event":"src-asa.domain.lan",
"@severity":"warning",
"@facility":"local4",
"@program":"%ASA",
"message":" Deny udp src Internet:1.2.3.4/100(LOCAL\user) dst WAN:5.5.5.5/100 by access-group \"access-group\"
"}
```

The above message generates a "_jsonparsefailure" raised by logstash.
Let me know if there is a way to escape the "\" by increasing the template.

Thank you

### PR DESCRIPTION
**Pull request by mostolog**
I think this could be enough to fix #1126

### CODE REVIEW

**Comment by mostolog** [comment]
Ok about comment...but how to change committer mail?

**Comment by rgerhards** [comment]
```git commit --amend --author "Your name <yourname@example.com>"```

**Comment by rgerhards** [comment]
also, can you please squash the commits: ```git rebase -i HEAD~3```, follow instructions given by git. HEAD~3 is for current state. To push again, you need to ```git push -f repo your-branch``` after rewriting history (rebase or ammend).

**Comment by mostolog** [comment]
Done. 
This are -probably- the most dirty/messy commits ever...but that's the way to learn!!!

**Comment by rgerhards** [comment]
the merge commit should also be squashed

**Comment by mostolog** [comment]
I think this is getting worse...as did before: may i close this PR and create a new/clean one?

**Comment by rgerhards** [comment]
I would recommend to go through the learning cycle on how to squash. The reason is that it is not very good to close and re-open PRs, as they are usually a collaborative effort where ideas and suggestions are exchanged, so it is IMHO unfriendly and unhelpful to thrash those discussions by closing an old PR. Squashing is very easy once you are used to it. Agreed, with this PR not much would be lost by closing, but I hearthly suggest to use it as a testbed for understanding how all of this works. I'll see that I dig out a guide on how to do it. You are obviously interested in improving ever and ever, and this is a good chance to. I know I was also hesitant about squashing when I didn't know how to work with it, so I can feel your pain. I laughed at myself once I went through the process, it is so damn easy you don't believe it :-)

**Comment by rgerhards** [comment]
some helpful links:

This one is a quick and somewhat dirty, but works if you want to squash all commits into one.
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
It actually works for all other kinds of things (same procedure), but it doesn't explain all you need to know. For that, have a look at:
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
**It is well worth reading this chapter and I strongly suggest to do so.** I would also recommend to play a bit with it in a (local) test branch. Understanding this makes your life very, very easy.
HTH

**Comment by mostolog** [comment]
@rgerhards Did I finally made it correctly?

**Comment by rgerhards** [comment]
@mostolog congrats, this looks very nice. I've seen a CI failure, but that seems to be related to a different issue. I have restarted the testrun in question.

**Comment by rgerhards** [comment]
will merge via #1223, adding testbench test
@mostolog I just now (too late) noticed that the commitor (author) name was incorrectly set. That's now how it is ;-)

**Comment by rgerhards** [comment]
just FYI: this would have been automatically closed once #1223 has been merged, because #1223 contains your commits, and github is smart enough to know that a PR has been merged when the commits appear.

So for all others: this is indeed merged and included in 8.23.0. :-)

**Pull request closed without merging**
