### PR TITLE
Allow cross-compiling by using AC_COMPILE_IFELSE

### PR DESCRIPTION
**Pull request by jer-gentoo**

### CODE REVIEW

**Comment by jer-gentoo** [comment]
Perhaps AC_LINK_IFELSE works better in some cases?

**Comment by rgerhards** [comment]
This unfortunately looks like it does not work...

**Comment by jer-gentoo** [comment]
What makes you say that?

**Comment by rgerhards** [comment]
> What makes you say that?

The failed CI tests ;-)

**Comment by jer-gentoo** [comment]
Which one of those are related directly to this patch? I see a missing symbol in imrelp, and there is some weird stuff on Solaris probably attributable to choosing AC_COMPILE_IFELSE instead of AC_LINK_IFELSE (as noted above - does Solaris need a specific library to implement atomic operations?).

**Comment by rgerhards** [comment]
Sorry, I forgot to restart the debian buildbot slave. This one had a problem. Other than that, I am not an autotools expert. All I know that without the patch, everything passes CI, with it, that's not the case. So we need someone who makes it CI-clean again in order to accept the patch.

**Comment by jer-gentoo** [comment]
It is not apparent what further contributions you require. Closing the PR makes it less visible to people who might work on the Solaris problem.

**Comment by rgerhards** [comment]
@davidelang what do you think?

**Pull request closed without merging**
