### PR TITLE
Issue #3343: signed and unsigned comparison

### PR DESCRIPTION
**Pull request by dattann**

### CODE REVIEW

**Comment by dattann** [comment]
Issue #3343: signed and unsigned comparison

**Comment by rgerhards** [comment]
Thx for the PR. I think CI failure is due to unrelated CI instability. I will investigate.

**Comment by rgerhards** [comment]
@dattann just out of interest: was there a specific reason to remove your contribution?

**Comment by dattann** [comment]
Sorry, I closed the PR unintentionally, please merge to rsyslog:master.

**Comment by rgerhards** [comment]
thx! Again, I'll handle CI issues. I just stopped a couple of workers as I am currently changing their plubming. Nothing that concerns you.

**Comment by rgerhards** [comment]
gcc8 check was created after PR, it's not necessary to pass for this PR.

**Comment by rgerhards** [comment]
thx again for the PR, now merged!

**Pull request merged**
