### PR TITLE
Introduce --enable-libcap-ng configure option

### PR DESCRIPTION
**Pull request by Cropi**
For more details, see https://github.com/rsyslog/rsyslog/issues/4986

What I am not sure about is where to place the ```libcap-ng``` related functions. So if you have a better idea on that, do not hesitate to share it with me.

### CODE REVIEW

**Comment by Cropi** [comment]
The PR is ready for review. From code point of view, the proposed feature consists of two main parts.
### 1.Specify which caps are needed for rsyslog to function properly
After some digging in the code, I came up with the following list:
- CAP_BLOCK_SUSPEND: use of ```epoll()```
- CAP_CHOWN: use of ```chown()```
- CAP_IPC_LOCK: use of ```mmap()```
- CAP_LEASE: Establish leases on arbitrary files using ```fcntl()```
- CAP_NET_ADMIN: use of ```setsockopt()```
- CAP_NET_BIND_SERVICE: ports below 1024 are used
- CAP_PERFMON: use of ```syscall()```
- CAP_SETGID: use of setgid()
- CAP_SETUID: use of setuid()
- CAP_SYS_ADMIN: exceed /proc/sys/fs/file-max, the system-wide limit on the number of open files, in system calls that open files (e.g. accept execve), use of setns(),...
- CAP_SYS_CHROOT: use of ```chroot()```
- CAP_SYS_RESOURCE: use of ```setrlimit()```
- CAP_SYSLOG: use of ```syslog()```

### 2. Change UID and GID while retaining previously specified capabilities
Some might want to drop privileges by impersonating as another user and/or group after startup. In order to preserve defined caps, we need to let the system know. That is the reason why ```doDropPrivGid()``` and ```doDropPrivUid()``` functions had to be altered a little bit. Default behavior is preserved, the change occurs when ```ENABLE_LIBCAPNG``` is defined.

**Comment by rgerhards** [comment]
Thanks for the PR. Please note that due to magnitude of the change, we will only merge it after the 8.2212.0 scheduled stable has been released. We do not want to generate some bad surprises during the holiday period. Hope that is fine with you ;-)

I'll nevertheless do code review in the mean time.

**Comment by Cropi** [comment]
> Thanks for the PR. Please note that due to magnitude of the change, we will only merge it after the 8.2212.0 scheduled stable has been released. We do not want to generate some bad surprises during the holiday period. Hope that is fine with you ;-)
> 
> I'll nevertheless do code review in the mean time.

Thank you for the heads up, I am totally fine with that :) No need to rush

**Comment by Cropi** [comment]
Update to the capability list: I do think it makes sense to add the CAP_DAC_OVERRIDE capability if privileges are not dropped. 
```
CAP_DAC_OVERRIDE: Bypass file read, write, and execute permission checks.  (DAC is an abbreviation of "discretionary access control".)
```

Use case: without this capability rsyslog would not be able to read from/write to logs if file permissions are not right, even if it's running as root.

**Comment by mbiebl** [comment]
This broke `make check` when run as regular user.
Will file a separate bug report

**Comment by theodoresi** [comment]
Hi @Cropi , I found that I can't run rsyslog as a non-root user like I used to. I asked the question on stackexchange, and it seems it is related to this code?
https://unix.stackexchange.com/questions/747224/unable-to-run-rsyslogd-as-non-root-user-on-centos-stream-9

**Pull request merged**
