### PR TITLE
queue: fixes issue when DiscardMark reached

### PR DESCRIPTION
**Pull request by phelanx**
When DiscardMark is configured for a queue and DiskcardMark elements inserted it is possible for lower priority items to not be discarded. This causes lower priority items to become "stuck" in the queue. This updates the element state to DISCARDED if the queue is full and will delete them because they _have_ been processed.

--author "anonymous <gdpr@example.com>"

### CODE REVIEW

**Comment by rgerhards** [comment]
> --author "anonymous [gdpr@example.com](mailto:gdpr@example.com)"

pls clarify if you would like to rewrite this as anonymous -- currently your user name is inside the commit. thx

**Comment by phelanx** [comment]
> > --author "anonymous [gdpr@example.com](mailto:gdpr@example.com)"
> 
> pls clarify if you would like to rewrite this as anonymous -- currently your user name is inside the commit. thx

Thank you for asking. I am not overly concerned about it.

**Comment by rgerhards** [comment]
> Thank you for asking. I am not overly concerned about it.

So we can keep it as-is? I ask because you specifically mention that in the initial description.

**Comment by rgerhards** [comment]
side-note CI TSAN worker is currently always failing. Working on introducing it as a new test. Any false positives I'll solve. I'll let you know if real issues are left.

**Comment by phelanx** [comment]
> > Thank you for asking. I am not overly concerned about it.
> 
> So we can keep it as-is? I ask because you specifically mention that in the initial description.

Yes, it is fine to keep it as-is. You'll have to excuse my igorance in this case.

**Comment by rgerhards** [comment]
looks like this causes quite some regressions - pls fix

**Comment by rgerhards** [comment]
@phelanx any interest in finishing this?

**Comment by phelanx** [comment]
I am interested, but have not hand the bandwidth for quite some time. If
someone else has the spare cycles, then there are certainly no hard
feelings if it isn't me who finishes this.

Am So., 10. Nov. 2019 um 06:34 Uhr schrieb Rainer Gerhards <
notifications@github.com>:

**Pull request closed without merging**
