### PR TITLE
fix failpath on actionTryRemoveHardErrorsFromBatch

### PR DESCRIPTION
**Pull request by kortemik**
fixes failpath on actionTryRemoveHardErrorsFromBatch happens only when

actionCommit () 
-> actionTryCommit => FAIL
-> actionCommit somewhat unhappy 
-> actionTryRemoveHardErrorsFromBatch() // contains memcpy which did work with non allocated area and non-element size alligned copy
-> actionCommit unhappy, has still uncommited messages.
-> actionTryCommit // would pass the rogue memory range to module

### CODE REVIEW

**Comment by kortemik** [comment]
@rgerhards  i really hope it's finally now ok, but shouldn't we add also CHKiRet on the call to actionTryRemoveHardErrorsFromBatch to handle the possible oom case as well? I think the oom case might be actually relevant at this point.

**Comment by rgerhards** [comment]
more later but in case you did not see the announcement on twitter: I am working on tumbleweed CI worker, it probably errs out invalidly.

**Comment by kortemik** [comment]
I need to subscribe you on twitter!

**Comment by kortemik** [comment]
well seems like it needs a bit more work around itself

**Pull request closed without merging**
