### PR TITLE
omkafka - use rd_kafka_purge to drain librdkafka queues during HUP and improve kafka instance visibility.

### PR DESCRIPTION
**Pull request by n2yen**
- For librdkafka > v1.x, utilize new api [rd_kafka_purge](https://docs.confluent.io/5.5.1/clients/librdkafka/rdkafka_8h.html#a59c28026ebf7a67df5954879ebab4707) in order to drain librdkafka queues before an instance shutdown, and save it for re-shipping. Useful in order to ensure all logs are shipped even during situations where rsyslog instance must be shut down, such as in during a HUP or restart.

- add statsname on per kafka instance basis to gain minimal visibility of `acks`, `submits`, and `failures` (for that instance).

### CODE REVIEW

**Review by alorbach — APPROVED** [review]
Looks good to me (Y), go ahead.

**Comment by n2yen** [comment]
hi @rgerhards , @alorbach , 
included "errors_ssl" error metric into this PR. not sure, if it would be best to open another PR for it. Please let me know if that would be preferable.

**Comment by alorbach** [comment]
> hi @rgerhards , @alorbach ,
> included "errors_ssl" error metric into this PR. not sure, if it would be best to open another PR for it. Please let me know if that would be preferable.

It's ok to amend it to this PR, it fits the same topic.

**Comment by rgerhards** [comment]
> included "errors_ssl" error metric into this PR. not sure, if it would be best to open another PR for it. Please let me know if that would be preferable.

sounds OK to me, but let me know when you are really done ;-)

Please also remember to update the doc.

**Comment by n2yen** [comment]
> > included "errors_ssl" error metric into this PR. not sure, if it would be best to open another PR for it. Please let me know if that would be preferable.
> 
> sounds OK to me, but let me know when you are really done ;-)
> 
> Please also remember to update the doc.

yes, just squashed the 2 commits together and that should be it. will update the docs as well.

**Comment by n2yen** [comment]
reference doc PR: https://github.com/rsyslog/rsyslog-doc/pull/933

**Review by rgerhards — APPROVED** [review]

**Pull request merged**
