### PR TITLE
Fix broken 'debugless' build.

### PR DESCRIPTION
**Pull request by mrworkman**
It seems that using the `--enable-debugless` configure option results in a broken build:

    $ make
    make  all-recursive
    make[1]: Entering directory './rsyslog'
    Making all in compat
    make[2]: Entering directory './rsyslog/compat'
      CC       compat_la-getifaddrs.lo
      CC       compat_la-strndup.lo
      CC       compat_la-solaris_elf_fix.lo
      CCLD     compat.la
    ar: `u' modifier ignored since `D' is the default (see `U')
    make[2]: Leaving directory './rsyslog/compat'
    Making all in runtime
    make[2]: Entering directory './rsyslog/runtime'
      CC       librsyslog_la-rsyslog.lo
    rsyslog.c: In function ‘rsrtInit’:
    rsyslog.c:211:2: error: implicit declaration of function ‘dbgprintf’ [-Werror=implicit-function-declaration]
      dbgprintf("rsyslog runtime initialized, version %s, current users %d\n", VERSION, iRefCount);
      ^
    cc1: some warnings being treated as errors
    Makefile:1161: recipe for target 'librsyslog_la-rsyslog.lo' failed
    make[2]: *** [librsyslog_la-rsyslog.lo] Error 1
    make[2]: Leaving directory './rsyslog/runtime'
    Makefile:818: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory './rsyslog'
    Makefile:645: recipe for target 'all' failed
    make: *** [all] Error 2

I made the necessary changes to address this, and thought I'd share.

This request replaces PR #1745 (now closed) which required too many changes to existing rsyslog code. This one's a lot less invasive.

### CODE REVIEW

**Comment by mrworkman** [comment]
Not sure why that one test I added keeps failing.... investigating.

**Comment by mrworkman** [comment]
The one Travis test I added that was failing is now passing. Not sure what's up with the FreeBSD build as I can't see its output, but it was working earlier (stopped working a after I updated the Travis config which is not even related as far as I can tell). 

There's another Travis build that seems to fail sometimes (it happened one or two builds ago, then passed after that) due to a memory issue. Betting it will "pass" if made to run again. I don't *think* the changes I made could lead to memory issues like that..

**Comment by rgerhards** [comment]
Hi, can you please squash the commits into one?

**Comment by mrworkman** [comment]
Done.

**Comment by rgerhards** [comment]
fixes regression introduced in v8.29.0

**Pull request merged**
