### PR TITLE
testbench: disable omprog-transactions-failed-messages.sh on solaris

### PR DESCRIPTION
**Pull request by rgerhards**
test consistently fails

see also https://github.com/rsyslog/rsyslog/issues/2403

### CODE REVIEW

**Comment by jsiwrk** [comment]
@rgerhards : in [this conversation](https://github.com/rsyslog/rsyslog/pull/1992#issuecomment-377002520), the test that failed was `omprog-transactions-failed-commits.sh`, as can be seen in the [log](http://build.rsyslog.com:8010/builders/rsyslog%20solaris11x64%20rsyslog/builds/2151/steps/shell_8/logs/stdio) you provided. However, you have disabled `omprog-transactions-failed-messages.sh`, which is a different test that is not affected by #2356. Does this test fail also, then? Do you have some failure logs so I can try to figure out the reason? If the test has a sync issue, I can try to resolve it along with #2403.

**Comment by rgerhards** [comment]
Error on my part! 

Thx for all your great work?

**Comment by jsiwrk** [comment]
OK, I can re-enable this test (and disable the other) myself in my next PR if you prefer, since I'm reviewing the omprog tests.

**Comment by rgerhards** [comment]
@jsiwrk please do - been tied up with the release (and the looong German easter weekend ;-)). Your help is really appreciated!

**Pull request merged**
