### PR TITLE
omprog: adapt test to testbench improvements

### PR DESCRIPTION
**Pull request by jsiwrk**
Adapt one of the omprog tests to the latest improvements in the
testbench framework, for consistency with other similar tests. The test
behaviour has not changed.

Add some temporary files created by the testbench to gitignore file.

### CODE REVIEW

**Comment by rgerhards** [comment]
@jsiwrk I'll merge this with the next stable release. The fix is already in.

Could you pls have a look at the Coday report -- these should be very easy to fix.

**Comment by jsiwrk** [comment]
Fixed codacy warnings and rebased to master.

**Comment by jsiwrk** [comment]
The CI failures of the `omprog-output-capture-mt` test are not related to this PR, but to a bug in omprog introduced in v8.2004. I have just submitted PR #4261 to fix this.

**Comment by rgerhards** [comment]
thx again for the PR!

**Pull request merged**
