### PR TITLE
Set mmpstrucdata jsonRoot default ("rfc5424-sd") and honor configuration parameter values

### PR DESCRIPTION
**Pull request by mostolog**
Closes https://github.com/rsyslog/rsyslog/issues/1262

### CODE REVIEW

**Comment by mostolog** [comment]
@rgerhards why mmpstrucdata is using uchar, while mmnormalize char?

**Comment by rgerhards** [comment]
We try to use uchar normally, in order to avoid problems with sign extension. However, if this becomes clumpsy (e.g. to many lib-calls with char) we tend to use char to not do sooo many casts. I think liblognorm uses char, because that's more generic (for non-rsyslog callers) and so this was the reason.

**Comment by mostolog** [comment]
@rgerhards Could you relaunch tests? I think this patch + yesterday's github issues made this tests go crazy. Thanks

**Comment by rgerhards** [comment]
could you do
```
$ git checkout <your-branch>
$ git commit --ammend
..no change..
$ git push -f <your branch>
```
This will trigger a new CI run. Otherwise I need to go into each of the systems individually.
Thanks!

**Comment by rgerhards** [comment]
I have manually restarted the travis run, let's see how it works before doing more manual work.

**Comment by rgerhards** [comment]
The travis failures are real ones.

**Comment by mostolog** [comment]
@rgerhards I'm confused: It's a code issue or a testing issue?

**Comment by rgerhards** [comment]
@mostolog looks like a code issue to me, as the test without the change works. have you run the test in your environment and did it work? You can do this quickly with ```make check TESTS="my_test.sh"```.

**Comment by mostolog** [comment]
I didn't make any tests, just compiled.

make check TESTS="mmpstrucdata.sh" fails with:
```
rsyslogd: could not load module '../plugins/imdiag/.libs/imdiag.so', dlopen: ../plugins/imdiag/.libs/imdiag.so: cannot open shared object file: No such file or directory  [v8.23.0 try http://www.rsyslog.com/e/2066 ]
rsyslogd: invalid or yet-unknown config file command 'IMDiagServerRun' - have you forgotten to load a module? [v8.23.0 try http://www.rsyslog.com/e/3003 ]
rsyslogd started with pid  16786
./diag.sh: line 326: ./tcpflood: No such file or directory
error during tcpflood! see rsyslog.out.log.save for what was written
cp: cannot stat 'rsyslog.out.log': No such file or directory
FAIL mmpstrucdata.sh (exit status: 1)
```

tried building tcpflood diagtalker msleep chkseq but other problems appear:
```
rsyslogd started with pid  29477
starting run 1
Sending 100 messages.
00000100 messages sent
runtime: 0.000
End of tcpflood Run
imdiag[13500]: mainqueue empty
scanf error in index i=0
sequence error detected
FAIL mmpstrucdata.sh (exit status: 1)
```

I could revert+compile+test to confirm it's a code issue (probably, but I don't understand why)

**Comment by rgerhards** [comment]
As general advise, without test development can never be thought of being completed ;-) Without testing, about 40% of my "trivial changes" turn out to be invalid.

To the failure you got under make check. It looks like configure is missing a dependency test. We need ```--enable-imdiag``` in order to do basic testing. So you need to add this to ./configure options.

You do not need to revert your change. You can simply do a local checkout of the last git commit (hash) before your change and then run make check on that code. If you need help with that, email my privately. I'll talk you through.

**Comment by mostolog** [comment]
The following snippet shows one place where I have found issues

```
static inline void
setInstParamDefaults(instanceData *pData)
{
        //was
        //pData->jsonRoot = NULL;
        //changed to (it works)
        pData->jsonRoot = (uchar*) strdup("!");
        //it fails with
        //pData->jsonRoot = (uchar*) strdup("rfc5424-sd");
        //should it use CHK?
        //CHKmalloc(pData->jsonRoot = (uchar*) strdup("rfc5424-sd"));
}
```

I have tried to printf/debug which messages are being processed, but I'm not able to figure if this is a "comparing to expected result" error or what. Any hint?

**Comment by rgerhards** [comment]
OK, I'll use this PR as a starting point to improve the testbench doc for contributors. So that you can interpret testbench failures better.

**Pull request closed without merging**
