### PR TITLE
testbench: Fix libefaketime regression

### PR DESCRIPTION
**Pull request by Whissi**
My proposal from https://github.com/rsyslog/rsyslog/issues/992 which uses `find` to keep using `LD_PRELOAD`.

### CODE REVIEW

**Comment by Whissi** [comment]
Re-pushed to fix typo in commit msg.

**Comment by rgerhards** [comment]
Unfortunately, this still does not work. If you look at the CI results, you'll notice that libfaketime is not found.

**Comment by rgerhards** [comment]
maybe we should temporarily revert https://github.com/rsyslog/rsyslog/pull/965 until we find a final solution?

**Comment by Whissi** [comment]
I tested Debian Jessie and CentOS 7 with system packages and my git branch detected libfaketime. Where do I find the build bot configuration? I need to know how the build env does install *libfaketime*.

**Comment by rgerhards** [comment]
The current buildbot machines, except Fedora, were manually installed. Fedora install script is here:

https://github.com/rgerhards/buildbotsetup/blob/master/fedora/system_setup.sh

in general, we did a
```
$ apt-get install faketime
$ yum install faketime
```
and so on. So everything is distro standard (package names vary between distros). 

The buildbot conf is not yet online as it contains some sensitive information. But it simply uses what is installed.

**Comment by rgerhards** [comment]
just a side-note: the detection also fails on travis (just saw that), this may be easier to debug as you can modify the whole system config

**Comment by Whissi** [comment]
Yup, currently running `find / -name 'libfaketim*' -type f` on all platforms to learn more about the different locations. I expect that the problem is that the test only looks into `/usr/lib` which isn't a symlink on all platforms.

**Comment by Whissi** [comment]
Results:

| OS | Result |
| ---- | --------- |
| Travis GCC | Passed, [libfaketime detected](https://s3.amazonaws.com/archive.travis-ci.org/jobs/127234233/log.txt) |
| Travis CLANG | Passed, [`/usr/lib/faketime/libfaketime.so.1` detected](https://s3.amazonaws.com/archive.travis-ci.org/jobs/127234234/log.txt) |
| CentOS6 | Skipped, [no libfaketim* on the system](http://build.rsyslog.com:8010/builders/rsyslog centos6 rsyslog/builds/484/steps/shell_3/logs/stdio) !
| CentOS7 | Skipped at the moment [but found in `/usr/lib64/faketime/libfaktetime.so.1`](http://build.rsyslog.com:8010/builders/rsyslog centos7 rsyslog/builds/440/steps/shell_3/logs/test-suite.log) |
| Debian | Skipped, [no libfaketim* on the system](http://build.rsyslog.com:8010/builders/rsyslog debian rsyslog/builds/496/steps/shell_4/logs/test-suite.log) |
| Fedora23x32 | Passed, [libfaketime detected](http://build.rsyslog.com:8010/builders/rsyslog fedora23x32 rsyslog/builds/205/steps/shell_3/logs/stdio) |
| Fedora23x64 | Skipped at the moment [but found in `/usr/lib64/faketime/libfaketime.so.1`](http://build.rsyslog.com:8010/builders/rsyslog fedora23x64 rsyslog/builds/189/steps/shell_3/logs/test-suite.log) |
| FreeBSD | Testsuite won't be called |
| OpenSUSE | Skipped, [no libfaketim* on the system](http://build.rsyslog.com:8010/builders/rsyslog suse rsyslog/builds/488/steps/shell_3/logs/test-suite.log) |
| Ubuntu | Passed, [libfaketime detected](http://build.rsyslog.com:8010/builders/rsyslog ubuntu rsyslog/builds/482/steps/shell_4/logs/stdio) |


I'll update the find call to look in `/usr/lib64` first and fall back to `/usr/lib`. This will fix CentOS7 and Fedora23x64.
Debian and OpenSUSE need another package (libfaketime instead of just faketime).

Not sure about CentOS6, which repository are you using for CentOS?

**Comment by rgerhards** [comment]
CentOS 6 unfortunately does not have libfaketime. We use the centos repos plus EPEL.

**Comment by Whissi** [comment]
Oh, interesting (unrelated) Debian failure: *FAIL: queue-persist.sh*

The updated PR fixes detection for CentOS7 and Fedora. As said, Debian and OpenSUSE build bots need *libfaketime*. Not sure what we do with CentOS6... I don't find any official _\*faket\*_ package at all (and for me it looks like *libfaketime* [first appeared in CentOS7](https://bugzilla.redhat.com/show_bug.cgi?id=1018626)).

**Comment by rgerhards** [comment]
The unrelated issue is indeed unrelated and something I am working on. It looks a recent package update introduced this. It probably is related to parallel builds, but I really don't know yet.

I'll install the missing packages.

For Centos6, I think there is nothing reasonable we can do. IMHO this simply is a platform where we need to skip the tests (after all, that's why we have this capability).

Thanks for your continous help!

**Comment by rgerhards** [comment]
The old OpenSuse 13.1 version also seems not to have [lib]faketime. So be it... We'll revamp those old build slaves within the next couple of weeks anyhow.

**Comment by rgerhards** [comment]
merged via #1004

**Pull request closed without merging**
