### PR TITLE
improve resilience of dynstats_overflow-vg.sh

### PR DESCRIPTION
**Pull request by janmejay**
towards: https://github.com/rsyslog/rsyslog/issues/786

### CODE REVIEW

**Comment by janmejay** [comment]
I haven't bumped time yet, have tried to just sync stats-flush window. I may need to bump time too.

**Comment by rgerhards** [comment]
I'd say let's see how this works over the next couple of days and then we can look further...

**Comment by rgerhards** [comment]
btw: something with travis seems to be fishy, I have no idea why it does not start a CI build right now.

**Comment by janmejay** [comment]
It was actually a bug in the test. I wanted to synchronize with purge of
bucket and ended up synchronizing with reporting of stats. Have fixed it in
the PR.

On Sun, Feb 21, 2016 at 12:48 AM, Rainer Gerhards <notifications@github.com>
wrote:

> btw: something with travis seems to be fishy, I have no idea why it does
> not start a CI build right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/pull/816#issuecomment-186668377>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment]
I have looked at the other tests that wait for first stats reporting cycle
to run and none of them are confusing the two situations, so this(and its
non-vg counterpart) as the only ones that had this bug.

On Sun, Feb 21, 2016 at 12:54 AM, singh.janmejay <singh.janmejay@gmail.com>
wrote:

> It was actually a bug in the test. I wanted to synchronize with purge of
> bucket and ended up synchronizing with reporting of stats. Have fixed it in
> the PR.
>
> On Sun, Feb 21, 2016 at 12:48 AM, Rainer Gerhards <
> notifications@github.com> wrote:
>
>> btw: something with travis seems to be fishy, I have no idea why it does
>> not start a CI build right now.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rsyslog/rsyslog/pull/816#issuecomment-186668377>.
>>
>
>
>
> --
> Regards,
> Janmejay
> http://codehunk.wordpress.com
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment]
I did some 30 runs using loop.sh which came out green.

**Comment by janmejay** [comment]
BTW, this one had a good travis run.

On Sun, Feb 21, 2016 at 1:00 AM, singh.janmejay <singh.janmejay@gmail.com>
wrote:

> I have looked at the other tests that wait for first stats reporting cycle
> to run and none of them are confusing the two situations, so this(and its
> non-vg counterpart) as the only ones that had this bug.
>
> On Sun, Feb 21, 2016 at 12:54 AM, singh.janmejay <singh.janmejay@gmail.com
> > wrote:
>
>> It was actually a bug in the test. I wanted to synchronize with purge of
>> bucket and ended up synchronizing with reporting of stats. Have fixed it in
>> the PR.
>>
>> On Sun, Feb 21, 2016 at 12:48 AM, Rainer Gerhards <
>> notifications@github.com> wrote:
>>
>>> btw: something with travis seems to be fishy, I have no idea why it does
>>> not start a CI build right now.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/rsyslog/rsyslog/pull/816#issuecomment-186668377>.
>>>
>>
>>
>>
>> --
>> Regards,
>> Janmejay
>> http://codehunk.wordpress.com
>>
>
>
>
> --
> Regards,
> Janmejay
> http://codehunk.wordpress.com
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
FYI: I get the most problems on buildbot runs. I think these are the slowest machines, so they are most timing-affected.

**Comment by janmejay** [comment]
Is it still unstable on buildbot? If it is then I'll work on a timing
oblivious way to test it.

But then it won't really be testing 100% production flow. I'll have to use
imdiag hooks which will pollute testing of production code path.

Should we try bumping time further up? Doubling it for every failure until
we see no more failures?

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by rgerhards** [comment]
2016-02-21 11:10 GMT+01:00 Janmejay Singh <notifications@github.com>:

> Is it still unstable on buildbot?


I don't know yet, the first build is right now being tried. Give me a
couple of days, I'll report if problems come up.

Rainer

**Comment by rgerhards** [comment]
just FYI: I now sometime get valgrind reports like this:

http://build.rsyslog.com:8010/builders/rsyslog%20ubuntu%20rsyslog/builds/263/steps/shell_3/logs/stdio

This points into pretty generic code and looks a lot like we have some problems doing a timely shutdown. It is also noticable that it seems to happen only with the valgrind test (which is also slower). So far, happened only on the slowest buildbot slaves.

**Comment by janmejay** [comment]
deinitAll doesn't seem to join threads when it kills them. It
calls thrdTerminateAll on threads linked-list, but doesn't join them. I
don't know why it doesn't show up in other valgrind tests though.

I came across this report:
https://sourceware.org/bugzilla/show_bug.cgi?id=3087 which seems to
indicate it was a very old version of libc. Are we running this version?


On Mon, Feb 22, 2016 at 7:59 PM, Rainer Gerhards <notifications@github.com>
wrote:

> just FYI: I now sometime get valgrind reports like this:
>
>
> http://build.rsyslog.com:8010/builders/rsyslog%20ubuntu%20rsyslog/builds/263/steps/shell_3/logs/stdio
>
> This points into pretty generic code and looks a lot like we have some
> problems doing a timely shutdown. It is also noticable that it seems to
> happen only with the valgrind test (which is also slower). So far, happened
> only on the slowest buildbot slaves.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/pull/816#issuecomment-187204182>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
on libc: some platforms may be running it, we never can outrule that. But I think it makes sense to check thrdTerminateAll, maybe there really is a race. On the other hand, I am sure there was a reason for not joining...

**Pull request merged**
