### PR TITLE
Accept leading underscores for variable names

### LINKED ISSUE #603: Unable to reference leading underscore variables created off root message property
If I have:
```
# cat /etc/rsyslog.conf.test
set $!this = $!foo;
set $!that = $!_bar;
```

Then when I try to parse this configuration I receive the following error with 8.14.0:
```
# /usr/sbin/rsyslogd -N1 -f /etc/rsyslog.conf.test
rsyslogd: version 8.14.0, config validation run (level 1), master config /etc/rsyslog.conf.test
rsyslogd: error during parsing file /etc/rsyslog.conf.test, on or before line 2: invalid character '$' in expression - is there an invalid escape sequence somewhere? [v8.14.0 try http://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /etc/rsyslog.conf.test, on or before line 2: invalid character '!' in expression - is there an invalid escape sequence somewhere? [v8.14.0 try http://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /etc/rsyslog.conf.test, on or before line 2: invalid character '_' in expression - is there an invalid escape sequence somewhere? [v8.14.0 try http://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /etc/rsyslog.conf.test, on or before line 2: syntax error on token ';' [v8.14.0 try http://www.rsyslog.com/e/2207 ]
rsyslogd: CONFIG ERROR: could not interpret master config file '/etc/rsyslog.conf.test'. [v8.14.0 try http://www.rsyslog.com/e/2207 ]
```

If I change `$!_bar` on line 2 to be `$!bar` it works, and will work if I change it to `$!then!_bar`.

Unfortunately, the `imjournal` module uses the exact names of trusted variables defined at [systemd.journal-fields](http://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html), which all have leading underscores.

Is this expected behavior?

### PR DESCRIPTION
**Pull request by portante**
The grammar now allows for leading underscores for variable names. This
addresses a problem stemming from the fact that the imjournal module
will create variables using the given name from systemd. All "trusted"
variables in systemd begin with a leading underscore.

Fixes #603.

### CODE REVIEW

**Comment by portante** [comment]
That looks like a sporadic failure of sorts.  Let me know if I have misunderstood the failure mode, and I'll try to address it further.

**Comment by portante** [comment]
This also seems to fix #481 as well, @davidelang.

**Comment by portante** [comment]
@theinric, this is one I'd like us to track closely.

**Comment by rgerhards** [comment]
This addresses character case handling, merge with care after very careful review.Maybe we should cherry-pick the patch for leading underscores.

**Comment by portante** [comment]
@rgerhards, definitely feel free to cherry-pick, which is why I did not collapse this into one patch.

The leading underscores is a problem unto itself, but I added the second patch for the mixed case references because my use case for the leading underscores is `imjournal`, which uses uppercase names, and I still can't reference the names without them.

FWIW, I have successfully deployed these two patches on the 8.14 code branch, and they work great.

**Comment by portante** [comment]
@rgerhards, I further broke this fix out so that you can see that the only change that appears to be necessary is where we stop lowercasing variable name references from templates.

This is a bug today, as one cannot reference uppercase variable names, even though the parser is allowing them.

I am going to add a switch to turn this on as an opt-in.

**Comment by portante** [comment]
Okay, so this PR has three patches in it:

1. "Accept leading underscores for variable names"
  * simple change to allow those characters
  * should **not** pose any backward compatibility issues
2. "Ensure non-variable property names are case-insensitive"
  * simple change to ensure property name matching is performed in a case-insensitive manner
  * should **not** pose any backward compatibility issues 
3. "Fix upper and mixed case variable references"
  * The only problem found with upper and mixed case variable name references occurs in templates
  * All template name references are initially left as provided by the parser (NOT lowercased)
  * If the template option of "`option.casesensitivity`" is "`off`", the default, then the field and property names are forced lowercase (as was the case previously), **maintaining existing behavior**
  * If the template option of "`option.casesensitivity`" is "`on`", then the field and property names are used as-is (this is "opt-in" new behavior)

Feedback welcome.

**Comment by portante** [comment]
@rgerhards, any further thought on this patch?  @theinric?

**Comment by rgerhards** [comment]
I think we are ready to merge, but I didn't manage last week due to unexpected problems with the other PRs. Now I need to look into some other stuff, first. This may require me to back off merging for another two weeks :-( But we should make it for 8.17 in any case.

**Comment by urbaniak** [comment]
:+1:

Looking forward for the next release. ;)

**Comment by rgerhards** [comment]
@portante I have lost a bit track of this ... did you also add accompanying doc to rsyslog-doc? If not, it would be great if you could do so. The merge should hopefully happen today (running throught the final multi-platform testbench right now).

**Comment by portante** [comment]
@rgerhards, I have not waded into the documentation at all.  I can certainly take a stab at that.

**Comment by rgerhards** [comment]
I guess at least this page needs some update: https://github.com/rsyslog/rsyslog-doc/blob/master/source/rainerscript/global.rst

**Comment by portante** [comment]
@rgerhards, I thought it was a template directive modification, I updated the documentation there.  Let me know if that was not what you were looking for, or if I am missing something.

**Comment by rgerhards** [comment]
**I** got lost in the many PRs I have merged recently. Somehow remembered it was a global option...

**Pull request merged**
