### PR TITLE
Support for authenticated redis database.

### PR DESCRIPTION
**Pull request by manu844**
Support for authenticated redis database to push log messages across networks and datacenters.

### CODE REVIEW

**Comment by rgerhards** [comment]
can you please squash this into one commit

**Comment by manu844** [comment]
@rgerhards Below are the changes made.
1. squashed all the commits into one.
2. If serverpassword is not set then do not send auth command to redis server.

**Comment by rgerhards** [comment]
thx! It would also be great if you could update the doc at https://github.com/rsyslog/rsyslog-doc so that others also know this feature exists.

Will merge within the next couple of days.

**Comment by manu844** [comment]
@rgerhards Raised a pull request with updated doc for password support. https://github.com/rsyslog/rsyslog-doc/pull/226

**Comment by rgerhards** [comment]
This is merged, but for some reason github doesn't auto-detect this. So I close the PR manually.

**Pull request closed without merging**
