### PR TITLE
omelasticsearch: add pipeline support

### PR DESCRIPTION
**Pull request by scibi**
Hi!

This PR adds support for pipeline in omelasticsearch.

Fixes: #1411

### CODE REVIEW

**Comment by rgerhards** [comment]
I would be great if you could also update the doc at https://raw.githubusercontent.com/rsyslog/rsyslog-doc/master/source/configuration/modules/omelasticsearch.rst

**Comment by WaeCo** [comment]
Would it also be possible to add a dynamic option for the pipeline parameter (e.g. `dynPipeline <on/off>). Similar to `dynSearchIndex`. 
So the `pipeline` name will be interpreted as a rsyslog template.

**Comment by rgerhards** [comment]
doc was added via rsyslog/rsyslog-doc#384

**Comment by rgerhards** [comment]
merged via https://github.com/rsyslog/rsyslog/pull/1914 - commit hashes do not match because of rebase

**Pull request closed without merging**
